import type { ExternalDoc, RedisFamily, Touchpoint } from "./types.ts";
const ev = (file: string, contains: string) => ({ file, contains });
export const anonymousRateFamily: RedisFamily = {
  key: "rl:anon:<caller address or onion>:<window start>", limiterPrefix: "anon:", holds: "address", windowSeconds: 60,
  purpose: "Anonymous public API reads and MCP messages share one per-client minute counter. Valid API keys retain their existing limits. Tor shares a separate onion counter with ONION_POOL_MULTIPLIER times the limit. Authenticated in-process dispatch and direct private-network traffic without forwarding headers are exempt.",
  ttl: "61 seconds (the 60-second window plus one second)",
  evidence: [ev("src/hardening/middleware.ts", "ctx.limiter.take(`anon:${from.id}`"), ev("src/lib/ratelimit.ts", "await this.redis.pexpire(k, windowMs + 1000)")],
};
export const hardeningAddresses: Touchpoint[] = [
  { file: "src/hardening/client.ts", reads: "The socket address, trusted X-Forwarded-For hop selected from the right by TRUST_PROXY_HOPS, and CF-Connecting-IP only when the enabled origin lock secret matches. The socket is also read to exempt direct private-network callers without forwarding headers from ingress guards.", then: "Validates IP syntax, selects the trusted client address for existing limiters, and rejects public forwarding traffic from private-socket exemptions. No caller address is read for authenticated Tor ingress.", kept: "Address held in request memory and anonymous Redis counter keys for 61 seconds. Existing limit families retain their lifetimes. No database or log address field.", evidence: [ev("src/hardening/client.ts", "export function socketAddress"), ev("src/hardening/client.ts", "hops[hops.length - (cfg?.trustProxyHops ?? 1)]")] },
  { file: "src/hardening/middleware.ts", reads: "Existing per-address bucket for anonymous public API reads and MCP messages; all Tor callers use onion.", then: "Counts against anon with the configured minute limit. Keyed requests, health and readiness, and internal callers are exempt. Redis failure permits the call and logs a fixed warning.", kept: "Counter only; 61 seconds in Redis or until the memory limiter sweep. Never a prompt, key, header, secret or address in logs.", evidence: [ev("src/hardening/middleware.ts", "const from = addressBucket(c, ctx.cfg)")] },
];
export const hardeningBodies: ExternalDoc["bodyReaders"] = [
  { file: "src/hardening/body.ts", carries: "prompt-or-answer", reads: "Request bytes before route dispatch, including ordinary plaintext inference, files and encrypted envelopes. Reads the declared Content-Length and streams up to each route's wire cap; an over-cap chunk is discarded.", then: "Rejects excess bytes with 413 before route side effects; passes a bounded replacement request to existing handlers, preserving the gateway origin record.", kept: "Bounded bytes in request memory only. This guard does not hide plaintext prompts from the router. No new database columns or body logging.", evidence: [ev("src/hardening/body.ts", "const reader = c.req.raw.body?.getReader()")] },
  { file: "src/hardening/middleware.ts", carries: "prompt-or-answer", reads: "The bounded MCP JSON message or batch, including tool arguments and any prompt.", then: "Rejects batches over 20 messages and charges each message against the anonymous minute limit. Existing MCP tool and rulebook guards still apply.", kept: "Parsed message in request memory only; count in the anonymous limiter. No tool arguments or prompts in the counter or logs.", evidence: [ev("src/hardening/middleware.ts", "const msg = await c.req.json()")] },
];
