import type { ExternalDoc, TableDoc } from "./types.ts";
export const notificationReader: ExternalDoc["bodyReaders"][number] = {
  file: "src/notifications/routes.ts", carries: "settings", reads: "A strict complete set of Inbox and Telegram booleans for ten fixed notice types, plus nullable daily UTC quiet-hour clocks.",
  then: "Requires an active management owner principal, excludes session and team keys, revalidates authority under the Telegram link lock and returns no-store.",
  kept: "notification-prefs:<account id> in kv stores channel choices and UTC quiet hours. Weekly Telegram reuses weekly_summary_opted_in on existing links; security switches extend the existing security-alerts:preference row. No credentials or network address.",
  evidence: [{ file: "src/notifications/routes.ts", contains: "preferenceBody.parse(await readJson(c))" }],
};
export const notificationStores: ExternalDoc["otherStores"] = [{
  id: "notification-preferences", name: "Account notification settings and encrypted quiet-hour queue",
  purpose: "One account page controls Inbox and Telegram for approvals, agent alerts, credited deposits, low balance, weekly summaries, security changes, quiet agents, model rate changes, project budgets and scheduled results. Underlying activity and approval records are retained. Feature flags and existing feature choices still apply. Inbox is filtered at read time; weekly Inbox, off by default, projects the latest completed week from existing records for management keys.",
  holds: "notification-prefs:<account id> stores channel booleans and nullable from_utc/to_utc daily clocks. Weekly Telegram reads and writes only existing telegram-link weekly_summary_opted_in columns, and security Inbox/Telegram use the existing security-alerts:preference value with enabled as their aggregate for recording; the older security switch replaces that value and controls both. notification-quiet:<random id> stores account id, Telegram user id and link generation, source and principal key hashes, team id and management snapshot, notice category, due/creation times, a legacy-link marker and text encrypted under APP_SECRET. Text includes notice names and amounts, and can include scheduled answer previews. The router can decrypt these previews; Telegram can read delivered messages. No inference credential, new Redis key, address reader or log field is added. Browser component memory holds the settings and current local clock conversion; nothing new enters browser storage.",
  ttl: "Preferences remain until changed or removed. NOTIFICATION_QUIET_HOURS_ENABLED defaults false: only the enabled minute worker queues and flushes delayed Telegram notices. Approvals are never queued. Each tick reads at most 500 queue entries and sends one bounded-excerpt bundle per recipient and generation; larger backlogs can yield later bundles. Successful delivery removes entries; muted, revoked, unlinked or changed-scope entries are discarded. Failed sends remain for a later attempt. Entries older than seven days are discarded by enabled ticks; flag off pauses queue delivery and cleanup. Delivery can repeat after Telegram accepts a message before transaction commit. The worker revalidates current link, role, team, management status, source key ownership and scheduled-result owner rights. A source feature switched off pauses its queued notices until enabled or expired. Existing sender success counters treat skipped channels or durable queue acceptance as acknowledged delivery. Weekly last_sent_week is marked when a summary enters the queue; a later discarded summary is not resent. Daily clocks are saved in UTC using the device's current offset; saving again is needed after clock or time-zone changes. Future Telegram links retain the existing weekly opt-in default.",
  requestText: "answer-text", evidence: [{ file: "src/notifications/telegram.ts", contains: 'const QUEUE = "notification-quiet:"' }, { file: "src/notifications/prefs.ts", contains: '`notification-prefs:${account}`' }],
}];
export function describeNotifications(docs: Record<string, TableDoc>) {
  docs.kv.notes?.push(notificationStores[0].holds + " " + notificationStores[0].ttl);
  docs.kv.purpose = "The router's small key-value store: job status, cursors, provider facts, sign-in challenges, Telegram state, notification settings and encrypted delayed notice text, including scheduled answer previews.";
  docs.accounts.columns.last_sent_week += " With quiet hours, the week is marked after durable queue acceptance, before actual Telegram delivery. A later revoked, muted or expired queued summary is not resent.";
  const value = docs.kv.columns.value;
  if (typeof value !== "string" && value.review) {
    value.review.verdict = "holds-request-text";
    value.review.why = "Most families hold ids, hashes, timestamps, amounts and settings. The notification-quiet family additionally retains encrypted Telegram notice text, including previews copied from scheduled model answers. APP_SECRET lets the router decrypt them. Queue cleanup and retention are described under this table.";
  }
}
