import type { Evidence, ExternalDoc, RedisFamily, Touchpoint } from "./types.ts";

// Everything the router keeps, or touches, outside Postgres: Redis keys (with their lifetimes and whether they contain a network
// address), the application log, telemetry, backups and the places in the code that read a request's body or a caller's address.
//
// Every statement carries evidence: a file and a line of code that shows it. test/data-inventory.test.ts checks that the file
// exists and still contains that text, and scans the source so a new limiter key, a new log field that reads a request, a new
// reader of a caller's address or a new route that reads a body fails until it is described here.

const ev = (file: string, contains: string, note?: string): Evidence => ({ file, contains, ...(note ? { note } : {}) });

/** Redis key lifetime for a rate-limit window: the window plus one second (RedisRateLimiter.take). */
export const windowTtl = (seconds: number) => `${(seconds + 1).toLocaleString("en-US")} seconds (the ${seconds.toLocaleString("en-US")}-second window plus one second)`;

const RL_KEY = ev("src/lib/ratelimit.ts", "const k = `rl:${key}:${start}`;", "The stored key is rl:<limiter key>:<window start in ms>.");
const RL_TTL = ev("src/lib/ratelimit.ts", "await this.redis.pexpire(k, windowMs + 1000);", "The key expires one second after its window ends.");

function limit(o: { prefix: string; shape: string; purpose: string; holds: RedisFamily["holds"]; seconds: number; evidence: Evidence[] }): RedisFamily {
  return {
    key: `rl:${o.shape}:<window start>`,
    purpose: o.purpose,
    holds: o.holds,
    limiterPrefix: o.prefix,
    windowSeconds: o.seconds,
    ttl: windowTtl(o.seconds),
    evidence: [...o.evidence, RL_KEY, RL_TTL],
  };
}

const ADDRESS_NOTE = "The caller's network address is part of the key. Over Tor the address is replaced by the word onion, so no address is used.";

const redisFamilies: RedisFamily[] = [
  limit({
    prefix: "ip:",
    shape: "ip:<caller address>",
    purpose: `Requests per minute for a call that carries no API key. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 60,
    evidence: [ev("src/api/chat.ts", "await limitOrThrow(ctx, `ip:${from.id}`"), ev("src/api/embeddings.ts", "await ctx.limiter.take(`ip:${from.id}`")],
  }),
  limit({
    prefix: "blind-ip:",
    shape: "blind-ip:<caller address>",
    purpose: `Requests per minute for a call paid with a blind token. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 60,
    evidence: [ev("src/api/chat.ts", "await limitOrThrow(ctx, `blind-ip:${from.id}`"), ev("src/api/embeddings.ts", "await ctx.limiter.take(`blind-ip:${from.id}`")],
  }),
  limit({
    prefix: "newkey:",
    shape: "newkey:<caller address>",
    purpose: `New API keys per hour. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 3600,
    evidence: [ev("src/api/keys.ts", "await ctx.limiter.take(`newkey:${from.id}`")],
  }),
  limit({
    prefix: "wallet-login:",
    shape: "wallet-login:<caller address>",
    purpose: `Wallet sign-in challenges per minute. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 60,
    evidence: [ev("src/api/keys.ts", "await ctx.limiter.take(`wallet-login:${from.id}`")],
  }),
  limit({
    prefix: "pm:",
    shape: "pm:<caller address>",
    purpose: `Paymaster requests per minute. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 60,
    evidence: [ev("src/api/paymaster.ts", "await ctx.limiter.take(`pm:${from.id}`")],
  }),
  limit({
    prefix: "ohttp-gw:ip:",
    shape: "ohttp-gw:ip:<caller address>",
    purpose: `Oblivious HTTP gateway requests per minute from a client that did not come through an authenticated relay. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 60,
    evidence: [ev("src/ohttp/gateway.ts", "`ohttp-gw:ip:${from.id}`")],
  }),
  limit({
    prefix: "ohttp-gw:relay:",
    shape: "ohttp-gw:relay:<relay key id>",
    purpose: "Oblivious HTTP gateway requests per minute for one authenticated relay. It names the relay, not the clients behind it.",
    holds: "nothing-personal",
    seconds: 60,
    evidence: [ev("src/ohttp/gateway.ts", "`ohttp-gw:relay:${relay.keyId}`")],
  }),
  limit({
    prefix: "tlog-cosign:",
    shape: "tlog-cosign:<caller address>",
    purpose: `Transparency-log cosignature submissions per minute. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 60,
    evidence: [ev("src/tlog/routes.ts", "await ctx.limiter.take(`tlog-cosign:${from.id}`")],
  }),
  limit({
    prefix: "claim-issue-ip:",
    shape: "claim-issue-ip:<caller address>",
    purpose: `Creator claim challenges per hour. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 3600,
    evidence: [ev("src/services/creators.ts", "await ctx.limiter.take(`claim-issue-ip:${from.id}`")],
  }),
  limit({
    prefix: "claim-verify-ip:",
    shape: "claim-verify-ip:<caller address>",
    purpose: `Creator claim verifications per hour. ${ADDRESS_NOTE}`,
    holds: "address",
    seconds: 3600,
    evidence: [ev("src/services/creators.ts", "await ctx.limiter.take(`claim-verify-ip:${from.id}`")],
  }),
  limit({
    prefix: "k:",
    shape: "k:<key hash>",
    purpose: "Requests per minute for one API key. Keyed by the SHA-256 of the key; no address is read for a call that carries a key.",
    holds: "key-hash",
    seconds: 60,
    evidence: [ev("src/api/chat.ts", "await limitOrThrow(ctx, `k:${key.keyHash}`"), ev("src/api/embeddings.ts", "await ctx.limiter.take(`k:${key.keyHash}`")],
  }),
  limit({
    prefix: "kc:",
    shape: "kc:<key hash>",
    purpose: "Requests per minute for one API key on the Anthropic-compatible endpoint.",
    holds: "key-hash",
    seconds: 60,
    evidence: [ev("src/api/anthropic.ts", "await ctx.limiter.take(`kc:${key.keyHash}`")],
  }),
  limit({
    prefix: "kt:",
    shape: "kt:<key hash>",
    purpose: "Tokens per minute for one API key: a running count of prompt tokens, not their text.",
    holds: "key-hash",
    seconds: 60,
    evidence: [ev("src/api/chat.ts", "await limitOrThrow(ctx, `kt:${billing.key.keyHash}`"), ev("src/api/council.ts", "tk.limitOrThrow(ctx, `kt:${billing.key.keyHash}`")],
  }),
  limit({
    prefix: "blind:buy:",
    shape: "blind:buy:<key hash>",
    purpose: "Blind-token purchases per minute for one API key.",
    holds: "key-hash",
    seconds: 60,
    evidence: [ev("src/blind/purchase.ts", "await ctx.limiter.take(`blind:buy:${caller.keyHash}`")],
  }),
  limit({
    prefix: "provider-applications",
    shape: "provider-applications",
    purpose: "Provider applications per minute, counted across all callers in one key. There is no per-caller part.",
    holds: "nothing-personal",
    seconds: 60,
    evidence: [ev("src/providers/application.ts", 'await ctx.limiter.take("provider-applications"')],
  }),
  limit({
    prefix: "claim:",
    shape: "claim:<model id>",
    purpose: "Creator claims per hour for one model.",
    holds: "model",
    seconds: 3600,
    evidence: [ev("src/api/public.ts", "await ctx.limiter.take(`claim:${v.model}`")],
  }),
  limit({
    prefix: "claim-issue:",
    shape: "claim-issue:<model id>",
    purpose: "Claim challenges per hour for one model.",
    holds: "model",
    seconds: 3600,
    evidence: [ev("src/services/creators.ts", "await ctx.limiter.take(`claim-issue:${modelId}`")],
  }),
  limit({
    prefix: "claim-verify:",
    shape: "claim-verify:<claim id>",
    purpose: "Claim verifications per hour for one claim.",
    holds: "nothing-personal",
    seconds: 3600,
    evidence: [ev("src/services/creators.ts", "await ctx.limiter.take(`claim-verify:${id}`")],
  }),
  limit({
    prefix: "telegram:",
    shape: "telegram:<Telegram user id>",
    purpose: "Telegram bot messages per minute for one Telegram user. The user id is a number Telegram assigns; the message text is not part of the key.",
    holds: "telegram-user",
    seconds: 60,
    evidence: [ev("src/services/telegram.ts", "await this.ctx.limiter.take(`telegram:${uid}`")],
  }),
  limit({
    prefix: "readiness",
    shape: "readiness",
    purpose: "The readiness probe checks the limiter works by taking zero from a fixed key.",
    holds: "nothing-personal",
    seconds: 60,
    evidence: [ev("src/services/readiness.ts", 'ctx.limiter.take("readiness", 0, 1, 60_000)')],
  }),
  {
    key: "cache:<sha256>",
    purpose:
      "The opt-in response cache (a request that sends cache.mode or the X-Anyroute-Cache header). It holds the answer to a request, so for as long as it lives this is the one place answer text is kept: sealed with AES-256-GCM under a key derived from the router's APP_SECRET and the caller's own scope, so only that caller's identical request can read it back. The Redis key is a SHA-256 of the scope and the request, not the request.",
    holds: "digest",
    requestText: "answer-text",
    ttl: "It is kept for the time-to-live the request asked for in cache.ttl: at most CACHE_TTL_S, which is 3,600 seconds unless the operator changed it, and also the default when the request names none.",
    evidence: [
      ev("src/gateway/cache.ts", "await this.redis.set(`cache:${key}`, JSON.stringify({ payload, upstream: upstream.toString() }), \"PX\", ttlS * 1000);"),
      ev("src/gateway/cache.ts", "const payload = this.seal(scope, response);"),
      ev("src/api/chat.ts", "validateCacheTtl(body, ctx.cfg.gateway.cacheTtlS);"),
      ev("src/api/chat.ts", "billing?.mode !== \"blind\"", "Never used for a blind-token call, a call with a disclosure ceiling, a restricted model variant or a stream."),
    ],
  },
  {
    key: "walletauth:<sha256>",
    purpose: "Replay protection for wallet-signed requests: a marker that a signature was already used. The key is a SHA-256 of the wallet address, the timestamp and the request's hash.",
    holds: "wallet",
    ttl: "600 seconds",
    evidence: [ev("src/api/auth.ts", "`walletauth:${id}`, \"1\", \"PX\", 600_000, \"NX\"")],
  },
  {
    key: "bull:anyroute-jobs-<group>:*",
    purpose: "The background job queue (BullMQ) that makes exactly one replica run each recurring job. The job data is empty ({}), so no request or user data is in it; a finished job's result or failure message is kept for the last 100 completed and 100 failed jobs.",
    holds: "nothing-personal",
    ttl: "Recurring job schedules stay while the router runs; only the most recent 100 completed and 100 failed jobs are kept.",
    evidence: [ev("src/services/jobs.ts", "removeOnComplete: 100, removeOnFail: 100"), ev("src/services/jobs.ts", "upsertJobScheduler(j.name, { every: j.everyMs }, { name: j.name")],
  },
];

const addressReaders: Touchpoint[] = [
  {
    file: "src/api/common.ts",
    reads: "The socket address of the connection or, only when TRUST_PROXY is on, the right-most X-Forwarded-For entry (clientIp).",
    then: "Returned to a caller as the key of a per-address rate limit. Requests that arrived over Tor get the fixed word onion instead of an address (addressBucket).",
    kept: "Not written to Postgres and not logged. It exists in Redis only as part of the rate-limit keys listed above, for at most an hour.",
    evidence: [ev("src/api/common.ts", "export function clientIp(c: Context, trustProxy = false)"), ev("src/api/common.ts", "return { id: \"onion\", onion: true")],
  },
  {
    file: "src/api/chat.ts",
    reads: "The caller's address, only for a call that carries no API key and did not arrive through the Oblivious HTTP gateway.",
    then: "Counted against ip:<address> (or blind-ip:<address> for a blind token).",
    kept: "Only as the Redis rate-limit key.",
    evidence: [ev("src/api/chat.ts", "const from = addressBucket(c, ctx.cfg);")],
  },
  {
    file: "src/api/embeddings.ts",
    reads: "The caller's address, only for a call without an API key.",
    then: "Counted against ip:<address> or blind-ip:<address>.",
    kept: "Only as the Redis rate-limit key.",
    evidence: [ev("src/api/embeddings.ts", "const from = addressBucket(c, ctx.cfg);")],
  },
  {
    file: "src/api/keys.ts",
    reads: "The caller's address when a key is created and when a wallet sign-in challenge is requested.",
    then: "Counted against newkey:<address> and wallet-login:<address>.",
    kept: "Only as the Redis rate-limit keys.",
    evidence: [ev("src/api/keys.ts", "await ctx.limiter.take(`newkey:${from.id}`"), ev("src/api/keys.ts", "await ctx.limiter.take(`wallet-login:${from.id}`")],
  },
  {
    file: "src/api/paymaster.ts",
    reads: "The caller's address on a paymaster request.",
    then: "Counted against pm:<address>.",
    kept: "Only as the Redis rate-limit key.",
    evidence: [ev("src/api/paymaster.ts", "const from = addressBucket(c, ctx.cfg);")],
  },
  {
    file: "src/ohttp/gateway.ts",
    reads: "The caller's address, only for a request that did not come through an authenticated relay. A request through a relay is counted by the relay's key id instead.",
    then: "Counted against ohttp-gw:ip:<address>.",
    kept: "Only as the Redis rate-limit key.",
    evidence: [ev("src/ohttp/gateway.ts", "const from = addressBucket(c, ctx.cfg);")],
  },
  {
    file: "src/tlog/routes.ts",
    reads: "The submitter's address when a witness posts a cosignature.",
    then: "Counted against tlog-cosign:<address>.",
    kept: "Only as the Redis rate-limit key.",
    evidence: [ev("src/tlog/routes.ts", "const from = addressBucket(c, ctx.cfg);")],
  },
  {
    file: "src/api/creator-claims.ts",
    reads: "The caller's address when a creator claim is issued or verified.",
    then: "Handed to services/creators.ts as an address bucket.",
    kept: "Only as the Redis rate-limit keys.",
    evidence: [ev("src/api/creator-claims.ts", "addressBucket(c, ctx.cfg)")],
  },
  {
    file: "src/services/creators.ts",
    reads: "The address bucket it was given.",
    then: "Counted against claim-issue-ip:<address> and claim-verify-ip:<address>.",
    kept: "Only as the Redis rate-limit keys.",
    evidence: [ev("src/services/creators.ts", "await ctx.limiter.take(`claim-issue-ip:${from.id}`")],
  },
  {
    file: "src/api/responses.ts",
    reads: "The caller's address, so the internal chat call it makes on the caller's behalf is limited exactly as the caller's own call would be.",
    then: "Passed to the chat route as an in-process value (requestIP) and then handled as in src/api/chat.ts.",
    kept: "Nothing beyond what src/api/chat.ts keeps.",
    evidence: [ev("src/api/responses.ts", "const from = clientIp(c, ctx.cfg.trustProxy);"), ev("src/api/responses.ts", "{ requestIP: () => ({ address: from }) }")],
  },
  {
    file: "src/onion/ingress.ts",
    reads: "Nothing. It deletes every header that names a client address (X-Forwarded-For, X-Real-IP, CF-Connecting-IP and others) from requests that arrived over Tor, before any route runs.",
    then: "Requests over Tor therefore carry no client address for a route, a limiter or a log line to use.",
    kept: "Not applicable.",
    evidence: [ev("src/onion/ingress.ts", "headers.delete(name);")],
  },
  {
    file: "relay/src/relay.ts",
    reads: "The separate Oblivious HTTP relay (run by relay operators, not by the router) forwards a request's body to a gateway without any header, address or cookie of the client.",
    then: "The forwarded request is built from configuration and the body only. The relay's automated checks fail if its source logs a request or reads a client address.",
    kept: "The relay keeps counters only: totals and fixed reason labels.",
    evidence: [ev("relay/src/relay.ts", "The forwarded request is built from nothing but the configured pieces and the body")],
  },
  {
    file: "sidecar/src/headers.ts",
    reads: "The model-server sidecar inside a provider's enclave forwards only allow-listed headers, so a proxy header cannot carry a client address to the model server.",
    then: "Forwarded by allow-list, not deny-list; a header that names a network address is refused even in configuration.",
    kept: "Not applicable.",
    evidence: [ev("sidecar/src/headers.ts", "Requests are forwarded by allow-list, not by deny-list")],
  },
];

const bodyReaders: ExternalDoc["bodyReaders"] = [
  {
    file: "src/api/chat.ts",
    carries: "prompt-or-answer",
    reads: "The whole JSON body of a chat or text completion: the messages, the model and the parameters (readJson).",
    then: "Read in memory to route the call on every lane: validated, checked against guardrails, priced, then sent to the provider chosen. The request is hashed (request_sha256) and the answer is hashed (response_sha256). Streaming answers are passed through chunk by chunk.",
    kept: "Not stored. Kept in memory for the length of the call. The one exception is the opt-in response cache (see the Redis section), and a failed provider attempt can keep up to 200 characters of that provider's own error message.",
    evidence: [ev("src/api/chat.ts", "const body = await readJson(c);"), ev("src/api/chat.ts", "const bodySha = requestHash(body);"), ev("src/api/chat.ts", "response_sha256: sha256(p.responseText),")],
  },
  {
    file: "src/api/embeddings.ts",
    carries: "prompt-or-answer",
    reads: "The JSON body of an embeddings call: the input text.",
    then: "Sent to the provider chosen and the vectors returned.",
    kept: "Not stored; a generation row and receipt with hashes and counts are written.",
    evidence: [ev("src/api/embeddings.ts", "const body = await readJson(c);")],
  },
  {
    file: "src/api/anthropic.ts",
    carries: "prompt-or-answer",
    reads: "The JSON body of an Anthropic-format messages call.",
    then: "Converted to a chat request and sent through the router's own chat route, so it is handled and kept exactly as a chat call is.",
    kept: "Nothing beyond what src/api/chat.ts keeps.",
    evidence: [ev("src/api/anthropic.ts", "const raw = await readJson(c);")],
  },
  {
    file: "src/api/responses.ts",
    carries: "prompt-or-answer",
    reads: "The JSON body of a Responses-format call.",
    then: "Converted to a chat request and sent through the router's own chat route.",
    kept: "Nothing beyond what src/api/chat.ts keeps.",
    evidence: [ev("src/api/responses.ts", "chatRequestFrom(await readJson(c))")],
  },
  {
    file: "src/api/mcp.ts",
    carries: "prompt-or-answer",
    reads: "The JSON-RPC body of a tool call for the MCP endpoint, which can include a prompt.",
    then: "Turned into a call to the router's own chat route.",
    kept: "Nothing beyond what src/api/chat.ts keeps.",
    evidence: [ev("src/api/mcp.ts", "const raw = await c.req.text();")],
  },
  {
    file: "src/api/rag.ts",
    carries: "prompt-or-answer",
    reads: "The documents and the question of a retrieval call.",
    then: "Cut into chunks and embedded through the router's own embeddings route, ranked in memory, and the best chunks sent to the router's chat route.",
    kept: "Nothing of the documents, question or answer is kept; the chunks and vectors are dropped when the request ends. The response cache is never used.",
    evidence: [ev("src/api/rag.ts", "const raw = await readJson(c);"), ev("src/api/rag.ts", "What is kept: nothing of the documents, the question or the answer.")],
  },
  {
    file: "src/ohttp/gateway.ts",
    carries: "prompt-or-answer",
    reads: "An encapsulated request (Oblivious HTTP). The gateway opens it with its own private key, in memory.",
    then: "Dispatched to the router's own routes as an ordinary request without a client address.",
    kept: "Nothing beyond what the route it reaches keeps. The private key for an epoch is destroyed when its window ends.",
    evidence: [ev("src/ohttp/gateway.ts", "const body = await readCapped(raw.body, cfg.maxRequestBytes);")],
  },
  {
    file: "src/services/telegram.ts",
    carries: "prompt-or-answer",
    reads: "A Telegram message a user sent to the bot (fetched from Telegram by long polling).",
    then: "Sent to the router's own chat route with the user's own API key, so limits, billing and receipts apply.",
    kept: "The message text is not stored or logged; only the user's sealed key and chosen model are (kv table).",
    evidence: [ev("src/services/telegram.ts", "Never logged: keys, message text, the bot token")],
  },
  {
    file: "src/gateway/cache.ts",
    carries: "prompt-or-answer",
    reads: "The request and the answer, only when the caller opted in.",
    then: "Encrypted and stored with a time-to-live (memory and, when configured, Redis). A hit is served without asking a provider.",
    kept: "The sealed answer, for the time-to-live the caller asked for (at most CACHE_TTL_S). A semantic cache also keeps, in memory only, a 1,024-number hashed word vector of the prompt so near-duplicates can match.",
    evidence: [ev("src/gateway/cache.ts", "Never written to Postgres: entries live in memory (or Redis with a TTL)"), ev("src/gateway/cache.ts", "vector: mode === \"semantic\" ? lexicalVector(textOf(body)) : undefined,")],
  },
  {
    file: "src/api/common.ts",
    carries: "settings",
    reads: "The shared JSON body reader used by the routes below: it reads the text, checks its size (16 MB at most) and parses it.",
    then: "Returned to the route.",
    kept: "Nothing.",
    evidence: [ev("src/api/common.ts", "const text = await c.req.text();")],
  },
  {
    file: "src/api/keys.ts",
    carries: "settings",
    reads: "Key settings (name, budget, limits, allowed models), amounts, BYOK provider keys, team roles and wallet sign-in challenges.",
    then: "Validated and written to the keys, byok_keys, teams and kv tables as described above.",
    kept: "The settings and, for a BYOK key, the key encrypted under APP_SECRET.",
    evidence: [ev("src/api/keys.ts", "const spec = keySpec.parse(await readJson(c));")],
  },
  {
    file: "src/api/saved-routes.ts",
    carries: "settings",
    reads: "A saved route: fallback models, provider preferences and sampling controls.",
    then: "Validated against a strict schema with no field for message text, then stored.",
    kept: "The route in saved_routes.",
    evidence: [ev("src/api/saved-routes.ts", "routeCreateSchema.parse(await readJson(c))")],
  },
  {
    file: "src/api/spend.ts",
    carries: "settings",
    reads: "A spend alert rule.",
    then: "Validated and stored.",
    kept: "The rule in spend_alerts.",
    evidence: [ev("src/api/spend.ts", "createBody.parse(await readJson(c))")],
  },
  {
    file: "src/api/agent-sessions.ts",
    carries: "settings",
    reads: "An agent session: name, budget, lifetime and labels.",
    then: "Validated and stored.",
    kept: "The session in agent_sessions.",
    evidence: [ev("src/api/agent-sessions.ts", "createSession(ctx, caller, await readJson(c))")],
  },
  {
    file: "src/api/lane.ts",
    carries: "settings",
    reads: "An operator's description of a model for the model lane: variant, status, licence and weights source.",
    then: "Checked for an operator token, validated and stored.",
    kept: "models_lane.",
    evidence: [ev("src/api/lane.ts", "laneInput.parse(await readJson(c))")],
  },
  {
    file: "src/api/disclosure.ts",
    carries: "settings",
    reads: "A provider disclosure profile written by an operator.",
    then: "Validated and stored.",
    kept: "provider_disclosure.",
    evidence: [ev("src/api/disclosure.ts", "disclosureInput.parse(await readJson(c))")],
  },
  {
    file: "src/api/dayzero.ts",
    carries: "settings",
    reads: "An operator's request to evaluate or approve a day-zero candidate.",
    then: "Validated and stored.",
    kept: "The lane tables.",
    evidence: [ev("src/api/dayzero.ts", "parse(await readJson(c))")],
  },
  {
    file: "src/api/creator-claims.ts",
    carries: "settings",
    reads: "A creator claim: model, wallet address and Hugging Face handle.",
    then: "Validated and stored.",
    kept: "lane_claims.",
    evidence: [ev("src/api/creator-claims.ts", "parse(await readJson(c))")],
  },
  {
    file: "src/api/host-anchor.ts",
    carries: "public-data",
    reads: "A request for an inclusion proof: a receipt envelope from an attested host (hashes and counts, no text) or a leaf hash.",
    then: "Looked up in host_anchor_leaves and answered.",
    kept: "Nothing.",
    evidence: [ev("src/api/host-anchor.ts", "const body = await readJson(c);")],
  },
  {
    file: "src/api/ipx.ts",
    carries: "settings",
    reads: "An operator's switch that halts or resumes the index-price oracle.",
    then: "Checked for an operator token and stored.",
    kept: "The halt flag in the kv table.",
    evidence: [ev("src/api/ipx.ts", "const body = await readJson(c);")],
  },
  {
    file: "src/api/paymaster.ts",
    carries: "payment-or-signature",
    reads: "A paymaster (gas sponsorship) request.",
    then: "Checked and answered.",
    kept: "Nothing beyond the Redis rate-limit key.",
    evidence: [ev("src/api/paymaster.ts", "const body = await readJson(c);")],
  },
  {
    file: "src/api/public.ts",
    carries: "payment-or-signature",
    reads: "Receipt verification requests, pay-with authorisations, provider applications and creator claim challenges.",
    then: "Verified and, for a provider application or a pay-with authorisation, stored.",
    kept: "The provider and pay-with tables described above.",
    evidence: [ev("src/api/public.ts", "const raw = await readJson(c);")],
  },
  {
    file: "src/blind/routes.ts",
    carries: "payment-or-signature",
    reads: "A blinded token request.",
    then: "Signed by the issuer.",
    kept: "Nothing that links the buyer to the token.",
    evidence: [ev("src/blind/routes.ts", "const body = await readJson(c);")],
  },
  {
    file: "src/tlog/routes.ts",
    carries: "public-data",
    reads: "A signed checkpoint note from a witness (16 KB at most).",
    then: "Verified and stored as a cosignature.",
    kept: "tlog_cosignatures.",
    evidence: [ev("src/tlog/routes.ts", "const body = c.req.raw.body;")],
  },
];

const noLog = (item: string, file: string, contains: string): { item: string; evidence: Evidence[] } => ({ item, evidence: [ev(file, contains)] });

export const EXTERNAL: ExternalDoc = {
  redis: {
    summary:
      "Redis holds rate-limit counters, the opt-in response cache, replay markers and the job queue. It is optional in development and required in production. Every key expires; the rate-limit keys below are the only place a caller's network address is used, and only for calls without an API key.",
    families: redisFamilies,
    memoryFallback: {
      purpose: "Without Redis (development) the same rate-limit counters live in the router process's memory and are removed once their window started more than five minutes ago (checked every minute). Nothing is written to disk.",
      ttl: "About five minutes after the window started.",
      evidence: [ev("src/lib/ratelimit.ts", "const cutoff = Date.now() - 5 * 60_000;"), ev("src/config.ts", "Production requires authenticated Redis.")],
    },
  },
  logs: {
    summary:
      "The router writes one JSON line per event to standard output (standard error for warnings and errors). A line is a time, a level, a fixed message and a few fields chosen at each call site. No call site writes a request or response body, a header, a client address, a query string or a prompt.",
    format: "JSON lines: { t, level, msg, ...fields }.",
    records: [
      "The time, the level and a message written in the code.",
      "Identifiers and counts: provider ids, model ids, job names, hold and generation ids, epochs, block numbers, transaction hashes, hashed key ids and, on rare settlement and escrow events, an account id.",
      "Wallet addresses of payers on pay-per-call and pay-with events (public on chain).",
      "For an unhandled error: the path of the request without its query string, the error message and the first five lines of the stack.",
      "Error messages from libraries and upstream services, each cut to 200 characters where a call site truncates them.",
    ],
    neverRecords: [
      noLog("Client network addresses. No log call passes one; the only code that reads an address returns it to a rate limiter.", "src/api/common.ts", "return { id: clientIp(c, cfg.trustProxy), onion: false"),
      noLog("Request or response bodies and prompts. The unhandled-error line takes the path and the error, not the body.", "src/app.ts", "log.error(\"unhandled error\", { path: new URL(c.req.url).pathname"),
      noLog("Request headers, cookies and API keys. The Telegram bot states the same rule for its own lines.", "src/services/telegram.ts", "Never logged: keys, message text, the bot token"),
      noLog("Query strings: only the pathname of a failing request is logged.", "src/app.ts", ".pathname, error: (err as Error)?.message"),
    ],
    caveats: [
      "The text of an unexpected exception is logged as the library wrote it (src/app.ts unhandled error, src/lib/process-guard.ts uncaught exception, job failures). No code path puts request text into an error message on purpose, but the router does not filter such messages, and a library error could quote a fragment of what it was parsing.",
      "The hosting platform's own network layer sees connection addresses and may keep its own access logs. This inventory covers what the router's code records; it cannot describe the platform's logs.",
    ],
    retention: "The router does not rotate or store its logs: it writes them to standard output and the hosting platform keeps them under its own retention. No log retention is set in this repository.",
    evidence: [ev("src/lib/util.ts", "(level === \"error\" || level === \"warn\" ? console.error : console.log)(line);"), ev("src/lib/util.ts", "const line = JSON.stringify({ t: new Date().toISOString(), level, msg, ...fields }")],
  },
  otherStores: [
    {
      id: "response-cache-memory",
      name: "Response cache in the router's memory",
      purpose: "The opt-in response cache also keeps each entry in the router process's memory (up to 5,000 entries), whether or not Redis is configured.",
      holds: "The same sealed answer as the Redis entry, and for the semantic mode a hashed word vector of the prompt.",
      ttl: "An entry is not served after its time-to-live, but it stays in memory until newer entries push it out (oldest first, at 5,000) or the process restarts.",
      requestText: "answer-text",
      evidence: [ev("src/gateway/cache.ts", "constructor(private secret: string, private maxEntries = 5_000"), ev("src/app.ts", "cache: new ResponseCache(cfg.appSecret, 5_000, redis)")],
    },
    {
      id: "replay-memory",
      name: "Replay guards in memory",
      purpose: "Two small in-memory sets stop replays: a used wallet signature (when Redis is not configured) and an Oblivious HTTP encapsulated request prefix.",
      holds: "SHA-256 digests of a wallet address, timestamp and request hash, and of the first bytes of an encapsulated request. Not the request.",
      ttl: "Ten minutes for a wallet signature (old entries are swept once the set passes 50,000); until the key's acceptance window ends for an encapsulated request, with at most 100,000 kept.",
      requestText: "hashes",
      evidence: [ev("src/api/auth.ts", "const seen = new Map<string, number>();"), ev("src/ohttp/replay.ts", "This remembers recent ones in")],
    },
    {
      id: "private-lane-counters",
      name: "Private-lane counters in memory",
      purpose: "Differentially private hourly counters for the attested and unlinkable lanes: how many requests, how many were refused and why, latency and token buckets. They contain no request, no address, no key and no timestamp finer than an hour.",
      holds: "Four families of counts for the current hour, released once with noise when the hour ends; the raw counts are then discarded.",
      ttl: "Released hours are kept for 48 hours; the privacy-budget ledger for 30 days.",
      requestText: "none",
      evidence: [ev("src/lib/dpstats.ts", "What it keeps: four families of counters for the current hour, and nothing else."), ev("src/services/private-stats.ts", "The router still keeps its per-request rows for billing", "The private lanes still leave the per-request rows described under Postgres; only the published aggregates are noisy.")],
    },
    {
      id: "telemetry",
      name: "Trace export (OpenTelemetry), off unless an endpoint is set",
      purpose: "When OTEL_EXPORTER_OTLP_ENDPOINT is set, one span per chat or text-completion call is sent to that endpoint: model, provider, token counts, cost, generation id, mode, attempt count, whether it streamed, and the trace id from a traceparent header if the caller sent one. Calls on the attested and unlinkable lanes send no span. Spans carry no prompt or completion.",
      holds: "The attributes listed, buffered in memory for up to five seconds before export.",
      ttl: "In memory for seconds; kept by whatever receives it, which the operator chooses.",
      requestText: "none",
      evidence: [
        ev("src/api/chat.ts", "if (!privateLane) ctx.telemetry.span(\"chat \" + r.model.id"),
        ev("src/api/chat.ts", "p.c.req.header(\"traceparent\")?.split(\"-\")[1]"),
        ev("src/gateway/otel.ts", "Spans never carry prompt or completion content."),
      ],
    },
    {
      id: "backups",
      name: "Encrypted database backups",
      purpose: "A scheduled pg_dump (daily in the reference deployment) of the whole database, encrypted to public age recipients and uploaded to S3-compatible storage. Every table listed on this page is in it. The private key that opens it is never on the host that makes the backup.",
      holds: "The database as it was when the backup ran.",
      ttl: "The code writes each archive under a new key and never deletes one; how long archives last is set by the storage bucket's own rules, which are not in this repository.",
      requestText: "none",
      evidence: [ev("scripts/backup-offsite.ts", "The private age identity never belongs on this host"), ev("scripts/backup-offsite.ts", "pg_dump custom-format archive encrypted to public age recipients")],
    },
  ],
  addressReaders,
  bodyReaders,
  browser: {
    summary: "What this website keeps in your own browser. None of it is sent to us except the requests you make.",
    items: [
      { store: "sessionStorage", holds: "The API key you pasted into the dashboard, for the length of the tab. It is removed when the tab closes and is never written to localStorage.", evidence: [ev("web/lib/api.js", "sessionStorage.setItem(keyStore, secret);")] },
      { store: "localStorage", holds: "The Harness favourite models and view preferences, and the Eval Lab evaluation sets you write. Eval Lab results are kept in IndexedDB. The router never receives them; only the requests you run do.", evidence: [ev("web/components/Harness.jsx", "localStorage.setItem(k, JSON.stringify(v));"), ev("web/components/features/EvalLab.jsx", "Eval sets live in localStorage")] },
    ],
  },
};
