import type { ExternalDoc, TableDoc } from "./types.ts";
const retention = "quiet-agent-alert:<key hash>: per-agent hours (null means off), enable timestamp, last claimed quiet-period activity timestamp, and newest 100 notices with random id, timestamp, readable agent-name title, hour window and last charged-call/Guard-decision time. Settings and the dedupe anchor persist until operator deletion. Enabled runs and changed settings prune notices older than 90 days; disabled cleanup pauses, while inbox reads hide expired notices. Deleted keys leave inaccessible settings until operator deletion. No rulebook field, table, column, Redis family, address reader or log field is added.";
export function describeQuietAlerts(docs: Record<string, TableDoc>) { docs.kv.notes!.push(retention); }
export const quietAlertBodyReader: ExternalDoc["bodyReaders"][number] = {
  file: "src/api/quiet-agent-alerts.ts", carries: "settings",
  reads: "A strict JSON object with hours null or one of 1, 3, 6, 12, 24, 72; no other field is accepted.",
  then: "Requires the existing agent owner/admin principal and same account/team ownership, explicitly refuses inference keys, and writes settings outside the rulebook under the account lock. Disabled endpoints return 404 before reading a body.",
  kept: retention, evidence: [{ file: "src/api/quiet-agent-alerts.ts", contains: "body.parse(await readJson(c)).hours" }],
};
export const quietAlertStores: ExternalDoc["otherStores"] = [{
  id: "quiet-agent-alerts", name: "Quiet-agent settings, inbox notices and Telegram delivery",
  purpose: "With QUIET_AGENT_ALERTS_ENABLED and agent rulebooks on, a five-minute non-API worker reads saved settings, current keys and Stop state, existing charged ledger timestamps (usage/tool_call/data_tool) and Guard decision timestamps, including agent session children in the same account. Disabled, expired and stopped keys are excluded. A keyset scan covers settings in pages of 100. Per-agent claims commit under the account lock before sending. A new activity timestamp re-arms the alert, with no writes on the call path. Free uncharged generations and rulebook previews do not count. The clock begins at the last recorded activity, or enable time when no activity is recorded. Resumed keys become eligible using the existing clock.",
  holds: retention + " The account inbox exposes these notices only to management keys and team owner/admin principals outside sessions, scoped by current account/team ownership. The browser keeps settings and save status in component memory only. Agent names enter readable notice titles and Telegram messages; user-chosen names can contain personal text. No inference prompt, answer, action target, Guard details, wallet address or API secret is read by this feature.",
  ttl: "History is bounded to 100 per agent and 90 days when cleanup runs. Settings and notified_for remain even while off. Saving or changing the choice preserves the last claimed activity timestamp; only later activity re-arms a previously reported period. Telegram uses existing linkedAlertTargets/sendLinkedAlert and their current principal checks and unlink lock. One attempt per eligible link after each saved claim; a crash or failed send can lose delivery with no retry. No message id or send-result metadata is added.",
  requestText: "none", evidence: [{ file: "src/agents/quiet-alerts.ts", contains: 'export const QUIET_PREFIX = "quiet-agent-alert:"' }, { file: "src/agents/quiet-alerts.ts", contains: 'ctx.jobs.register("quiet-agent-alerts", 300_000' }],
}];
