import type { ExternalDoc } from "./types.ts";

export const rushKvNotes = ["upstream-balance:<provider id>: latest USD balance or explicit unknown/unsupported state and check time; upstream-credit-hold:<provider id>: expiry of a five-minute provider-wide routing hold after explicit insufficient credits or a zero balance. Enabled only by UPSTREAM_MONITOR_ENABLED. Overwritten in place; expired hold rows remain until operator deletion. No response text, API keys or caller identifiers are copied. Alerts use the existing alerts:state and alerts:lease rows and configured operations webhook."];
export const rushStores: ExternalDoc["otherStores"] = [{
  id: "rush-operations", name: "Operator capacity and daily counts",
  purpose: "The operator-only GET /trpc/rush reads daily aggregate milestones over at most 90 UTC days. New wallet sign-ins mean wallet accounts created with a management key at the same transaction timestamp; an account created earlier by a deposit is excluded. First credited deposits mean the first positive deposit, stock_deposit or anyr_deposit ledger row per account. First successful calls mean the first signed generation per account that was not cancelled and did not finish with an error. Earlier retained rows are checked to exclude repeats; deleted historical records cannot be reconstructed. No per-account rows leave these queries.",
  holds: "Daily counts and dates; latest upstream USD balances, check states and hold expiry times on the operator surface only. In memory the enabled monitor reads the existing encrypted provider credential and configured headers to authenticate a documented balance check; neither credential nor upstream response text is retained in the new state or logs. API replicas refresh temporary holds on health flushes. The catalogue cache holds up to 64 public catalogue JSON variants and 64 in-flight computations, keyed only by the four supported public catalogue filters. It contains catalogue metadata, prices, capabilities and provider evidence, never inference text or caller addresses. No new table, column or Redis family.",
  ttl: "Aggregate responses discarded after delivery with no-store. Catalogue JSON expires after 30 seconds or successful catalogue sync; process memory disappears on exit. Routing holds expire after five minutes. Existing source retention applies.", requestText: "none",
  evidence: [{ file: "src/rush/funnel.ts", contains: "export async function readFunnel" }, { file: "src/rush/cache.ts", contains: "export const CATALOG_TTL_MS = 30_000" }, { file: "src/rush/monitor.ts", contains: "export const CREDIT_HOLD_MS = 5 * 60_000" }, { file: "src/admin/trpc.ts", contains: 'c.header("cache-control", "no-store")' }],
}];
