import type { ExternalDoc, TableDoc } from "./types.ts";
export function describeScheduledPrompts(docs: Record<string, TableDoc>) {
  docs.schedules = { category: "operations", purpose: "Owner-chosen recurring prompts and the key that pays for each ordinary chat call.", request: "no", retention: "Until the owner deletes the schedule. Deletion cascades to its saved runs. Database backups follow the operator's retention policy.", columns: {
    id: "Random schedule identifier.", account_id: "Owning account identifier.", owner_hash: "Hash of the owner key that last saved the schedule; rechecked before each run.", key_hash: "Hash of the paying key; its normal budget, rulebook, lane and approval checks apply.", name: "Owner-chosen schedule name, also shown in inbox and Telegram.",
    prompt_enc: { purpose: "The complete owner-chosen prompt, encrypted with AES-GCM using APP_SECRET scoped to the account and schedule.", request: "yes", review: { covers: ["name:content"], verdict: "holds-request-text", why: "This is stored prompt text, encrypted at rest with a router-held secret. The router decrypts it for scheduled inference; encryption does not prevent Anyroute from reading it." } },
    model: "Selected model identifier.", cadence: "Hourly, daily or Monday recurrence.", time_utc: "UTC hour and minute for daily or Monday recurrence; null for hourly.", max_cost_pico: "Required per-run cost ceiling in pico-USD, checked against the normal worst-case hold before inference.", paused: "Whether automatic runs are paused, including after three consecutive failures.", failures: "Consecutive refused, failed or interrupted run count.", next_at: "Next due UTC instant; missed intervals are coalesced into one run.", created_at: "When the owner created the schedule.",
  } };
  docs.schedule_runs = { category: "request", purpose: "The last ten claimed scheduled runs, including encrypted replies and bounded failure reasons.", request: "yes", retention: "Last ten runs per schedule, pruned at the next claim; all removed when the schedule is deleted. Ordinary billing and receipt records retain their existing lifetimes.", columns: {
    id: "Random run identifier.", schedule_id: "Parent schedule identifier; deletion cascades.", due_at: "Unique due slot per schedule; coordinates competing workers without Redis.", started_at: "When the run was claimed.", finished_at: "When the run succeeded, failed or was marked interrupted.", status: "Running, succeeded or failed.",
    reply_enc: { purpose: "The full returned reply, encrypted with the same account-and-schedule AES-GCM scope as the prompt.", review: { covers: ["name:content"], verdict: "holds-request-text", why: "This column keeps actual answer text encrypted under a router-held secret. It is decrypted for authorized owners and the first 300 characters are included in inbox and Telegram notices." } },
    reason: "Bounded machine error code, never the upstream message or request text.", generation_id: "Preselected ordinary generation identifier linking the run to its charge and receipt, including an uncertain interrupted call.", notified: "One outbound Telegram attempt claimed before delivery; failed or interrupted sends are not retried.",
  } };
}
export const scheduledPromptsReader: ExternalDoc["bodyReaders"][number] = {
  file: "src/api/schedules.ts", carries: "prompt-or-answer", reads: "Owner-chosen name, prompt, model, paying key hash, recurrence, UTC time, cost ceiling and pause state.",
  then: "Requires an active owner or management key, excludes inference and session keys, verifies ownership of the paying key, and encrypts the prompt before saving it.",
  kept: "Prompt ciphertext and schedule metadata in schedules; last ten encrypted replies and bounded failure reasons in schedule_runs. Deleted with the schedule. Ordinary chat still reads text in memory and retains billing metadata.",
  evidence: [{ file: "src/api/schedules.ts", contains: "fields.parse(await readJson(c))" }],
};
export const scheduledPromptsStores: ExternalDoc["otherStores"] = [{
  id: "scheduled-prompts-delivery", name: "Scheduled result notifications and browser view", purpose: "Authorized owners read their saved schedules and results. The existing inbox shows one item per finished retained run. Linked Telegram delivery receives the name, first 300 reply characters or a failure code, and an authenticated result link.",
  holds: "Decrypted prompt and reply text in router and browser memory, and a reply excerpt in Telegram, which can read and retain it under its own policy. The browser does not persist scheduled prompt or reply text. No new Redis key family or application log field.",
  ttl: "Router and browser memory lasts for the request or open page. Telegram follows its own retention policy; deleting a schedule does not erase delivered Telegram messages. Saved database content and its inbox item disappear with the schedule; billing records and backups retain their existing policies.", requestText: "request-and-answer-text",
  evidence: [{ file: "src/schedules/worker.ts", contains: "reply.slice(0, 300)" }, { file: "src/schedules/store.ts", contains: "decrypt(contentScope(ctx, row), text)" }],
}];
