import type { ExternalDoc, TableDoc } from "./types.ts";
export function describeSealed(tables: Record<string, TableDoc>) {
  tables.kv.notes!.push("sealed-agent:<key hash>: owner-selected HTTPS /attest URL, expected image digest and measured compose hash, random registration revision, last check timestamp, fixed success/failure code, verifier names and verified TLS SPKI hash. Overwritten on registration and each check; deleted by the principal's DELETE endpoint. No quote, certificate, API credential or inference content is stored. Owner-selected hostnames are settings and may carry meanings chosen by that owner. Records remain while disabled until explicitly removed; badge success expires after 30 minutes.");
}
export const sealedBodyReaders: ExternalDoc["bodyReaders"] = [{ file: "src/api/agent-sealed.ts", carries: "settings", reads: "Strict registration settings: HTTPS /attest URL without query, image digest and measured compose hash.", then: "Requires principal ownership of the active non-management key, obtains fresh quote evidence through guarded public-only pinned TLS and verifies key fingerprint and measured deployment.", kept: "Registration settings, random revision, fixed result codes, verifier names, TLS key hash and check time in the sealed-agent kv family; never inference bodies or API credentials. No new Redis family or log field.", evidence: [{ file: "src/api/agent-sealed.ts", contains: "registrationSchema.parse(await readJson(c))" }] }];
export const sealedOtherStores: ExternalDoc["otherStores"] = [{
  id: "sealed-agent-sidecar", name: "Owner's sealed agent VM", purpose: "The dedicated agent sidecar uses the guest agent's application-scoped GetKey with a measured-compose-specific path to seal a provisioned AnyRoute credential with AES-256-GCM. It obtains TDX quotes committing the key fingerprint, image, measured compose, version and TLS key. The internal proxy forwards agent request and response streams to fixed paths at the configured HTTPS router origin.",
  holds: "An encrypted credential file in the VM's sealed volume. Raw credential and guest-derived key enter process memory during provisioning or boot; the API credential is sent to AnyRoute as Bearer authentication over TLS. The agent container receives no credential. Provisioning input, guest console retention and any owner-held credential copies remain the owner's responsibility. VM software and administrators can access guest memory. JavaScript strings cannot be reliably erased. No prompt or answer file is written by the sidecar.",
  ttl: "Ciphertext survives restarts until volume removal or replacement. Memory lasts for the sidecar process; the KMS key is scoped to app identity and a path containing the measured compose. Manifest changes require fresh provisioning. No anti-rollback guarantee is provided.", requestText: "request-and-answer-text", evidence: [{ file: "sidecar/src/agent/credential-store.ts", contains: "cipher.setAAD(aad(compose))" }, { file: "sidecar/src/agent/runtime.ts", contains: 'headers.set("authorization", `Bearer ${credential}`)' }],
}];
