import type { ExternalDoc, TableDoc } from "./types.ts";
export const securityAlertReader: ExternalDoc["bodyReaders"][number] = {
  file: "src/security-alerts/routes.ts", carries: "settings", reads: "An account management key's strict enabled boolean for security alerts.",
  then: "Requires the existing owner/admin principal guard plus management rights; session keys and team administrators cannot change account-wide preferences. Returns no-store. SECURITY_ALERTS_ENABLED defaults to false, returning 404 while off.",
  kept: "The boolean under security-alerts:preference:<account id> in existing kv until changed or account data is removed. No request text or caller network address.",
  evidence: [{ file: "src/security-alerts/routes.ts", contains: "preferenceBody.parse(await readJson(c))" }],
};
export const securityAlertStores: ExternalDoc["otherStores"] = [{
  id: "security-alerts-kv", name: "Account security changes and delivery cursor in kv",
  purpose: "With SECURITY_ALERTS_ENABLED, existing key rows, agent policy events and team audit writers record security changes, including those made by the signed-in key. A thirty-second worker claims pending events once, adds inbox items and attempts Telegram delivery through the existing linked-alert helper. Management keys see their account; team owners and administrators see only their team; ordinary and session keys see no security items. Account preferences default on while the feature is enabled.",
  holds: "security-alerts:event:<change id, policy event id, or team id and sequence> holds account id, nullable team id, inbox-arrival timestamp (recording time while pending), readable title and pending/inbox/muted state. Titles contain sanitized key and team names, management status, the kind of change and the acting key name. The request middleware holds only a digest of the presented Bearer key in an asynchronous request scope to correlate the already-authenticated team audit writer with its exact acting key; no credential is retained. Team audit entries authenticated by wallet or passkey name that member type instead of inventing a key. Wallet sign-in reads the already-verified account wallet in memory, keeping only its first six and last four characters in a sign-in title. Full wallet addresses, key secrets, prompt text, policy contents, stop reasons and Telegram messages are not copied. security-alerts:cursor keeps a processed-event count and lock; per-event states are the durable cursor so late commits and equal timestamps remain eligible. security-alerts:preference:<account id> keeps the enabled boolean. Telegram can read the security titles and key names it receives. Unlinked members receive no later alert, including their unlink notice; other eligible links may receive it.",
  ttl: "Claimed and muted event rows are removed after ninety days by enabled worker runs; pending events remain until claimed. Flag off pauses recording, delivery, inbox projection and cleanup. Events from before recording was enabled are not reconstructed. Preference and cursor rows remain until removed. Claims commit before one send attempt per eligible link: worker crashes, failed and ambiguous sends can leave an inbox item without Telegram delivery; sends are not retried. Key change hooks use the existing write boundaries; changes whose key write commits but notice write fails can miss a notice. Policy, team audit and Telegram notices commit with their source transaction. No new database table/column, Redis family or log field; the settings route is the only new request-body reader.",
  requestText: "none", evidence: [{ file: "src/security-alerts/worker.ts", contains: 'const CURSOR = "security-alerts:cursor"' }, { file: "src/security-alerts/records.ts", contains: "export async function recordPolicySecurity" }, { file: "src/security-alerts/worker.ts", contains: 'ctx.jobs.register("security-alerts", 30_000' }],
}];

export function describeSecurityAlerts(docs: Record<string, TableDoc>) {
  docs.kv.notes?.push(securityAlertStores[0].holds + " " + securityAlertStores[0].ttl);
}
