import type { ExternalDoc, TableDoc } from "./types.ts";
import { rv } from "./tables/common.ts";
export const webhookTables: Record<string, TableDoc> = {
  webhook_destinations: { category: "operations", request: "no", purpose: "Owner-controlled HTTPS destinations, encrypted signing credentials and subscriptions for account event notices.", retention: "Until destination removal or linked Spend Watch rule deletion. Revocation erases the encrypted signing key and stops deliveries; database backups can outlive removal.", columns: {
    id: "Random destination identifier, scoped to one account.", account_id: "Account whose owner manages this destination.", created_by: "API key hash used for visibility and authorization; never a raw API key.", key_hash: "Optional key scope inherited from a Spend Watch rule; null is account-wide.", rule_id: "Optional linked Spend Watch rule identifier, removed with that rule.", url_enc: { purpose: "HTTPS URL encrypted under APP_SECRET; path and query can hold receiver credentials. API responses show scheme and host only.", review: rv(["name:network"], "config", "Owner-supplied delivery endpoint sealed using APP_SECRET, never the caller network address. URLs can identify the receiver and carry credentials, so only scheme and host are returned.") }, secret_enc: "Server-generated random signing secret encrypted under APP_SECRET, null for an unsigned legacy or revoked destination. Plaintext is revealed only on creation or rotation, never in subsequent reads or delivery logs.", revoked: "Whether delivery has been stopped and its signing credential removed.",
    events: { purpose: "Selected fixed event type identifiers.", review: rv(["type:json"], "config", "Strict event names chosen by the owner, excluding arbitrary text, addresses, prompts or answers.") },
    scan: { purpose: "Bounded reader progress: time window, activity cursor and sweep time.", review: rv(["type:json"], "no-request-content", "Only timestamps, pagination filter digest and event identifiers; no activity bodies, intent text, endpoint URL or credentials.") },
    created_at: "Creation time and lower bound for event discovery.",
  } },
  webhook_deliveries: { category: "operations", request: "no", purpose: "Durable event references, duplicate suppression and delivery attempt metadata without webhook bodies.", retention: "Terminal records are deleted after 90 days by the enabled worker; pending records remain until attempted or cancelled. Destination removal cascades deletion. Each event has at most three recorded attempts, and the API returns the last 100 attempts.", columns: {
    id: "Random internal delivery identifier.", destination_id: "Owned destination association.", event_id: "Stable identifier sent in the event header, shared across retries for duplicate suppression.", event: "Fixed event type name; endpoint.check is an owner-requested connectivity notice.", reference: "Source identifier only, such as a ledger, policy event, agreement or host id. No source body is copied.", event_at: "Source event time used for retention and ordering.", event_status: "Fixed source status at discovery, not arbitrary source text.", attempts: "Claimed delivery attempt count, capped at three.", status: "Fixed delivery state: pending, delivered, blocked, failed or cancelled.", http_status: "Receiver HTTP status code, never its response body.", latency_ms: "Elapsed time for the attempted send in milliseconds.", attempted_at: "When the most recent result was recorded.", next_attempt: "Retry lease and due time; ordinary retries wait five minutes.",
    history: { purpose: "Up to three attempt timestamps, delivery state, HTTP status, latency and retry count.", review: rv(["type:json"], "no-request-content", "Fixed result codes and numeric timing/count metadata only; excludes webhook bodies, receiver bodies, URL, signature headers, signing secret and exception text.") },
  } },
};
export const webhookBodyReader: ExternalDoc["bodyReaders"][number] = { file: "src/webhooks/routes.ts", carries: "settings", reads: "Bounded JSON containing an HTTPS destination URL and selected fixed event types.", then: "Requires an authenticated owner/admin outside agent sessions. New account-wide destinations require a management key; non-management callers see and control only destinations scoped to their own key.", kept: "URL and generated signing key are encrypted under APP_SECRET. Selected event identifiers are retained. Subsequent responses redact the path/query and omit credentials. No new Redis family, log field, prompt/answer reader or caller-address reader.", evidence: [{ file: "src/webhooks/routes.ts", contains: "create.parse(await readJson(c))" }] };
export const webhookStores: ExternalDoc["otherStores"] = [{ id: "signed-webhooks", name: "Signed account event delivery", purpose: "When WEBHOOK_SIGNING_ENABLED is enabled, a minute worker reads at most 50 destinations, one 100-row activity page per destination, and sends at most 100 due notices per tick. Activity readers retain account, key, team and wallet-party guards. It delivers metadata references, fixed types/statuses and timestamps; existing Spend Watch and agent delivery retain their original alert fields. Signing covers exact wire JSON bytes plus a timestamp. The signed body binds event_id to the header. Secrets use the existing APP_SECRET encryption helper. Legacy URLs remain unsigned until rotation. Revocation stops future deliveries; an already in-flight request can finish. The disabled flag retains original alert delivery without signing, imports or worker writes.", holds: "Decrypted URLs and signing secrets enter router process memory only for delivery or credential issuance. Account wallet and host operator addresses are read by the status-write hook to match operated hosts. No prompt/answer is added to deliveries, and no arbitrary response or transport error text is logged. The browser holds a newly revealed signing secret in component memory until dismissed, disconnected or navigation; it is not written to browser storage.", ttl: "Activity discovery begins at destination creation, uses five minutes of overlap and durable pagination, and can miss source rows removed before discovery or commits delayed beyond the overlap. Approval requests/decisions and operated host status changes enqueue references in the transaction that records the change, so changes between worker ticks are retained. Approval references are approval ids. Direct database writes outside the router do not generate these notices. Delivery can repeat after a crash before result persistence: receivers must verify exact bytes with a five-minute timestamp tolerance and atomically deduplicate event ids. Delivery metadata is retained for 90 days; the API shows 100 attempts. Three attempts per event, five minutes apart. Owner-requested connectivity notices are limited to one per destination per minute.", requestText: "none", evidence: [{ file: "src/webhooks/worker.ts", contains: "export async function runWebhooks" }, { file: "src/webhooks/delivery.ts", contains: "const wire = secret ?" }, { file: "src/webhooks/hosts.ts", contains: "export async function recordHostStatus" }, { file: "src/webhooks/approvals.ts", contains: "export async function recordApprovalWebhook" }] }];
