export default function AgentBreakersDocs() {
  return <section id="agent-breakers"><h3>Circuit breakers</h3>
    <p>An optional rulebook field, breakers, accepts max_spend_usd_per_minute (positive USD up to 1,000,000), max_requests_per_minute, max_denials_per_10min and max_distinct_models_per_hour (positive safe integers). Omitted fields add no restriction. AGENT_POLICY_ENABLED, default false, also controls breakers.</p><p>Switched on at anyroute.tech.</p>
    <p>Before each policy admission, the router checks recorded rolling counters under the account lock. A value equal to or above a limit trips the kill switch with reason breaker: followed by the field name. That request receives HTTP 403 agent_killed before any reservation or charge. A trip overrides an on_breach action of deny and cannot permit anything another rule denies. These controls apply to requests through Anyroute only, with no on-chain enforcement.</p>
    <p>Spend is charged usage from the last minute plus open usage reservations. Requests and denials count policy admission batches; a batch with several models counts once, and every distinct requested model is observed, including denied models. An MCP tool admission and its routed inference are separate admissions. Approval-required attempts count as requests, not denials. Earlier decision events without a batch marker each count as an observation.</p>
    <p>The principal resumes manually. Resume resets breaker observations and the spend window while leaving budget-cap spend intact; in-flight work may finish and later charges can trip the breaker again. Spend breakers also refuse an estimate that would cross the limit, and distinct-model breakers check the complete requested model set before admitting it. Equality is permitted for a new estimate or model set; the next admission trips at the recorded threshold. Final charges can exceed estimates; budget caps remain independent.</p>
    <p>Breaker metadata uses the existing rulebook and event tables, with the same 90-day event retention. No prompt or response text is added. Ordinary inference paths still let Anyroute’s router and the answering provider read request text in memory. The agent page includes breaker fields and a “Tripped by” badge.</p>
  </section>;
}
