export default function AgentProfileDocs() {
  return <section className="doc-section" id="agent-profiles"><h2>Opt-in public agent profiles</h2>
    <p>AGENT_PROFILES_ENABLED defaults to false. With it off, profile APIs return 404 and the directory MCP tool is omitted. Apply the additive agent_profiles migration before enabling it. Rulebook categories require AGENT_POLICY_ENABLED; selected certificates also require TLOG_ENABLED and its existing signing configuration.</p>
    <p>An owner or authorised account administrator publishes with PUT /api/v1/agents/:key_hash/profile. GET on the same path reads publication settings; DELETE unpublishes and deletes the row. Use an owner API key; session keys cannot manage profiles. The request accepts name (1–80 characters), description (up to 280), optional HTTP(S) homepage (up to 500, no embedded credentials), capabilities (up to 16 tags, 1–40 characters each), show (selected spending_caps, ask_first, kill_switch categories), and certificate_claims (up to 16 distinct supported record claims). Omitted selections default to empty.</p>
    <p>Only selected rulebook booleans are returned, including applicable inherited rules. Exact spending amounts, approval thresholds, model and tool restrictions, policy hashes, kill reasons, key hashes and account identifiers are not automatically published. Owner-written names, tags, descriptions and homepages can identify their owner. Capabilities are supplied by the owner and are not verified abilities.</p>
    <p>Certificate claims are checked against the selected key’s retained records and issued with a fresh pseudonym. Updates replace the selected certificate; empty claims remove it. Public reads verify its signature, signing-key issuance window and expiry. Expired or invalid certificates are omitted. The card adds valid:true as read-time metadata; remove valid before passing a certificate to strict certificate verifiers. The profile page’s certificate JSON already removes it. These seven-day snapshots do not revoke on later activity, do not independently prove the underlying observations and are not zero-knowledge proofs. Publishing intentionally links the selected certificate to the public profile. Issuance shares the account’s five-per-minute certificate limit.</p>
    <p>GET /api/v1/agents/profiles/:slug returns an A2A-style card with name, description, url, capabilities, provider organization AnyRoute, optional homepage and an anyroute extension containing id, rulebook_summary, certificates and status. This is a discovery card, not an agent invocation endpoint or a complete A2A protocol implementation. Sealed hosting and agent hardware attestation are reported unavailable because no agent-host evidence source is connected.</p>
    <p>GET /api/v1/agents/profiles accepts an exact tag, a cursor and limit (1–50, default 20), returning data and next_cursor. The MCP tool anyroute_agent_directory accepts the same fields and needs no API key. Disabled or expired keys are hidden. Public profile slugs are independent random 144-bit identifiers; republishing after deletion creates a new slug. A random slug does not prevent correlation through owner-written fields or timing.</p>
    <p><a href="/agents/directory/">Publish and search profiles</a>; individual pages use /agents/profile/?id=&lt;slug&gt; and fetch current cards. Unpublishing removes router discovery immediately, but cannot remove copies already retained by public readers or database backups. Profiles do not change who can read inference: ordinary chat requests are read in router memory on every lane; the dedicated encrypted-chat path forwards ciphertext.</p>
  </section>;
}
