export default function AgentAutonomyDocs() {
  return <section id="agent-autonomy"><h3>Progressive autonomy</h3>
    <p>An optional <code>autonomy</code> rulebook field defines up to five ascending rungs. Each rung has integer <code>after_days</code> and <code>clean_requests</code> requirements, both nonnegative, and a strictly increasing <code>caps_multiplier</code> above 1 and at most 10. Requirements cannot decrease between rungs. Both requirements apply since reaching the current rung; the request counter starts again at every climb.</p>
    <pre><code>{JSON.stringify({autonomy:{rungs:[{after_days:1,clean_requests:100,caps_multiplier:2},{after_days:7,clean_requests:1000,caps_multiplier:4}],demote_on:['deny','kill','breaker']}},null,2)}</code></pre>
    <p>The agent starts at rung 0 with caps ×1. The selected <code>demote_on</code> events return it to rung 0 and clear progress. A deny means a recorded policy refusal; kill means a recorded kill event; breaker means a recorded agent breaker event. Saving a rulebook restarts progress. Removing autonomy restores the original caps. Existing rulebooks without the field retain their canonical hash and behaviour.</p>
    <p>Only per-request and rolling hour, day and week spending caps scale, using integer pico-USD arithmetic with fractional pico values rounded down. Output token limits, models, tools, lanes, UTC windows and approval thresholds never scale. A clean request is counted once per applicable rulebook after all policy checks allow it and its spending reservation succeeds; cached inference and allowed MCP tool checks also count. Dry runs, approval-required decisions, refused requests and failed reservations do not earn progress. This counts routing authorization, not successful provider delivery.</p>
    <p><code>GET /api/v1/agents/me</code> and each applicable rulebook in the agent list report <code>autonomy</code> with the current rung, since timestamp, clean request count, multiplier and next requirements with remaining days and requests; <code>effective_caps</code> reports scaled caps. A session and its parent advance independently and both must pass. The /agents page shows a ladder; configure rungs through the rulebook API. Editing other settings in the page preserves autonomy.</p>
    <p>State comes from the metadata event chain, with rung, timestamp and counter checkpoints. Events normally expire after 90 days; active autonomy rulebooks retain their latest checkpoint and following events to preserve progress during inactivity. No prompt text enters these records. <code>AGENT_POLICY_ENABLED</code> defaults to false; it gates autonomy and all rulebook enforcement. These are router rules for requests through AnyRoute, with no on-chain enforcement. AnyRoute’s router reads ordinary request text in memory on every lane today.</p>
  </section>;
}
