export default function AgentCertificateDocs() {
  return <section id="agent-certificates"><h2>Share a signed track record</h2>
    <p>POST /api/v1/agents/me/record-certificate with your agent’s Bearer key and {`{"claims":["requests_at_least:100","active_days_at_least:7"]}`} returns a certificate with a fresh random pseudonym, your requested true claims, issued_at, expires_at, key_id and an Ed25519 signature. Any false or insufficiently supported claim refuses the entire request with HTTP 422 record_claim_unproven. No agent key hash, account id, rulebook hash or underlying activity record is included. Issuance attempts are limited to five per minute per account across its keys.</p>
    <p>Signed by Anyroute’s router, which sees the agent’s activity; not a zero-knowledge proof. This describes records of requests through Anyroute only. It establishes no on-chain enforcement and no activity outside Anyroute. The router reads ordinary chat text in memory on every lane; the encrypted-chat adapter forwards ciphertext. This certificate path stores no prompt text, certificate, pseudonym or claims.</p>
    <p>requests_at_least:N counts retained generation records for the calling key with a completion reason and no cancellation. active_days_at_least:D counts distinct UTC calendar dates with those records, rather than rounding elapsed time into days. Parent, sibling and child request counts are excluded. Missing or deleted records reduce the count. N and D must be positive integers of at most 15 digits; at most 16 distinct claims are accepted.</p>
    <p>no_denials_days:D and no_kills_days:D cover an exact rolling interval of D × 24 hours, up to 90 days. They refer to retained rulebook denials (including denied approvals) and stop events. The key must predate the interval and have a current effective rulebook, including inherited parent rules, unchanged for the whole interval and currently not stopped. Recent edits, resumes or rulebook recreation conservatively refuse these claims. Parent events can include sibling activity and can also prevent issuance. Approval-required decisions alone are not denials. These claims describe the router’s retained rulebook history, not all authentication or provider failures. Autonomy rungs are unavailable here; rung_at_least is not accepted.</p>
    <p>AGENT_POLICY_ENABLED defaults to false and gates issuance and public verification. Issuance also needs TLOG_ENABLED (default false), and waits for the reused receipt signing key’s receipt_key entry to appear in the key log. Certificates expire exactly seven days after issuance and are snapshots: later denials or stops do not revoke them. Signing key rotation keeps earlier public keys available. Key publication alone does not establish a witnessed checkpoint; check the log’s inclusion proof and witness policy separately.</p><p>Switched on at anyroute.tech.</p>
    <p>POST /api/v1/agents/certificates/verify with the certificate as its JSON body returns {`{"data":{"valid":true,"notice":"…"}}`} only when its shape, signature, signing-key issuance window and expiry pass. No authentication is needed. GET accepts URL-encoded certificate JSON in the certificate query parameter; use POST to avoid placing it in URL history or upstream access logs. Malformed certificates return HTTP 400; expired or tampered certificates return valid:false.</p>
    <p>For offline verification, obtain and independently trust or pin the router’s receipt JWKS from /.well-known/anyroute-receipt-keys.json before going offline. Match key_id to kid and to the first 16 hex characters of SHA-256 of the raw public key. For key-log verification, hash that raw key and use /api/v1/tlog/proof?kind=receipt_key&amp;sha256=… with a pinned log verifier and your witness policy. Retain the trusted keys and proof with the certificate.</p>
    <pre><code>{`import { verifyRecordCertificate } from '@anyroute/client';
// trustedKeys is an independently trusted receipt JWKS saved beforehand.
const valid = await verifyRecordCertificate(certificate, { keys: trustedKeys });`}</code></pre>
    <p>The helper verifies Ed25519 over canonical JSON of payload (recursive object keys sorted, no whitespace), requires the fixed certificate type and version, checks issued_at against the key’s valid_from and retired_at, and requires issued_at ≤ current time &lt; expires_at with exactly seven days between them. It makes no network calls. A signature confirms what the router signed; it does not independently establish the underlying activity.</p>
    <p>Each certificate has a new 256-bit pseudonym. There is no stable agent identifier across certificates, but the shared issuer signing-key id, selected claims and issuance timing remain visible and may correlate them. The authenticated router knows which key requested issuance; this is not anonymity from the router.</p>
  </section>;
}
