export default function AgentApprovalDocs() {
  return <section id="agent-approvals"><h2>Your agent asks you first</h2>
    <p>With AGENT_POLICY_ENABLED=true (default false), costs above a rulebook’s approval.above_usd return HTTP 403 agent_approval_required with metadata.approval_id, expires_at and poll. The router creates one pending approval for an identical intent and requesting key; a repeated request reuses it until expiry.</p>
    <p>GET /api/v1/agents/approvals?status=pending lists up to 100 newest approvals visible to a management key or an owner/admin of the same account and team. The Agents page shows “Waiting for you” with Approve and Deny buttons. POST /api/v1/agents/approvals/:id/approve or /deny records that principal’s decision. GET /api/v1/agents/approvals/:id returns only id, status and expires_at to that principal or the requesting key. Session and ordinary agent keys cannot approve themselves.</p>
    <p>After approval, retry with X-Agent-Approval: &lt;id&gt;. Approval is single-use, belongs to the requesting key, and binds the model, lane, declared tools and output token limit. The estimated cost may decrease but cannot exceed max_cost_pico. Council and dual requests bind every model and their combined estimate. Other caps, schedules and the kill switch are evaluated again. An approval is consumed with a successful reservation, even if the provider later fails; a cache hit can also consume it. Approval does not bind prompt contents; prompt text is excluded from the intent.</p>
    <p>AGENT_APPROVAL_TTL_S defaults to 900 seconds, measured from the request, with bounds of 1–86400. Approval does not extend the deadline. Expiry ends validity; approval rows remain until operator deletion. Approval request, decision and use events enter the existing per-key hash chain, whose retention is 90 days when its worker runs. Approval metadata retains readable model and tool identifiers, estimated cost, token limit, principal key hash and timestamps. AnyRoute’s router reads request text in memory on every lane.</p>
    <p>Telegram approval alerts are unavailable: the existing bot connects chat API keys, but this release has no account-to-Telegram alert linkage. Use the Agents page or REST endpoints for principal decisions.</p>
  </section>;
}
