// E153
export default function AgentApproversDocs() {
  return <section id="approvers"><h2>Let teammates approve</h2>
    <p>Choose “Who can approve” on Agents: owners only, owners and admins, or selected teammates from the agent’s team. Owners always retain access. Allowed teammates can approve or deny pending requests in their inbox, on Agents, or with their own linked Telegram. The requester cannot approve requests from their own key or another key issued to the same team member. Approve and allow next time stays with owners and admins because it changes the rulebook.</p>
    <p>GET and PUT /api/v1/agents/:key_hash/approvers require a management key or an owner/admin key in the same account and team, outside agent sessions. PUT accepts mode (owners, owners_and_admins, specific_members) and member_ids, an array of team principal IDs or member key hashes returned by GET. GET returns data.mode, data.member_ids, data.configured and data.members (id, name, role). Members with passkey or wallet sign-ins keep the selection across new sign-in keys. Revoked, disabled and expired members lose access; sessions and API-only agent roles cannot approve.</p>
    <p>AGENT_TEAM_APPROVERS_ENABLED defaults to false and requires AGENT_POLICY_ENABLED. Off returns 404 for settings and preserves existing approval access and responses. When enabled, an unset setting means owners only. The existing approval list and Approve/Deny endpoints accept allowed teammates; list rows include can_allow, false for teammates without rulebook administration. Decisions recheck permissions in the single-use approval transaction and retain decided_by. Activity names the deciding key’s current name; security notices capture its name at decision time when security alerts are enabled.</p>
    <p>The settings use the existing key-value store; no migration is needed. Telegram shows approval and rulebook details in plain words. Telegram delivery also needs TELEGRAM_LINKING_ENABLED and the existing bot. Members receive approval buttons only for allowed agents; Stop and other account notifications keep their existing management guards. Settings and readable member names are retained; no prompt or answer text is added. The router still reads ordinary request text in memory.</p>
  </section>;
}
