// C132
export default function AgentSpendGlanceDocs() {
  return <section id="agent-spend-glance"><h2>Agent spend at a glance</h2>
    <p>See each agent’s charged spending for the last seven UTC days on Agents. Seven small bars show the daily amounts, beside the total, the model with the most charged spending and the last recorded call. Days without charges stay visible. “This week” means today and the six dates before it.</p>
    <p><code>GET /api/v1/agents/spend?days=7</code> uses the same active Bearer management or owner/admin key as the agents list. Management keys see their account; team owner/admin keys see only their team in that account. Sessions and inference-only keys cannot read it. It follows <code>AGENT_POLICY_ENABLED</code>, default false; off returns 404. No new flag or background job is added. Omit <code>days</code> for seven; other values return 400.</p>
    <p>The response has <code>days</code>, <code>from</code>, <code>as_of</code> and a <code>data</code> array. Each key has <code>key_hash</code>, seven oldest-first <code>daily</code> entries with <code>date</code> and numeric <code>charged_usd</code>, numeric <code>total_usd</code>, nullable <code>top_model</code> with <code>id</code>, <code>name</code> and <code>charged_usd</code>, and nullable <code>last_request_at</code>. Responses are not cached.</p>
    <p>Spend comes from posted negative ledger entries of kinds <code>usage</code>, <code>tool_call</code> and <code>data_tool</code>, using settlement time. Refunds do not reduce it; estimates, open holds, deposits and withdrawals are excluded. Model spend uses a generation explicitly linked to the same key and account; charges without that link still count in totals but have no model attribution. The top model is the largest attributed amount, with ties sorted by model identifier. The line says “mostly” only when that model accounts for more than half of all charged spend.</p>
    <p>The last call is the latest retained generation time or charged ledger settlement time, including records older than this week. Free recorded model calls count as calls; paid tools without a generation use settlement time. Calls with neither record cannot appear. Parent keys do not absorb session-key spend. This view adds no retained data and does not read request bodies or prompts.</p>
  </section>;
}
