export default function AgentApprovalDocs() {
  return <section id="agent-approvals"><h2>Your agent asks you first</h2>
    <p>With AGENT_POLICY_ENABLED=true (default false), costs above a rulebook’s approval.above_usd, and model calls once the rolling hour already holds approval.above_calls_per_hour admitted calls (optional), return HTTP 403 agent_approval_required with metadata.approval_id, expires_at and poll. The router creates one pending approval for an identical intent and requesting key; a repeated request reuses it until expiry.</p><p>Switched on at anyroute.tech.</p><p>Approve on /agents, or in Telegram after an owner links it (switched on at anyroute.tech).</p>
    <p>GET /api/v1/agents/approvals?status=pending lists up to 100 newest approvals visible to a management key or an owner/admin of the same account and team. The Agents page shows “Waiting for you” with Approve and Deny buttons. POST /api/v1/agents/approvals/:id/approve or /deny records that principal’s decision. GET /api/v1/agents/approvals/:id returns only id, status and expires_at to that principal or the requesting key. Session and ordinary agent keys cannot approve themselves.</p>
    <p>After approval, retry with X-Agent-Approval: &lt;id&gt;. Approval is single-use, belongs to the requesting key, and binds the model, lane, declared tools and output token limit. The estimated cost may decrease but cannot exceed max_cost_pico. Council and dual requests bind every model and their combined estimate. Other caps, schedules and the kill switch are evaluated again. An approval is consumed with a successful reservation, even if the provider later fails; a cache hit can also consume it. Approval does not bind prompt contents; prompt text is excluded from the intent.</p>
    <p>AGENT_APPROVAL_TTL_S defaults to 900 seconds, measured from the request, with bounds of 1–86400. Approval does not extend the deadline. Expiry ends validity; approval rows remain until operator deletion. Approval request, decision and use events enter the existing per-key hash chain, whose retention is 90 days when its worker runs. Approval metadata retains readable model and tool identifiers, estimated cost, token limit, principal key hash and timestamps. Anyroute’s router reads ordinary chat text in memory on every lane; the encrypted-chat adapter forwards ciphertext.</p>
    <p>TELEGRAM_LINKING_ENABLED defaults to false and requires AGENT_POLICY_ENABLED=true, plus TELEGRAM_BOT_TOKEN on the worker that runs the bot and alert jobs (the API only issues and checks link codes). Telegram linking and approvals are switched on at anyroute.tech. When enabled, Link Telegram on /agents or dashboard settings issues a single-use code valid for five minutes, with five issuance attempts per account per minute. Send /link &lt;code&gt; in a private chat with Anyroute’s bot. No API key is sent to Telegram. Only management keys or account/team owner/admin keys may link; sessions cannot link. There is one Telegram identity per principal key, and one account per Telegram identity. Creating a new code invalidates the account’s previous code. Treat the code as an approval credential.</p>
    <p>GET, POST and DELETE /api/v1/telegram/link read this principal’s status, issue a code and unlink or cancel its pending code. Off returns 404. Unlink also works with /unlink in the bot. Linked principals receive pending intent metadata with Approve/Deny buttons through the existing telegram-bot worker. Callbacks recheck the key, role, team scope, link generation and message, then run the dashboard’s approval decision logic. The message updates after a decision, including decisions made on the dashboard. No inference is executed by clicking a button; the agent must retry its bound request before expiry.</p>
    <p>Telegram sees link codes, account-link commands, approval metadata and alert messages. Anyroute stores the code’s hash, link account and principal key hash, Telegram user id, random link generation, timestamps and approval delivery markers, never Telegram message text or API keys for linking. Codes expire after five minutes; delivery markers expire with the approval and are removed on unlink. Expired metadata is purged on enabled polling or code issuance. The key is rechecked for every delivery and callback. A worker interruption can repeat a notification; decisions remain single-use. Chat keys connected through /key are separate and removed through /forget.</p>
  </section>;
}
