import { Code } from './UI';
import { GUARD_LIMIT, GUARD_STARTERS } from '../lib/agent-guard';
const decide = `curl "$ANYROUTE_URL/api/v1/guard/decide" \
  -H "Authorization: Bearer $AGENT_KEY" -H 'Content-Type: application/json' \
  -d '{"action":"payment.send","amount_usd":"40.00"}'`;
const report = `curl "$ANYROUTE_URL/api/v1/guard/decisions/$DECISION_ID/outcome" \
  -H "Authorization: Bearer $AGENT_KEY" -H 'Content-Type: application/json' \
  -d '{"status":"executed","amount_usd":"40.00"}'`;
export default function AgentGuardDocs() {
  return <section id="agent-guard"><h2>Ask before an action with money</h2>
    <p>Agent Guard is switched on at anyroute.tech. Self-hosted routers enable it with AGENT_GUARD_ENABLED (default false), which requires AGENT_POLICY_ENABLED. While it is off, guard routes return 404 and its MCP tools are hidden. /api/v1/status reports agent_guard.enabled: true when it is on and omits the field when it is off; treat an absent field as unavailable.</p>
    <p>{GUARD_LIMIT}</p>
    <ol><li>Model calls the MCP tool: a seatbelt. Ask anyroute_guard_decide before acting; a model can omit a tool call.</li><li>Code wraps the order function: the model can’t skip the check when every execution path goes through that wrapper. Use integrations/robinhood-agents/guard.ts or guard.py beside the decision-receipt helper.</li><li>Guard controls execution: agent wallets with on-chain rules are the next step and are not part of this update.</li></ol>
    <p>Use the agent’s inference-only key to decide, report an outcome, read its rules and poll its approval. Keep the owner or management key outside the agent. POST /mcp internal calls still pass the same route scope checks; the agent cannot PUT policies, stop, resume or approve itself.</p>
    <Code label="Ask the rulebook (where enabled)">{decide}</Code>
    <p>POST /api/v1/guard/decide returns HTTP 200 with data.decision: allow, deny or approval_required. No rulebook or no actions section denies. Action names are owner-chosen; allow/deny lists match exactly or with a prefix ending in .*; denied entries win. Targets match exactly without case. An allowed target list requires a target. Amounts are decimal USD strings, up to 12 whole and 6 fractional digits; “0” is allowed for cancellations.</p>
    <p>On approval_required, call anyroute_guard_wait with approval_id (timeout_s 1–50, default 25), or poll GET /api/v1/agents/approvals/:id. Approve or deny on /agents or linked Telegram. On approved, call decide again with the same action, target and details_sha256 plus approval_id. The amount may decrease but cannot exceed the approved ceiling. Approval is single-use and expires after AGENT_APPROVAL_TTL_S (default 900 seconds). Limits, UTC windows and stop state are checked again. Never retry a denial unchanged. With on_breach: “kill”, a denied action stops subsequent requests until the owner resumes it on /agents, or sends /resume followed by the agent key hash in a private chat with linked Telegram.</p>
    <p>Action per-request and rolling 24-hour amount limits are separate from model-spend caps. An unreported allow holds the requested amount; an executed outcome replaces it with the reported amount, while skipped or failed releases it. Every allow counts toward max_per_hour even if skipped. Anyroute does not verify execution or the reported amount. Only the deciding key can report, once; repeats return 409. Outcomes above the requested amount are recorded with over_allowed: true; reporting does not retroactively undo an action.</p>
    <Code label="Report what happened (where enabled)">{report}</Code>
    <p>anyroute_guard_report sends the same outcome. Executed requires amount_usd; skipped and failed may omit it. The helpers decide, wait, redeem approval, call your function on allow and report its outcome; a thrown function reports failed. Supply executedAmountUsd(result) in TypeScript or executed_amount_usd(result) in Python to report the actual amount. A report failure after execution must not cause the order function to be retried. Guard does not debit the action amount from your Anyroute model balance.</p>
    <p>Each decision includes data.signed with a payload of type anyroute.guard.decision.v1, alg: Ed25519, key_id and sig. Verify the canonical JSON signature using the published receipt signing keys. The signature is the router’s statement, not independent proof of execution. A session inheriting multiple rulebooks uses a SHA-256 digest of their sorted policy hashes. Action decisions and outcomes join the existing hash chain. Decisions retain readable action names, target labels and reported amounts until operator deletion; full order details are excluded. Optional details_sha256 is the decision-receipt helper’s canonical JSON hash, connecting the order to the model call’s decision tag.</p>
    <p>Suggested names: trade.order, trade.cancel, swap, token.approve, transfer.send, bridge.send, payment.send, invoice.pay, tool.buy, api.call, email.send, deploy.run. Windows are UTC and cover the whole rulebook, including model calls. The trading starter’s 13:30–20:00 covers US market hours during daylight time; from Nov 1 use 14:30–21:00. These starters are configuration examples, not advice or a claim of affiliation with a brokerage; model spending and declared tools remain unrestricted until you add rules.</p>
    {GUARD_STARTERS.map(s => <div key={s.id}><h3>{s.name}</h3><Code label={`${s.id}.json`}>{JSON.stringify(s.policy, null, 2)}</Code></div>)}
  </section>;
}
