export default function AgreementContractDocs() {
  return <>
    <h3>Agreement contracts</h3>
    <p>The agreement contracts are deployed on Robinhood Chain (AgreementEscrow 0xefd8d05f45b8a92aa3b3ef3a7db4c9d3a21f7c96, DisputeOracle 0xcdeddcea1e039e72868bb8af3206af2647afda5a; Sourcify exact match). They hold USDG for individual milestones: the payee submits a delivery digest, the payer releases payment, and the payee may claim after an unanswered review window. After the deadline, the payer may reclaim undelivered milestones. A dispute locks only its milestone.</p>
    <p>A complete signed jury tally can pay the payee, refund the payer or split the milestone. If no verdict reaches the configured majority, a separate panel may decide before dispute expiry. After the immutable dispute timeout, anyone may settle an unresolved dispute with a neutral 50/50 split; the payee receives any rounding remainder. Rulings at or after expiry are refused, even before recovery is called. Only the recorded payer and payee can receive funds. There is no administrator withdrawal, upgrade mechanism or pause.</p>
    <p>The optional jury service runs through Anyroute’s router on the attested lane. The contracts do not verify model execution or hardware attestation. Jury keys and panel decisions remain trusted. Unavailable jury signers or an unavailable panel can delay settlement until expiry. Recovery requires a transaction, and token transfer restrictions can still prevent payouts. The router reads ordinary request text in memory; these contracts add no prompt encryption.</p>
    <p><code>DISPUTE_TIMEOUT_DAYS</code> defaults to 30 in the deployment script, with an allowed range of 7–180 days. The timeout starts when each dispute opens and cannot be extended by the jury or panel. <code>AGENT_AGREEMENTS_ENABLED</code> defaults to false in the configuration loader and deployment script. The service additionally requires configured escrow and oracle addresses. Deployment also requires an explicit operator decision to broadcast. Wallet addresses, amounts, deadlines, digests, jury signatures and rulings are permanently public on chain. Digests can reveal guessable content.</p>
  </>;
}
