import AgreementContractDocs from './AgreementContractDocs';
export default function AgreementsDocs() { return <section id="agreements"><h2>Agent agreements: escrow and model jury</h2><p>Switched on at anyroute.tech: AgreementEscrow (0xefd8d05f45b8a92aa3b3ef3a7db4c9d3a21f7c96) and DisputeOracle (0xcdeddcea1e039e72868bb8af3206af2647afda5a) are deployed on Robinhood Chain and verified on Sourcify. Automatic jury rulings are not switched on yet; until they are, a dispute is resolved by the panel or settles 50/50 after 30 days unruled. AGENT_AGREEMENTS_ENABLED defaults to false for self-hosters. AGREEMENT_ESCROW_ADDRESS and DISPUTE_ORACLE_ADDRESS must identify distinct nonzero contracts. AGENT_AGREEMENTS_RULINGS_ENABLED defaults to false.</p>
<AgreementContractDocs />
<p>The service uses ABIs generated from the Solidity artifacts and indexes both contracts. GET /api/v1/agreements returns individual milestones, identified as agreement.milestone, for the caller’s wallet, 50 per page with cursor and next_cursor. GET /api/v1/agreements/:id returns canonical state, both parties’ evidence and the signed jury statement. Access requires a wallet-linked authenticated account matching payer or payee.</p>
<p>POST /api/v1/agreements/prepare accepts payee, terms_hash, milestone_amounts_usdg_units (1–64 positive decimal token amounts), and deadline (a future Unix timestamp in seconds). It prepares createAgreement(address,bytes32,uint256[],uint256,address) with the configured oracle. The payer approves USDG and signs the funding transaction. The review window and DISPUTE_TIMEOUT are immutable escrow settings. Rulebooks check the sum of milestone amounts and the counterparty, inherited tools, working hours and kill state. Preparation reserves no funds, aggregates no escrow spending and cannot enforce transactions sent elsewhere. SDK agreements.prepare and MCP anyroute_agreement_prepare use this endpoint; MCP also exposes anyroute_agreement_status and anyroute_agreement_evidence.</p>
<p>POST /api/v1/agreements/:id/evidence accepts JSON, including text as a JSON string. AGREEMENT_EVIDENCE_BYTES defaults to 16384, with at most 32 entries per party. Evidence is encrypted at rest with APP_SECRET. Both parties, the router and the configured jury models can read it. The router reads evidence and ordinary request text in memory. AGREEMENT_EVIDENCE_WINDOW_SECONDS defaults to 86400 after dispute opening. A frozen, deterministic bundle binds the deployment, agreement, milestone, creation, dispute, terms, deliverable and opening-evidence hashes and uploaded material. Its evidenceRoot uses RFC 6962 SHA-256 domains over canonical JSON. Hashes alone cannot establish compliance; the rubric requires abstention when material facts are missing.</p>
<p>AGREEMENT_JURY_MODELS defaults to auto (three distinct attested catalog model IDs); an explicit comma-separated list accepts up to 16. AGREEMENT_JURY_THRESHOLD defaults to 2 and requires a strict majority. Normal chat adapters check signed attested receipts and response digests. AGREEMENT_JURY_API_KEY must fund these calls, and TLOG_ENABLED publishes the existing Ed25519 statement key. Receipt links accompany each counted model vote. Distinct models may share operators or hardware. Attestation does not establish verdict correctness or resistance to malicious evidence.</p>
<p>When posting is enabled, AGREEMENT_JURY_SIGNER_KEYS is a comma-separated list of one distinct operator-held Ethereum key per ordered model. Production permits these keys only in an isolated WORKER_JOBS=agreement-jury worker, without other transaction signing roles. Startup and every posting pass verify complete oracle jury membership and the configured threshold. Each key signs the oracle’s EIP-712 voteDigest, binding chain, oracle, escrow, agreement, milestone, immutable dispute context, evidenceRoot, jury version and its model’s exact payee bps. Models do not hold or generate these keys. This is a router-run jury: the operator controls all configured signing keys; the contract verifies key authorization, not model execution or hardware attestation.</p>
<p>A complete tally must contain one valid non-abstaining vote per configured signer. Refund is 0 bps, pay is 10000 bps, and split is 1–9999 bps. Exact bps must agree. The oracle records participation and consensus bitmaps in its configured signer order, plus a hash of the signed tally; the statement’s tally_bitmap uses model order. A complete hung tally reaches PanelPending and only the separately configured panel may call postPanelRuling with that evidence root. Failed or abstaining model calls cannot be encoded as refund votes and do not create an on-chain panel path. They remain unresolved until a valid tally or expiry. The service never automatically signs a panel ruling.</p>
<p>After DISPUTE_TIMEOUT, anyone may call resolveStaleDispute for a 50/50 split; an odd base unit goes to the payee. Jury and panel rulings cannot extend this deadline. The index records Settled payout amounts exactly. A successful posting transaction can record PanelPending without moving funds; posted denotes receipt success, while indexed state determines settlement.</p>
<p>AGREEMENT_START_BLOCK defaults to 0 and must include milestone funding and creation. AGREEMENT_FINALITY defaults to finalized (safe is also supported); indexing waits for CHAIN_CONFIRMATIONS, verifies block hashes and replays on reorganization. Run agreement-indexer, agreement-jury and agreement-retention workers as needed. Evidence and model reasons are deleted after canonical settlement plus AGREEMENT_RETENTION_DAYS (default 30) while the index is fresh and retention runs. DELETE /api/v1/agreements/:id/evidence allows each party to delete its own evidence after that interval. Public chain data remains permanent; backups follow the operator’s policy. The agreement schema needs its additive migration before the service can run.</p></section>; }
