// B118
export default function ApproveAndAllowDocs() {
  return <section id="approve-and-allow"><h2>Allow this next time</h2>
    <p>Next to Approve in Agents and your inbox, choose “Approve and allow next time” for an amount-based request. Review the exact ask-first amount change, then confirm. Only that agent’s ask-first amount rises, rounded up to the cent. Spending caps and other rules still apply. If the agent follows a playbook, open that playbook to change its rules there.</p>
    <p>GET /api/v1/agents/approvals/:id/approve-and-allow previews field, before_usd, after_usd, amount_usd and policy_sha256. POST to the same path with a strict body containing policy_sha256 confirms that preview. Both require the same management or owner/admin key and account/team scope as Approve; inference and session keys are refused. AGENT_POLICY_ENABLED defaults to false; off returns 404. Actions also require AGENT_GUARD_ENABLED (default false). No additional flag or migration is needed.</p>
    <p>The server approves the pending request and saves the rulebook’s new hash and schema version with a policy_set event in the same transaction. The approval keeps its single-use retry binding and original expiry. POST returns data.approval, data.change, data.policy, data.version and data.sha256. HTTP 409 refuses expired or decided approvals, non-amount reasons, changed rulebooks and playbook followers; playbook_linked includes playbook_id and playbook_name. A rulebook changed since the request needs a fresh approval. Telegram retains Approve and Deny; changing the threshold requires the web confirmation.</p>
    <p>This changes the amount at which future requests ask first, including requests with different models or actions still permitted by the rulebook. Model calls use the estimated ceiling; Guard uses the agent’s reported amount. The router records the rulebook and approval changes in its existing tables and hash chain. It still reads ordinary request text in memory.</p>
  </section>;
}
