export default function CommerceStatsDocs() {
  return <section id="commerce-stats"><h2>Commerce ledger: methodology</h2>
    <p><code>GET /api/v1/commerce/stats</code> and the <a href="/commerce/">commerce page</a> count paid settlements between agents, sellers and the router, and show every figure twice: gross, and filtered for self-dealing. They are public and read-only when <code>COMMERCE_STATS_ENABLED</code> is true; it defaults to false and is not switched on at anyroute.tech yet. Disabled deployments return 404. <code>GET /api/v1/status</code> reports the state under <code>data.commerce</code>.</p>
    <h3>What is counted</h3>
    <p>Settlements are read per receipt kind: <code>model.call</code> (x402 payments for model calls, the full authorized USDG amount, payee <code>X402_PAY_TO</code>), and <code>tool.call</code>, <code>facilitator.settle</code> and <code>job.release</code> once those features report their settlements. A kind with nothing feeding it shows zeros and is marked as not connected. Windows are the last 24 hours, 7 days and 30 days. For each window and kind the response gives settlements, distinct payers, distinct payees, volume, median price, refunds and refund rate, for gross and filtered alike. Amounts are decimal strings in USDG base units (6 decimals). The median is the middle amount, or the floor of the mean of the two middle amounts.</p>
    <h3>The filters, in order</h3>
    <p>A settlement counts toward the filtered figures only when it passes all four rules. The first rule it fails is the one it is excluded under, so each excluded settlement is counted once in <code>excluded</code>.</p>
    <ol>
      <li><strong>Anchored.</strong> Every receipt for the settlement is in a Merkle root confirmed on ReceiptAnchor on Robinhood Chain. A payment whose call produced no receipt is excluded, and so is one whose root is pending or kept only locally. A router with no ReceiptAnchor configured excludes everything here.</li>
      <li><strong>Same owner.</strong> Payer and payee are the same wallet, resolve to the same owner key, or are both wallets the operator controls (the x402 payee, the router's signing wallets, treasuries and <code>COMMERCE_OPERATOR_ADDRESSES</code>). The operator paying itself is not commerce.</li>
      <li><strong>Round trip.</strong> Value went back from the payee to the payer within 24 hours either side of the settlement: a settlement in the other direction, or any plain USDG transfer back.</li>
      <li><strong>Funding link.</strong> Payer and payee are linked by USDG funding within <code>COMMERCE_FUNDING_HOPS</code> transfers (default 2): one funded the other, directly or through other wallets, or one wallet funded both. Only transfers of at least <code>COMMERCE_FUNDING_MIN_UNITS</code> count (default 1 USDG), so dust cannot link two wallets. The ledger's own settlements never count as funding: an authorized USDG transfer to the x402 payee, or one relayed by the router or a <code>COMMERCE_RELAYER_ADDRESSES</code> wallet, at any time. Hubs never link anyone: the zero address, USDG, the router's contracts, <code>COMMERCE_HUB_ADDRESSES</code>, and any wallet that funded more than <code>COMMERCE_HUB_FANOUT</code> distinct wallets (default 25), such as an exchange or a bridge.</li>
    </ol>
    <p>The funding rule needs the router's copy of public USDG transfers, which starts at <code>COMMERCE_FUNDING_FROM_BLOCK</code> and is read by the <code>commerce-transfers</code> worker job. Without it, <code>filters.funding.available</code> is false, the page says the rule is not applied, and the other three rules still apply. <code>indexed_block</code> and <code>indexed_at</code> show how far the copy has read.</p>
    <h3>Check it yourself</h3>
    <p>The repository's <code>integrations/dune/commerce.sql</code> recomputes the on-chain part from public chain data alone: USDG <code>Transfer</code> and <code>AuthorizationUsed</code> events on Robinhood Chain (chain id 4663) and ReceiptAnchor <code>Anchored</code> events. Its README lists the assumptions. Dune cannot see receipts, refunds, owner keys or settlements paid from prepaid balances, so it approximates the anchored rule with anchor windows and shows no refund rate.</p>
    <h3>Privacy and limits</h3>
    <p>The response holds counts, sums and medians only: no payer, payee, transaction, receipt or single settlement. It never splits figures by privacy lane, so a settlement on the attested or unlinkable lane is counted like any other and cannot be told apart. Snapshots are cached in router memory for 60 seconds; a failed refresh returns 503 with no stale snapshot. The filters are heuristics: a determined self-dealer can route funding through hubs or more wallets than the hop limit, and an honest payer can be excluded when a shared funder links them to the payee. Gross figures are always shown next to the filtered ones so both can be read.</p>
  </section>;
}
