export default function DefaultRouteDocs() {
  return <section id="default-route"><h2>Default route</h2>
    <p>A key owner can set a default route once, in the key’s rulebook: <code>route_default</code> in PUT /api/v1/agents/:key_hash/policy, or Default route in Spending limits, next to the lanes, on the Agents page or for a key under API keys. It applies only to a request that names no lane. A lane named by <code>provider.lane</code>, <code>provider.disclosure</code>, <code>provider.lane_downgrade</code>, <code>provider.private</code>, a <code>:private</code> model, the X-Anyroute-Lane, X-Anyroute-Disclosure-Max or X-Anyroute-Lane-Downgrade header, the key’s routing settings, a saved route, a preset or a character always wins.</p>
    <ul>
      <li><strong>Standard provider</strong> (<code>standard</code>, the default): served as today, on the public lane.</li>
      <li><strong>Proven hardware only</strong> (<code>proven_only</code>): served exactly as lane <code>attested</code>, only by endpoints with a fresh hardware attestation the router verified. When none can serve it, the request gets the same 503 <code>no_attested_endpoint</code> refusal and nothing is charged.</li>
      <li><strong>Proven hardware first</strong> (<code>proven_first</code>): lane <code>attested</code> when the model has an attested endpoint that would take the request at that moment, otherwise an ordinary public request. The check runs once, before routing. A request served on the public lane is receipted and labelled as the standard route, never as proven hardware; once lane <code>attested</code> is chosen, its rules apply in full, refusal included.</li>
    </ul>
    <p>The rulebook’s <code>lanes</code> allowlist still applies and the stricter rule wins: Proven hardware first never picks <code>attested</code> when the allowlist leaves it out, and Proven hardware only under an allowlist without <code>attested</code> is refused with <code>lane_not_allowed</code>. A session key also follows its parent’s rulebook; where both set a default, the stricter one applies. A response a default applied to carries X-Anyroute-Default-Route, for example <code>proven_first; lane=public</code>; the signed receipt records the lane that served it.</p>
    <p>It covers chat and text completions (with the compatible, character and batch routes that run through them), embeddings, rerank and document questions (POST /api/v1/rag). For a document question, Proven hardware only makes the whole request one that asks for lane <code>attested</code>: the embedding model is picked among attested ones, and the request is refused before anything is sent when none qualifies, so no chunk reaches a standard provider. Proven hardware first is applied to each embeddings and answer call for its own model; the response’s lane stays public unless every call was held to <code>attested</code>, and each receipt shows the lane its call was served on. Encrypted chat is always served on proven hardware. There is no separate switch: the setting is read only while <code>AGENT_POLICY_ENABLED</code> is on, and that defaults to false. On every lane the router still reads ordinary request text in memory; proven hardware describes where the request is answered.</p>
  </section>;
}
