export default function E2eeDocs() {
  return <section id="e2ee-phala" className="docs-section">
    <h2>End-to-end encrypted chat (Phala gateway)</h2>
    <p>The dedicated <code>POST /api/v1/e2ee/chat/completions</code> adapter forwards encrypted message content unchanged to the Phala confidential AI gateway. It is switched on at anyroute.tech. It is off by default in the open-source router until its operator sets <code>E2EE_PASSTHROUGH_ENABLED</code>. Ordinary chat routes on every lane still read request text in router memory.</p>
    <p>Client encryption ends inside Phala’s attested <strong>gateway enclave</strong>. The gateway restores content and forwards it to the serving workload over a separate confidential channel. This is not client encryption directly to a GPU. The router sees the model, roles, message count, content sizes, timing, public keys, nonce, timestamp, response framing, finish reasons, usage and API key or blind-token authorization. A correctly encrypting client keeps message content and its private key out of the router.</p>
    <p>The JavaScript SDK exports <code>e2eeChat(body, options)</code> and <code>client.e2eeChat(body, options)</code>. Supply model, text messages, stream, an optional max_tokens ceiling (default: 512), and a required <code>verifyAttestation</code> callback. Set the options lane to unlinkable when using Tor with blind tokens. The helper fetches <code>GET /api/v1/e2ee/attestation?nonce=…</code> with its own fresh challenge, checks the keyset digest, quote report-data binding, expiry and debug bit, then encrypts each content field using X25519, HKDF-SHA256 and AES-256-GCM with canonical AAD. Your callback must verify the TDX quote signature and Intel collateral, replay and appraise the measured event log, enforce accepted measurements, and assess the deployment and key custody. A router boolean is never evidence.</p>
    <p>Both buffered JSON and SSE are supported. The helper verifies every encrypted field tag, then the gateway’s Ed25519 receipt over the exact response wire bytes and restored request. Decrypted streamed chunks remain provisional until iteration finishes and the complete signed receipt verifies; stopping early does not establish a complete answer. A missing sentinel, wrong key, field mutation, reordering or truncated response fails closed. There is no plaintext fallback.</p>
    <p>Only exact model identifiers offered by <code>phala-confidential-ai</code> are admitted, on the attested lane or the unlinkable lane over Tor with blind tokens. Gateway-verified routing and zero data retention are required. Tools, files, search, structured content, aliases, presets, caching, content policies and unknown fields are refused. Key balances and blind tokens are supported; wallet and pay-with authorization are refused. The router validates ciphertext framing; it cannot determine the plaintext modality or prove that an arbitrary caller actually encrypted a hex string. The router limits envelopes to 1 MiB and responses to 32 MiB. The SDK retains bounded encrypted wire bytes until it can verify the complete receipt.</p>
    <p>Before forwarding, the router places a hold priced from a conservative byte-based input bound plus max_tokens. Ciphertext length is a reservation bound, not observed token usage. Billing trusts the gateway’s reported token counts under the same provider trust model as ordinary chat. On completion or truncation, reported usage settles the charge and releases the unused hold; without reported usage, the hold is charged. Blind-token overages are capped at the hold and unused token value follows the existing forfeiture rules. A provider refusal before a response releases the hold and blind-token claim. A process failure can leave a hold for the existing expiry recovery; expiry recovery cannot reconstruct unseen provider usage.</p>
    <p>The router’s signed receipt marks encrypted content and hashes the exact forwarded ciphertext bytes. It keeps counts or billing bounds, cost, timing, byte counts, completion state, gateway keyset reference and response-verification status, with key linkage or blind nullifiers. It keeps no message ciphertext, plaintext, private key or replay nonce. The router cannot reproduce the gateway’s restored plaintext request hash and records that check as false. The SDK can check that hash. Receipts are public by id; hashes of low-entropy plaintext in gateway receipts may permit guessing.</p>
    <p>Production startup requires <code>PROVIDERS_FILE</code> to declare the live HTTPS TDX provider, its attestation URL and credential reference, plus the matching configured database provider. Forwarding requires fresh verified gateway attestation and pinned TLS. No existing production independence guard is relaxed. Operators must supply the provider credential, acceptable attestation policy and compatible gateway; repository validation does not establish an encrypted exchange with a live account.</p>
    <p>V2 does not pad sizes, hide billing or network metadata, encrypt all clear response metadata, or provide forward secrecy against later compromise of a reused recipient key. Browser-delivered client code must be independently trusted. The gateway’s attested status does not by itself establish GPU attestation. Upstream and GPU claims are gateway assertions, authenticated by its signed receipt and, when cited, a content-addressed session. The client can pin appraised session identifiers.</p>
  </section>;
}
