// v6 F: the hosted x402 facilitator for other sellers. Off unless FACILITATOR_ENABLED.
export default function FacilitatorDocs() {
  return <section aria-labelledby="facilitator"><h2 id="facilitator">x402 facilitator: settle payments for your own API.</h2>
    <p>FACILITATOR_ENABLED defaults to false; GET /api/v1/status reports facilitator.enabled, and every /facilitator address answers 503 facilitator_disabled while it is off. When it is on, any seller can use the router as an x402 facilitator for USDG on Robinhood Chain (eip155:4663), x402 v1 and v2, scheme exact. Settlement calls USDG’s transferWithAuthorization from the payer straight to the seller’s payTo. The router never holds seller funds, and its relay key (FACILITATOR_RELAY_PRIVATE_KEY, which may hold no other signing role) only pays gas. See the <a className="inline-link" href="/facilitator/">facilitator page</a>.</p>
    <ul>
      <li><b>GET /facilitator/supported.</b> kinds (x402Version 1 and 2, scheme exact, network eip155:4663), signers (the relay address) and policy: fee, minimum, gas floats, relay floor, rate limits, the listing’s EIP-712 types, and screening (listings only).</li>
      <li><b>POST /facilitator/verify.</b> Body {'{'}paymentPayload, paymentRequirements{'}'}. Answers {'{'}isValid, invalidReason, payer{'}'} and moves nothing. v1 reads maxAmountRequired, v2 reads amount and checks what the payer accepted; both run the same checks.</li>
      <li><b>POST /facilitator/settle.</b> Same body. Answers {'{'}success, errorReason, transaction, network, payer, receipt{'}'}. (payer, nonce) is claimed before the relay, so a replay gets invalid_exact_evm_payload_authorization_nonce_used and nothing moves twice.</li>
      <li><b>GET /facilitator/discovery/resources.</b> ?type=http&amp;network=eip155:4663&amp;limit&amp;offset&amp;tag, and x402Version=1 for v1 items. Items carry resource, type, x402Version, accepts (from the price hint), lastUpdated and metadata.</li>
      <li><b>POST /facilitator/sellers.</b> An opt-in listing (payTo, resource, priceHint, outputSchema as the exact JSON text signed, tags, listed, issuedAt) signed by the payTo key as EIP-712 SellerListing. issuedAt must be within 10 minutes; a later signature replaces an earlier one. A listed payTo is screened against the OFAC SDN list when SANCTIONS_SCREENING_ENABLED is on.</li>
      <li><b>POST /facilitator/sellers/&#123;id&#125;/gas-float.</b> {'{'}paymentPayload{'}'}: an exact payment to FACILITATOR_TREASURY that tops up the seller’s gas float. GET /facilitator/sellers/&#123;id&#125; shows it.</li>
      <li><b>GET /facilitator/receipts/&#123;id&#125;.</b> The settle’s COSE receipt (kind facilitator.settle: network, asset, transaction, value, payTo, fee; no payer), and its anchor proof once its hour is rooted.</li>
    </ul>
    <p><b>Refusals.</b> Below FACILITATOR_MIN_SETTLE (0.01 USDG by default) a payment is refused with payment_below_facilitator_minimum unless the seller’s gas float covers the estimated gas; each such settle is debited at measured gas times FACILITATOR_GAS_BUFFER_BPS, priced with FACILITATOR_ETH_USDG (unset: no gas floats). When the relay key holds less native gas than FACILITATOR_RELAY_FLOOR_WEI, verify and settle answer 503 with facilitator_unavailable and Retry-After; nothing is queued. Rate limits are the facilitator’s own: per caller address (FACILITATOR_RPM), per payer (FACILITATOR_PAYER_PER_MIN), per payTo (FACILITATOR_SELLER_PER_MIN) and listings per payTo per hour (FACILITATOR_LISTINGS_PER_HOUR); a refusal is 429 with Retry-After.</p>
    <p><b>Fee.</b> FACILITATOR_FEE_BPS defaults to 0 for the launch waiver, and then nothing extra is signed or relayed. Above 0, the seller states paymentRequirements.extra.facilitatorFee {'{'}amount, payTo: the treasury{'}'} and the payer signs a second authorization in paymentPayload.payload.facilitatorFee; it is relayed after the payment.</p>
  </section>;
}
