export default function HostBondsDocs() {
  return <section id="host-bonds"><h2>Host bonds</h2><p>Switched off at anyroute.tech: hosts post no deposit and are weighted by attestation, probation, uptime, errors and latency. This section describes the option for self-hosted routers. HostBond holds USDG work deposits. The router reads canonical bond and slash events on Robinhood Chain and exposes <code>GET /api/v1/network/bonds</code>. When enabled, host records include total and active base units, unbond requests, index freshness and slash history with explorer links. USDG uses six decimals.</p>
    <p>Use <code>keccak256(UTF-8 provider.id)</code> as the contract’s bytes32 host id. Its on-chain operator must equal the provider’s registered wallet. A bond for one host cannot boost another host sharing that wallet. Unbond requests reduce the active amount immediately; a delisted or below-minimum host receives no bond boost.</p>
    <p><code>NETWORK_BONDS_ENABLED=false</code> and <code>NETWORK_SLASHING_ENABLED=false</code> by default. Set <code>HOST_BOND_ADDRESS</code> explicitly; it has no default. <code>HOST_BOND_START_BLOCK</code> defaults to <code>76855987</code>. <code>NETWORK_BOND_FULL_USDG=5000</code> sets the amount for the maximum 1.5× multiplier. Probation remains below the host’s unboosted graduated weight. Price, health, attestation and lane rules continue to apply.</p>
    <p>At anyroute.tech, host bonds and bond indexing are switched off; HostBond on Robinhood Chain (<a href="https://robinhoodchain.blockscout.com/address/0x2921d34fd86d3323a5369a270a82814a74250518"><code>0x2921d34fd86d3323a5369a270a82814a74250518</code></a>) remains deployed but is not used by this router. Slashing and payouts are not switched on at anyroute.tech.</p>
    <p><code>NETWORK_BOND_FINALITY=finalized</code> defaults to the finalized RPC tag; <code>safe</code> is also supported. The indexer also waits for <code>CHAIN_CONFIRMATIONS</code>. It resumes from its stored cursor and rewinds canonical state after a reorganization. A scan older than 120 seconds or incomplete backfill supplies no boost and stops slash work.</p>
    <p>Register <code>host-bond-indexer</code> in the indexing worker’s <code>WORKER_JOBS</code>. Use an isolated <code>host-slasher</code> worker for proposals. With slashing off, that job logs a would-be proposal once per evidence commitment and sends nothing. Live slashing requires <code>SLASHER_PRIVATE_KEY</code>, whose address is checked against <code>HostBond.slasher()</code> at startup and before signing. The public API must never receive this signing key.</p>
    <p>Verified quote-bound rejection against a published host policy produces a MeasurementDrift proposal for the current bond, without delisting. Invalid receipts from the pinned host feed produce review-only evidence because HostBond has no receipt-integrity reason. Evidence bundles store source digests and identifiers, not raw quotes, receipt envelopes or inference text; the commitment alone cannot prove fault. Review requires the source evidence.</p>
    <p>The independent contract owner must approve each exact proposal. The worker executes only after 72 hours, while pending, undisputed and currently approved. It never approves a proposal. Signed transaction intents are saved before broadcast; retries reuse the same signed bytes. An intent that reverts or remains unresolved requires operator review rather than an automatic replacement.</p>
  </section>;
}
