export default function IdempotencyDocs() {
  return <section id="idempotency">
    <h2>Retry without paying twice</h2>
    <p>If a connection drops after a call, send the same request again with the same retry key. Anyroute returns the kept reply and original receipt without another charge. This is an option you choose on each call.</p>
    <p>Send <code>Idempotency-Key</code> with 1–128 visible ASCII characters on <code>POST /api/v1/chat/completions</code>, <code>/api/v1/completions</code>, <code>/api/v1/messages</code>, <code>/api/v1/responses</code>, <code>/api/v1/embeddings</code> or <code>/api/v1/rerank</code>. Their <code>/v1/</code> aliases work too. Use an API key with the endpoint’s usual permissions; Messages also accepts <code>x-api-key</code>. Wallet payments and blind tokens cannot opt in. There is no configuration flag: omitting the header keeps the existing behavior.</p>
    <p>Each retry key belongs to one account and one API key for 24 hours from the first request. Send the same endpoint and JSON body, including the stream setting; object field order and whitespace do not affect the body hash. Matching retries return the original status, JSON body and receipt headers with <code>Idempotent-Replay: true</code>, without a new call, charge or receipt. Reusing a key for a different body or endpoint returns <code>422 idempotency_key_reused</code>. While the first call is running, a retry returns <code>409 idempotency_in_progress</code>. Keep using the same key while retrying; after 24 hours it starts a new billable call.</p>
    <p>Stream replies are not kept. After a stream ends, a retry returns <code>409 idempotency_result_not_kept</code> with <code>X-Receipt-Id</code> and <code>error.metadata.receipt_id</code> when available. No inference or charge runs on that retry. Use the original receipt to check the call. If the router cannot keep a final result, the guard stays in progress until expiry. A retry-store outage returns <code>503 idempotency_unavailable</code> before a new protected call runs.</p>
    <p>Choosing this header lets Anyroute keep the reply, status and selected response headers encrypted with the response cache’s AES-256-GCM encryption for 24 hours. Replies can echo your request. The store keeps a hash of the request, not its body, and a digest of the account, API key hash and retry key. It deletes the entry at expiry. The router reads ordinary requests and replies in memory on every lane and can decrypt these stored replies; encryption at rest does not hide them from Anyroute. Receipts do not record this header, so the privacy label describes retention conditionally. See <a href="/keep/" className="inline-link">What we keep</a>.</p>
    <p>Redis shares protection across router processes. Without Redis, protection uses one process’s memory, ends at restart and does not span processes. A full memory store refuses new protected calls instead of dropping an unexpired guard. A retry still checks the key’s current expiry, disabled state and role.</p>
  </section>;
}
