// E148
export default function KeyIpAllowlistDocs() {
  return <section id="key-ip-allowlist">
    <h2>Allow a key only from certain IP addresses</h2>
    <p>Open a key’s Rename options in Keys &amp; limits and use Only allow these IP addresses. Enter one address or network range per line, then select Save IP addresses. Use my current IP asks the server to return your address once and adds it to the editor; save to apply it. Leave the list empty to remove the restriction. Keep another management key available if your address changes. The router compares the caller’s address in memory; this feature never stores or logs it. The allowlist you choose is retained as key settings.</p>
    <p><code>PATCH /api/v1/keys/:hash</code> accepts <code>allowed_ips</code>: one to 32 IPv4 or IPv6 addresses or CIDR ranges, or <code>null</code> to clear it. Leaving the field out preserves the setting. Key reads include <code>allowed_ips</code>, with <code>null</code> by default. Creation does not accept this field; edit an existing key. Existing management-key or team owner/admin authentication, ownership and session-key guards apply.</p>
    <p><code>GET /api/v1/keys/current-ip</code> requires a bearer key with owner/admin permission and returns <code>data.ip</code> with <code>Cache-Control: no-store</code>. It uses the existing trusted proxy helper: <code>TRUST_PROXY</code> enables forwarded addresses and <code>TRUST_PROXY_HOPS</code> selects the hop from the right (Railway uses two). When the enabled origin lock is valid, the existing Cloudflare address takes precedence. Without a trustworthy address, restricted keys fail closed.</p>
    <p>Requests with a restricted key are refused before routing or charging with <code>403 ip_not_allowed</code> and “This key only works from its allowed IP addresses.” IPv4-mapped IPv6 addresses match equivalent IPv4 rules. Onion and unlinkable requests cannot verify a client address and cannot use a restricted key, even with a lane downgrade. Scheduled and batch inference also cannot use restricted keys because their background calls have no verifiable originating client IP. Existing ingress rate limits retain their current storage rules; this feature adds no caller-address storage. Ordinary request text is still read by the router in memory.</p>
  </section>;
}
