export default function KeyProvisioningDocs() {
  return <>
    <h2 id="key-management">Create capped keys and restrict access.</h2>
    <p>Create and update keys with <code>include_byok_in_limit</code>; responses echo the stored boolean. <code>usage</code> remains the router’s billed USD total. <code>byok_usage</code> is zero: provider-side BYOK expenditure is not measured here, and router charges appear only in usage. The selection does not change billing or budgets. DELETE adds a top-level <code>deleted: true</code> and keeps the data envelope; it disables the key and retains its records.</p>
    <p>List keys with <code>offset</code> and <code>limit</code> (1–1000). An offset without a limit uses pages of 100; no pagination parameters preserves the full list. Disabled keys remain included; past the end the data array is empty. Order is newest first, with key hash breaking ties. Pages reflect current rows rather than a frozen snapshot.</p>
    <p>USD floats keep their existing meaning and can round in JSON. <code>usage_pico_usd</code> and <code>usage_period_pico_usd</code> are exact integer strings (one USD = 10¹² pico-USD). <code>usage_micro_usd</code> is an integer string rounded up from the total to micro-USD (one USD = 10⁶ micro-USD); it is not an exact sub-micro amount. BYOK integer fields are zero. Read usage after disabling a key with its management credential. Disabling does not drain accepted calls; usage is a current counter, not a final settlement certificate.</p>
    <p>Inference-only key provisioning is switched on at anyroute.tech; self-hosted routers enable it with <code>INFERENCE_KEYS_ENABLED</code> (default false). Where enabled, a management key may create a child with <code>scope: "inference"</code>, or PATCH <code>/api/v1/keys/defaults</code> with that scope to make newly minted children default to it. GET that endpoint reads the account default. Existing keys retain access. A management key can explicitly create with <code>scope: "account"</code>, including a successor management key; scope is fixed at creation. Inference-only keys cannot have management rights.</p>
    <p>An inference-only key may call chat/completions, completions, embeddings, responses and messages, list models, read its own generations and receipts, and call the paid GET data tools under /api/v1/data where a router switches them on (DATA_TOOLS_ENABLED, default false). Saved account routes, presets and characters cannot be selected through a model name. Other routes return 403, including key administration, balances, teams, agents and account feeds. Stored restrictions stay active even when provisioning is switched off. Calls remain linked to the operator account and the router reads ordinary request text in memory. Public receipts remain accessible by identifier without a key; the scope limits authenticated access and does not make those receipts confidential.</p>
  </>;
}
