import { Code } from './UI';
// Lane report. Rendered from /docs next to the proof pack section.
export default function LaneReportDocs() {
  return <section id="lane-report"><h2>Lane report</h2><p>A lane report shows where your calls ran over a month or any range of up to 31 days: calls and spend on each lane (public, attested and unlinkable), the share that ran on proven hardware, and, for the attested and unlinkable lanes, each provider and model with a link to that provider&apos;s hardware evidence. Both of those lanes admit only endpoints whose fresh hardware attestation the router verified. The lane counted is the one each call&apos;s signed receipt records.</p>
    <p>It follows the statements feature, which is switched on at anyroute.tech: self-hosters enable <code>STATEMENTS_ENABLED</code> (default <code>false</code>), and with it off the route answers 404. Key access is the statement and Activity rule: management and owner/admin keys read the account; ordinary and session keys read only their own calls, labelled <code>scope: key</code>. Inference-only keys cannot read it. Thirty reports per key per minute; then 429 with <code>Retry-After</code>.</p>
    <Code>{`GET /api/v1/lane-report?from=2026-09-01&to=2026-09-30\nAuthorization: Bearer <your-key>`}</Code>
    <p><code>from</code> and <code>to</code> are UTC calendar dates, both included; a longer range answers 413 and a malformed one 400. The response is <code>{'{ data: { type: "anyroute.lane-report.v1", range, scope, totals, lanes, proven, providers, not_recorded } }'}</code>:</p>
    <ul>
      <li><code>totals</code>: calls and spend in USDG, an exact decimal string.</li>
      <li><code>lanes</code>: one row each for public, attested and unlinkable, with calls, spend, <code>share_of_calls</code> and <code>share_of_spend</code> (four decimal places, rounded half up; null when there is nothing to divide). Calls whose receipt records no lane are a row with <code>lane: null</code>.</li>
      <li><code>proven</code>: the attested and unlinkable lanes together, with the same shares.</li>
      <li><code>providers</code>: one row per lane, provider and model on those two lanes, with <code>evidence_url</code> (the provider&apos;s record on <a href="/verify/">Verify</a>) and <code>attestation_url</code> (<code>GET /api/v1/attestation/:provider</code>). <a href="/status/#proof-time">Proof-time</a> shows how recently each provider&apos;s hardware was verified.</li>
    </ul>
    <p>Calls are counted by call time with the same rows as Activity and the <a href="#proof-pack">proof pack</a>. Spend is the amount charged for each call; statements group charged usage by settlement time, so the two can differ near a month&apos;s edge. The evidence link shows the provider&apos;s current record and its history; each call&apos;s receipt carries the attestation reference it was served under. Calls paid with a blind token name no payer, so they cannot be attributed to an account and are not in a report.</p>
    <p>Two things are not recorded per call and so are not counted: whether a request&apos;s lane came from the key&apos;s <a href="#default-route">default route</a> (the <code>X-Anyroute-Default-Route</code> response header says so at the time), and requests refused because no endpoint on a lane could take them. <code>not_recorded</code> says so in the response.</p>
    <p>Every proof pack carries the same report for the calls in its file, as <code>lane_report</code>, inside the signed manifest. <code>scripts/verify-proof-pack.mjs</code> recomputes it from the calls, checks the totals, lanes, shares and provider rows add up, and checks each call&apos;s lane, provider and model against its signed receipt. See it under <a href="/dashboard/#statements">Statements under Billing</a> as Where your calls ran. Nothing is stored for a report beyond a per-key rate-limit counter; <a href="/keep/">What we keep</a> lists it.</p></section>;
}
