export default function NetworkHostsDocs() {
  return <section id="network-host-signup"><h2>Self-serve host signup</h2>
    <p><code>NETWORK_HOSTS_ENABLED</code> defaults to false; signup and status return 404 while disabled. Enabling it requires <code>NETWORK_POLICY_ENABLED</code> and <code>TLOG_ENABLED</code>. Production also requires Redis, hardware quote verifiers over HTTPS, a persistent log signing key and the existing independent checkpoint checks. Publish a signed host policy before admission.</p><p>Switched on at anyroute.tech.</p>
    <p>Send <code>POST /api/v1/network/hosts</code> with <code>{'{name, endpoint, payout_address, models, contact?}'}</code>. Name is at most 60 characters, models contains one to eight distinct IDs, and optional contact is at most 120 characters. Endpoint is the sidecar root URL over HTTPS, without credentials, query or fragment; the router calls its public <code>/attest</code> endpoint. HTTP submissions are recorded as rejected without contacting the endpoint. Private and reserved network destinations are refused by the existing provider transport in production.</p>
    <p>Use the existing <code>X-Wallet-Auth: address:unixSeconds:signature</code> header. Sign <code>anyroute:unixSeconds:sha256(canonical JSON body)</code> with personal_sign: recursively sort object keys, retain array order, encode UTF-8 without whitespace. Signatures expire after five minutes and are single-use. Signup is limited to three attempts per wallet and ten per network address per minute; onion requests use the existing shared scaled bucket. The temporary address counter lasts 61 seconds in Redis.</p>
    <p>The response contains <code>provider_id</code>, <code>status</code>, plain-English <code>reasons</code> and a <code>dashboard</code> link. A new wallet and endpoint pair returns 201; re-applying to the same pair updates it and returns 200. The wallet becomes the lowercase operator, with USDG payout mode. Fresh hardware evidence must pass the existing attestor, the published policy and sanctions screening when enabled. Development evidence is refused. Success records probation for <code>NETWORK_PROBATION_DAYS</code> (default 7); refusal records rejected. Both operator and payout wallets are screened.</p>
    <p><code>GET /api/v1/network/hosts/{'{provider_id}'}/status</code> returns status, reasons, fresh attestation state, probation end and weight. Weight is the current network selector multiplier, rounded to two decimals: the highest across eligible model offers, not a traffic percentage. It is zero without eligible offers or fresh healthy evidence. With offer terms in the signed policy, the registry creates shadow offers for requested quote-bound models; fresh healthy probation hosts receive a reduced routing multiplier of up to 0.1 through the existing selector. Payouts to network hosts are not switched on yet. A policy refusal can coexist with a successful hardware check; inspect the reasons. The approved recipe, <code>deploy/network/approved/tdx-qwen2.5-0.5b</code>, uses Intel TDX in a supported confidential VM and SHA-256 sidecar bindings v2. These commit the source archive hash, engine image and served model ID alongside existing digests. Admission is automatic after the fresh quote, signed host policy v1 and operator/payout sanctions checks pass. Probation has a public record on <a href="/hosts/">Hosts</a>. Legacy v1 evidence still verifies but lacks the fields this admission policy requires.</p>
    <p>Signup needs no inference API key from the router. The host operator generates its own high-entropy key and configures its SHA-256 through the sidecar’s <code>auth.keys</code> flow. To supply it securely for later inference, send wallet-authenticated <code>PUT /api/v1/network/hosts/{'{provider_id}'}/credential</code> with <code>{'{provider_id, api_key}'}</code> over HTTPS. The signed provider ID must match the path and recovered operator wallet. The router stores it only in the existing AES-GCM encrypted provider-key column, never returns it, and retains it on re-application. Rotate it by repeating this endpoint and updating the sidecar’s hash. Protect the operator’s key and router APP_SECRET.</p>
    <p>Download and inspect <a href="/network/join.mjs">join.mjs</a>; compare its digest on <a href="/network/#join">the registration page</a>. Add <code>--api-key-file /path/to/sidecar.key</code> to signup to supply the credential after a successful response, or use <code>--credential-only PROVIDER_ID --key-file /path/to/operator.key --api-key-file /path/to/sidecar.key</code> later. <code>--api-key-env NAME</code> reads an environment variable instead. The UTF-8 key is trimmed to 16–500 characters; POSIX files must not be group or world readable. <code>--dry-run</code> reads neither key, prints canonical bodies with api_key as &lt;redacted&gt; and uses &lt;provider_id&gt; until signup assigns the ID. A credential failure leaves signup in place; retry with credential-only mode using the same operator wallet.</p>
    <p>The router retains the submitted host settings, optional contact, wallet and payout address, admission reasons and existing attestation records. Status is public by ID; contact and credentials are not returned there. Ordinary chat reads request text in router memory on every lane; the encrypted-chat adapter forwards ciphertext. Admission does not change that. <a href="/keep/">Read the data inventory</a>.</p>
    <p>With <code>NETWORK_HOSTS_ENABLED=true</code>, scheduled attestation renews probation hosts against the current signed host policy without promoting them to live. A failed renewal blocks selection and appears on <a href="/hosts/">Hosts</a>; revoked bindings reject the host and disable its offers. Admission records retention as attested, sourced to the checked host policy version, while jurisdiction, legal hold and training use remain undeclared. Fresh evidence and eligible offers are required for the attested lane. Rejection removes this disclosure profile. The router reads ordinary chat text in memory on every lane; the encrypted-chat adapter forwards ciphertext.</p>
  </section>;
}
