export default function NetworkPolicyDocs() {
  return <section id="network-host-policy">
    <h2>Network host policy</h2>
    <p>When NETWORK_POLICY_ENABLED is on (default false), GET /api/v1/network/policy returns the current policy, and GET /api/v1/network/policy/&#123;version&#125; returns an immutable version. Each response includes the canonical JSON, its SHA-256, an Ed25519 signature over those UTF-8 bytes and the log verifier key. Pin that key independently; a key returned beside a signature does not establish the operator’s identity. The host_policy entry in the transparency log names the version and hash. Check its inclusion under a signed checkpoint and the independent witness or public-log evidence.</p><p>Switched on at anyroute.tech.</p>
    <p>An admin publishes a complete document through POST /trpc/network.publishPolicy with the operator token. Versions start at 1 and advance consecutively; existing versions cannot be replaced. Publication requires TLOG_ENABLED and the production log signing key and independent checkpoint checks already required by the log. Nothing is seeded automatically. Run scripts/network-policy.ts with --base, --provider and --model-id to draft from the router’s current public attestation record, then supply the reviewed source and engine pins and confirm GPU CC requirements before publication.</p>
    <p>The pure check compares verified, quote-bound sidecar image and source hashes, engine images, model IDs and digests, and TEE kind. Development evidence is always refused. GPU models require GPU CC evidence verified separately from CPU attestation. Opt-in SHA-256 sidecar bindings v2 commit the source archive hash, engine image and model ID in addition to image, compose and model digests. Legacy v1 still verifies, but its missing policy-required fields fail admission. The live policy v1 approves <code>deploy/network/approved/tdx-qwen2.5-0.5b</code>: Intel TDX in a supported confidential VM serving Qwen2.5 0.5B. A compose hash is required as an existing binding, but this document does not approve a compose manifest. This policy governs automatic network host admission and renewal; it does not replace other provider admission paths. Digest bindings are software statements inside a verified quote; they do not establish that source produced an image or that running software obeys a data policy. AnyRoute’s router reads ordinary chat text in memory on every lane; the encrypted-chat adapter forwards ciphertext.</p>
    <p>Each models entry may include an optional strict offer object: slug (lowercase catalogue namespace/model), name, optional hugging_face_id, context_length, max_completion_tokens, optional quantization, and pricing with positive decimal strings prompt and completion in USD per token. Names and identifiers are bounded to 160 characters, quantization to 32, prices to 32 characters and at most 1000000 USD per token, and token limits to 2147483647. Omitting offer leaves existing canonical bytes and hashes unchanged. With NETWORK_HOSTS_ENABLED, successful admission copies terms only for models both requested and bound to the verified quote. The registry creates shadow offers during probation; models without offer terms create none. Existing lane and attestation freshness checks still apply: the attested lane also requires an operator-declared attested-retention profile; the public lane can select fresh attested network hosts under its existing rules. Probation starts with routing weight 0.1; failed or stale hardware evidence excludes the host. Rejection clears terms and disables retained offers.</p>
  </section>;
}
