export default function NetworkStatsDocs() {
  return <section id="network-stats"><h2>Network statistics</h2>
    <p><code>GET /api/v1/network/stats</code> is public and read-only when <code>NETWORK_STATS_ENABLED</code> is true (default false). Switched on at anyroute.tech. Token activity currently shows “No data yet”. No API key is required. The <a href="/network/">network page</a> fetches statistics in the browser; its static export renders without the API.</p>
    <p>The response has a <code>data</code> envelope: <code>as_of</code>, <code>cache_seconds</code>, <code>hosts</code> (total, probation, live and rejected), <code>attested_hosts</code>, <code>capacity</code> (distinct model count and IDs), <code>tokens</code>, <code>bonds</code>, <code>interest</code> and <code>policy_version</code>. Host status counts include network hosts only. Other statuses contribute to total but not the three named counts. Attested hosts require admission evidence, fresh successful hardware attestation and a fresh successful latest attempt. Models must have eligible offers and be among that host’s admitted model IDs; model count is not GPU memory or throughput.</p>
    <p><code>tokens.public_lane.days_7</code> and <code>days_30</code> contain decimal-string <code>lower</code> and <code>upper_exclusive</code> bounds in 100,000-token buckets. They count input plus output tokens from retained public-lane generation records on network hosts, excluding cache hits and future records. These coarse ranges are not differential privacy and cannot establish complete historical coverage after records expire. Null means no records in that window.</p>
    <p><code>tokens.private_lanes</code> is null. The existing DP releases at <code>GET /api/v1/stats</code> cover router-wide private-lane traffic, without a host dimension or 7/30-day history; they cannot be assigned to network hosts. Private-lane billing rows are excluded from this endpoint.</p>
    <p>Bonds reuse the bond indexer’s total and active amounts as decimal strings in USDG base units (6 decimals), with freshness and indexed block. Null means indexing is not enabled. Stale index data remains identified as stale and is not shown as a current amount on the site. Interest reuses waitlist counts by role, region and readiness mentions; these are self-reports, not eligibility. Policy version comes from the published host policy, or is null if unavailable or disabled.</p>
    <p>Snapshots are cached in router memory for at most 30 seconds. HTTP freshness uses the remaining snapshot lifetime. A failed refresh returns 503 with no stale snapshot. Disabled deployments return 404. No new database rows, Redis keys, request-body readers or address readers are added. The router still reads ordinary inference request text in memory on every lane; these statistics make no additional prompt-privacy claim.</p>
  </section>;
}
