export default function PriceNoticesDocs() {
  return <section id="price-notices"><h2>Model price change notices</h2>
    <p>See when a model you used in the last 30 days gets cheaper or pricier. Notices show its previous and current input or output rate per million tokens in your account inbox. A linked account management key also receives the notice in Telegram, where Telegram can read the model name and rates.</p>
    <p>This feature is not switched on yet. PRICE_NOTICES_ENABLED defaults to false. When enabled on a worker, an hourly check compares the catalogue’s published rates with the previous snapshot. The first check stays silent. Changes below 1% are ignored; a change from a free rate counts. A model disappearing or losing its available endpoints does not count as a price change. Rates describe the catalogue’s reference offer; your route can cost a different amount.</p>
    <p>GET /api/v1/inbox uses its existing active Bearer key authentication. Only account management keys, excluding session keys, receive these account-wide items. Each has kind price_notice, id, at, title, model, status null, href /models/, and unread. Grouped items have model null. The existing since parameter filters by the notice timestamp. No new endpoint or migration is needed.</p>
    <p>One item covers each model change, including both rates when both change. Each account gets at most five items per UTC day: four individual notices and one “And 3 more model price changes” item that groups the rest. Its count updates after later checks that day. Telegram gets at most five send attempts per linked management key per day; later grouped-count updates appear only in the inbox. Failed or interrupted sends are not retried.</p>
    <p>Notices reuse existing account-attributed call records. Calls without an account record cannot target an account. Latest snapshots stay until overwritten; daily inbox rows are removed after 30 UTC days while the worker is enabled. With the flag off, no job runs and no price notices appear in the inbox. Anyroute still reads ordinary request text in memory; these notices add no prompt or answer storage.</p>
  </section>;
}
