export default function ProjectBudgetsDocs() {
  return <section id="project-budgets"><h2>Project budgets</h2>
    <p>Set a monthly spending limit for a project in the dashboard’s Activity or Insights view. Calls tagged with that project share the limit across the account’s keys. The month follows the UTC calendar. Untagged calls and projects without a budget keep their usual behaviour.</p>
    <p>Use an active account management owner key for <code>GET /api/v1/projects</code> and <code>GET</code>, <code>PUT</code> or <code>DELETE /api/v1/projects/:name/budget</code>. Names follow project tag rules. PUT accepts <code>{'{"budget_usd":50}'}</code>, from zero to one million USD; zero stops calls with positive estimates. DELETE removes the cap, preserving charged history and earlier notices. Each project returns <code>name</code>, <code>month</code>, <code>spent_usd</code>, <code>held_usd</code> and nullable <code>budget_usd</code>; money fields are decimal USD strings.</p>
    <p>The router checks charged spend plus pending holds and the next call’s estimate in the existing ledger reservation transaction before contacting a provider. An over-budget call returns HTTP 402 with <code>project_budget_exceeded</code> and costs nothing. Estimates use the same mechanism as key limits; actual usage can differ. Pending holds count across a month boundary until released or settled; actual charges count in the month of settlement. Earlier tagged calls count from their stored charged cost. Refunds do not restore allowance. Removing a cap does not cancel pending calls.</p>
    <p>At 80% of the cap, one inbox notice is kept per project each month. Saving a cap below existing spend can also create the notice. Editing or removing the cap does not resend it that month. Optional Telegram delivery uses <code>PROJECT_BUDGET_TELEGRAM_ENABLED</code>, default false, plus existing Telegram linking and bot configuration. The worker claims each notice before one delivery attempt to current linked management owners; failed or interrupted sends are not retried. The dashboard inbox works without that flag.</p>
    <p>Anyroute can read project labels and ordinary request text in memory. Labels and billing amounts are retained as account metadata; a budget does not hide prompts or add project labels to signed receipts. Use non-sensitive names. This feature has not been switched on at anyroute.tech yet.</p>
  </section>;
}
