import { Code } from './UI';
// U100: proof packs. Rendered from /docs next to the statements section.
export default function ProofPackDocs() {
  return <section id="proof-pack"><h2>Proof pack</h2><p>A proof pack is one JSON file for a date range that anyone can check with no network. It holds the calls in range with their signed receipts and Merkle paths, the refund receipts issued in range, the signed monthly statements covering those dates, the router&apos;s published receipt keys and a manifest the router signs over exactly which receipts it listed. Receipts carry hashes, token-count buckets and amounts; the pack holds no prompt or answer text.</p>
    <p>It follows the statements feature: self-hosters enable <code>STATEMENTS_ENABLED</code> (default <code>false</code>), and with it off the route answers 404. Key access is the statement and Activity rule: management and owner/admin keys read the account; ordinary and session keys read only their own calls and refunds, labelled <code>scope: key</code>. Inference-only keys cannot read it.</p>
    <Code>{`GET /api/v1/proof-pack?from=2026-09-01&to=2026-09-30\nAuthorization: Bearer <your-key>`}</Code>
    <p><code>from</code> and <code>to</code> are UTC calendar dates, both included, at most 31 days apart; a longer range answers 413 and a malformed one 400. One file holds up to 2,000 calls under at most 200 anchor roots. A larger range sets <code>truncated: true</code> and a <code>next_cursor</code>; pass it back as <code>cursor</code> with the same dates for the next part. Each part verifies on its own. Ten packs per key per minute; then 429 with <code>Retry-After</code>. <code>GET /api/v1/proof-pack/limits</code> answers with these caps and the key&apos;s scope.</p>
    <p>The response is <code>{'{ data: { type: "anyroute.proof-pack.v1", range, scope, calls, lane_report, decision_tags, refunds, statements, keys, manifest, next_cursor, verify } }'}</code>. Each call&apos;s <code>receipt</code> is the object <code>GET /api/v1/receipts/:id</code> serves, so it can also be pasted into <a href="/verify/">Verify</a>. <code>keys</code> is the content of <code>/.well-known/anyroute-receipt-keys.json</code> at download time.</p>
    {/* B122 */}<p>Check it on <a href="/verify/#v-proof-pack">Verify</a> or with the script below. On Verify, the file is read in your browser and never uploaded. A GET request loads Anyroute’s published receipt keys; signatures, paths and totals are checked on your device. The script uses the keys in the file with no network; compare them with the published key list yourself.</p>
    <Code label="Check a pack offline">{`node scripts/verify-proof-pack.mjs anyroute-proof-pack-2026-09-01-to-2026-09-30.json`}</Code>
    <p>The verifier needs Node 18 or later and nothing else. It checks that each key id matches its key bytes; every v1 and v2 receipt, refund receipt, statement and the manifest signature against the keys in the file; each receipt&apos;s anchor leaf; every Merkle path present; each statement&apos;s arithmetic; that the <a href="#lane-report">lane report</a> adds up and matches the calls, with each call&apos;s lane, provider and model matching its signed receipt; that <code>decision_tags</code> names exactly the <a href="#decision-tags">decision tags</a> the signed receipts carry; and that the manifest lists exactly the receipts, statements, keys, lane report and decision tags in the file. It exits 0 only when every check passes.</p>
    <Code label="Find the call behind an order">{`node scripts/verify-proof-pack.mjs anyroute-proof-pack-2026-09-01-to-2026-09-30.json --intent order.json`}</Code>
    <p><code>decision_tags</code> has one row, <code>{'{ id, decision_tag }'}</code>, for each call whose receipt carries a decision tag. The file holds the hashes, never the orders. With <code>--intent</code> (repeatable) the verifier hashes each order file as the decision-receipt helpers do and names the calls whose signed receipt carries that hash; an order no receipt carries fails the run.</p>
    <p>A Merkle path shows a receipt sits under a root. Whether that root was posted on chain, and whether the keys are the router&apos;s, are checked against the ReceiptAnchor contract and the published key list. Receipts from the most recent hour have no path until their hour is rooted. The manifest signature is the router&apos;s statement of what it listed, not an independent audit of its records.</p>
    <p>Download one from <a href="/dashboard/#statements">Statements under Billing</a>. Nothing is stored for a pack beyond a per-key rate-limit counter; <a href="/keep/">What we keep</a> lists it.</p></section>;
}
