export default function ReliabilityDocs() {
  return <section id="reliability-report"><h2>Your reliability report</h2>
    <p>Open Insights in your account to see how your own recorded calls went over the last seven days. Each model shows call counts, success rates, fallback use, available timing and recorded refusal reasons. Refresh the report to include newer calls.</p>
    <p><code>GET /api/v1/account/reliability?days=7</code> requires a Bearer API key, using Activity’s access rules: management and owner/admin keys see account call records; ordinary and session keys see only their own. Agent decisions keep Activity’s team boundary for non-management administrators. Disabled or expired keys are refused. The endpoint is read-only, sends <code>Cache-Control: no-store</code>, needs no new switch and changes no existing responses. <code>days</code> accepts an integer from 1 to 7, default 7, over a rolling UTC range from inclusive to exclusive.</p>
    <p>The response contains <code>scope</code>, <code>days</code>, <code>from</code>, <code>to</code>, <code>totals</code> and <code>models</code>. Each model has <code>model</code> (null when unrecorded), decimal-string <code>calls</code>, <code>succeeded</code>, <code>route_recorded_calls</code>, <code>fallback_calls</code>, and numeric percentages <code>success_rate</code> and <code>fallback_rate</code>, rounded to one decimal. Empty denominators return null. A success is a generation record neither cancelled nor marked with an error or cancelled finish reason, including stored answers. A successful completion does not establish answer quality.</p>
    <p>Fallback use is counted only from existing receipt route records marked as a fallback, including retries or a change of model. Its percentage divides by calls with route records, not all calls; the coverage count is shown. Records made without route explanations have unknown fallback use. Failures before a generation record, general lane refusals and general balance refusals have no account call record here and are excluded. This is a report of recorded calls, not an overall availability guarantee.</p>
    <p>Optional <code>time_to_first_token_ms</code> and <code>total_latency_ms</code> contain decimal-string <code>samples</code>, numeric <code>median</code> and <code>p95</code>. First-token samples use recorded latency only for streams that were not served from stored answers. Total samples use recorded generation time. Null and negative timings are excluded; an entire timing field and its table columns are omitted when there are no samples. Percentiles use linear interpolation over sorted samples, including errors and cancelled calls when timings exist. The table rounds milliseconds for display; the API retains fractional percentiles.</p>
    <p><code>refusals</code> contains decimal-string <code>decisions</code>, <code>lane</code>, <code>budget</code> and <code>rulebook</code> counts from retained denied inference rulebook decisions when agent policies are enabled. Lane counts lane-not-allowed reasons. Budget counts per-request/hour/day/week caps and the spending breaker. Other reasons count as rulebook. Each category counts a decision once; a decision with multiple reasons can appear in several categories. These are decisions, not unique requests: retries, several requested models and inherited policies can add several records. Approval requests and tool/action decisions are excluded. If agent policies are off, these counts are zero.</p>
    <p>No new tables, columns, logs or Redis keys are added. The report reads model and reason codes from existing rulebook records, never messages or request text. Ordinary inference still passes readable request text through the router.</p>
  </section>;
}
