export default function RouteExplanationDocs() {
  return <section id="why-this-route"><h2>Why this route?</h2>
    <p>Route explanations are switched on at anyroute.tech. <code>ROUTE_EXPLAIN_ENABLED</code> defaults to <code>false</code>. When an operator enables it, ordinary chat, text completions and embeddings include a compact JSON <code>x-anyroute-route</code> header once the serving provider is known, and an optional <code>route</code> object in the signed receipt. Streams carry it in the header and the final receipt event. With explanations enabled, stream headers wait for the existing routing attempt to find the first meaningful output; no second selection or provider call is made. The Harness shows “Why this route?” only when that receipt evidence is present.</p>
    <p>The extension has its own <code>v: 1</code>; the enclosing canonical-JSON receipt remains v1 and the COSE receipt remains v2 where issued (embeddings use v1 only). Both signatures cover the entire optional claim. Older receipts omit it. With the flag off, no field or header is added and the existing signed bytes stay unchanged. Verifiers check the extension’s version, fixed vocabulary, counts and serving-provider identity; a valid signature establishes the router’s statement, not an independent replay of selection.</p>
    <p>Fields are <code>provider</code> (the serving provider id), <code>reason</code>, <code>eligible</code> (candidate offers in this model’s final plan, after provider and parameter rules and fallback restrictions, before the attempt limit), <code>skipped</code> (counts grouped by a fixed reason), <code>lane</code>, <code>parameters</code> (required names from a fixed list), and <code>network_host</code>. A fallback adds error-class counts in <code>fallback</code>, including failures on earlier models. It names no failed or skipped provider. Unknown skip or error reasons become <code>other</code>.</p>
    <p>Reasons distinguish price, latency or output-speed order, weighted choice, preferred performance, provider order, your own provider key, a single eligible provider, required parameter support and fallback. Weighted choice uses price, health, quality and hardware checks; eligible network hosts can also receive network weights. It does not always choose the cheapest or healthiest provider. Lane rules and disclosure checks still apply. Parameter names describe routing rules; where the existing selector accepts undeclared support, this summary does not establish support. Dual-verification receipts describe each partition; council receipts describe each member or judge’s provider call. A top-level explanation does not describe the whole panel.</p>
    <p>Cache replies and encrypted-chat receipts have no new selection explanation. Provider ids outside the safe header vocabulary omit the extension. No prompts, answers, other callers’ records, provider URLs, keys, raw error messages or numeric weights are added. The summary is retained in the existing generation receipt fields under their current retention rules. Ordinary request text remains readable by the router in memory; this feature makes no new prompt-privacy claim.</p>
  </section>;
}
