// D144
export default function RulebookHistoryDocs() {
  return <section id="rulebook-history"><h2>Rulebook history</h2>
    <p>Open History on an agent’s rulebook to see when rules were saved, the saving key’s fingerprint and sentences added or removed since the previous version. Restore this version asks you to confirm, then saves those rules again. A key following a playbook shows a note about that playbook instead.</p>
    <p>GET /api/v1/agents/:key_hash/policy/versions returns at most 50 versions, newest first by saved revision. Each has id, key_hash, sha256, spec, saved_at, saved_by, source and diff (added and removed sentence lists). POST /api/v1/agents/:key_hash/policy/restore accepts {`{sha256}`} from that key’s history. Both use the same Bearer owner/admin, management, account and team permissions as PUT policy. Session and inference-only keys cannot manage history. A following key must stop following its playbook before restoring.</p>
    <p>Saving, approving and allowing next time, restoring, and copying playbook rules each retain the rules in the same transaction as the change. Restore appends a normal rulebook-change event to the existing hash chain and keeps Stop state. Removing a current rulebook keeps its history. The first retained version is the current rulebook at the history migration; earlier rules cannot be recovered. Its date and saving key come from the current row’s last update, which may have been a Stop or Resume.</p>
    <p>There is no new flag or background job. AGENT_POLICY_ENABLED defaults to false and gates these routes, like other rulebook routes; agent rulebooks are switched on at anyroute.tech. History keeps full readable rulebooks and saving key hashes until operator deletion. Labels are owner-written text. Differences summarize displayed sentences, rather than every stored field. Rules apply to requests through Anyroute; ordinary request text remains readable by the router in memory.</p>
  </section>;
}
