// B119
export default function RunwayDocs() {
  return <section id="balance-runway"><h2>Balance runway and alerts</h2>
    <p>See how long your balance might last at your last seven days of charged spending. Home and the account strip show the estimate when there is spending to compare. In Money, an owner can choose an amount for a low-balance alert. Alerts are not switched on yet.</p>
    <p><code>GET /api/v1/account/runway</code> requires the same active Bearer key as credits. Account-scoped keys see settled account balance and account spending; session keys see their remaining budget and their own spending. Inference-only keys cannot read it. The response contains numeric <code>balance_usd</code>, <code>spend_7d_usd</code>, <code>per_day_usd</code> (charged spend divided by seven), and <code>days_left</code> (balance divided by that pace, rounded down; null when spend is zero).</p>
    <p>Spend counts posted usage and paid-tool debits during the preceding seven days, by settlement time. Refunds do not reduce charged spend; deposits, withdrawals and token purchases are excluded. Open holds do not reduce the settled balance used here. This is a pace estimate, not a promise of future spending.</p>
    <p><code>GET /api/v1/account/low-balance</code> returns <code>low_balance_usd</code> (nullable) and <code>enabled</code>. <code>PATCH /api/v1/account/low-balance</code> accepts that nullable amount from zero to one million dollars. Both require an owner key; sessions and inference-only keys are excluded. Null clears the setting. Edits answer 403 when <code>LOW_BALANCE_ALERTS_ENABLED</code> is off (default false).</p>
    <p>When enabled, the <code>low-balance-alerts</code> worker checks every five minutes, records one inbox item while settled balance is below the threshold, and attempts a Telegram message through any authorized account link. It re-arms only when a check sees balance strictly above the threshold; equality does neither. Changing the threshold starts a new check. The inbox record and crossing claim are committed before Telegram delivery. Telegram failures are not retried, and an interruption can leave an inbox item without a message. Earlier inbox items stay. The funding link uses the configured <code>SITE_URL</code>.</p>
  </section>;
}
