export default function ScheduledPromptsDocs() {
  return <section id="scheduled-prompts"><h2>Scheduled prompts</h2>
    <p>Save a prompt in Schedules to run every hour, every day at a UTC time, or every Monday at a UTC time. Choose which of your keys pays and set a maximum cost per run; the form starts at $0.05. Each run follows that key’s budget, models, lanes, rulebook and approvals through the ordinary Chat completion path. This feature is not switched on yet.</p>
    <p>Anyroute stores the prompt and the last ten run results encrypted at rest using its router-held secret. Anyroute can decrypt them and reads request text in memory. The account inbox shows the schedule name and first 300 reply characters, with a link to the full saved result. If Telegram is linked, that same excerpt goes to Telegram, where Telegram can read and retain it. Delete a schedule to delete its saved prompt and replies. Deletion does not remove ordinary billing records, database backups or Telegram messages already sent.</p>
    <p>SCHEDULED_PROMPTS_ENABLED defaults to false. When enabled, a worker checks due schedules every minute. UTC times do not shift with daylight saving time. Hourly schedules run on the next UTC hour. A missed interval becomes one run rather than a backlog. Each call asks for at most 1,024 output tokens; its normal worst-case cost must fit the saved ceiling before any funds are reserved or provider contacted.</p>
    <p>GET and POST /api/v1/schedules list and create schedules. GET, PATCH and DELETE /api/v1/schedules/:id read, edit or delete one. POST /api/v1/schedules/:id/run-now runs it immediately, including when paused. GET /api/v1/schedules/:id/runs reads the retained results. All require an active Bearer owner or management key; inference keys, session keys and team administrators are refused. Team owners see only their team’s paying keys. Creation accepts name, prompt, model, key_hash, cadence (hourly, daily or monday), time_utc (HH:MM for daily or Monday), required max_cost_usd, and optional paused. PATCH accepts those fields individually. There are at most 100 schedules per account.</p>
    <p>A refused or failed run is recorded with a bounded reason code and one inbox notice. Three consecutive failures pause automatic runs; Resume clears that count. Ask-first rules refuse the run and create the normal approval request. After approval, run-now can supply X-Agent-Approval; the ordinary single-use intent and cost checks still apply. Automatic runs never approve themselves.</p>
    <p>Database claims prevent competing workers from issuing the same due slot. An interrupted worker’s call is never automatically retried: after fifteen minutes the saved run is marked interrupted because it may already have been billed. Telegram gets one send attempt per run; a failed or interrupted send is not retried. You must wait for an active run to finish before editing or deleting its schedule. Single-call text models are supported; council, streaming and cached replies are refused.</p>
  </section>;
}
