export default function SealedAgentDocs() {
  return <section id="sealed-agents"><h2>Sealed agent hosting</h2>
    <p>Sealed agent registration is not switched on yet. The approved recipe in deploy/agents/sealed runs an owner’s agent image pinned by digest with a credential proxy inside an Intel TDX dstack confidential VM. The proxy derives an application-scoped sealing key from the guest agent using a path containing the measured compose hash, and seals the dedicated AnyRoute API credential with AES-256-GCM. The credential is provisioned through stdin inside the confidential guest, never in the compose manifest. The same measured app can recover it after restarts; manifest changes require fresh provisioning and a fresh dstack app identity. GetKey paths are caller-selected: KMS authorization must restrict release to the approved measurement. Giving replacement code the old application key could let it request the old sealing path.</p>
    <p>With the principal’s Bearer key, POST /api/v1/agents/&#123;key_hash&#125;/sealed with attestation_url (HTTPS /attest without query or credentials), agent_image_digest and compose_hash (both sha256: followed by 64 lowercase hex characters). Approve the exact compose manifest and both container image digests independently. The target must be an active key without management permissions. DELETE the same URL removes the registration.</p>
    <p>The router obtains a fresh nonce-bound TDX quote over pinned TLS. Its report_data commits canonical JSON of type, agent_image_digest, compose_hash, agent_key_hash (SHA-256 of the API credential), sidecar_version and tls_spki_sha256, followed by the 32-byte nonce. All configured quote verifiers must accept it, and a dstack or phala verifier must recover the approved measured compose hash. Debug-enabled TDX, key mismatch, TLS mismatch and stale nonce evidence are refused. Image identity is established by approving the digest-pinned measured manifest, not by trusting a self-reported image label alone.</p>
    <p>AGENT_SEALED_ENABLED defaults to false and requires AGENT_POLICY_ENABLED (default false), plus ATTESTATION_VERIFIERS including a configured dstack or phala verifier. Existing verifier settings apply: DSTACK_VERIFIER_URL or PHALA_VERIFIER_URL and any other selected verifier credentials. The existing attestor worker rechecks at ATTESTATION_INTERVAL_MS (default 600000). A failed check clears the badge; success expires after 30 minutes even without workers. The agent list and GET /api/v1/agents/me include sealed metadata only while the feature is enabled. The badge reads “Sealed · attested · image sha256:…”.</p>
    <p>Trust includes Intel TDX, firmware, the guest OS, dstack KMS authorization, quote-verifier services and code inside the measured VM. Measured does not mean audited: guest administrators and approved code can read or exfiltrate secrets. Rollback, denial of service and all side channels are not prevented. Owners may retain a credential copy; this badge does not establish exclusive possession or prove that every later request came from the VM.</p>
    <p>The agent container does not receive the API credential. The proxy sends it to AnyRoute as HTTPS Bearer authentication and forwards request and response streams, including receipt, lane and policy headers. Ordinary requests sent to AnyRoute are read by the router in memory on every lane. Only the encrypted-chat transport keeps message plaintext off that router when the agent explicitly uses it; sealed hosting alone does not enable encrypted chat.</p>
    <p>The router keeps the registration URL, expected deployment hashes, random revision, fixed result code, verifier names, TLS key hash and check timestamp in its existing key-value store. No quote or API credential is persisted by this registration path. Removing the registration deletes the row; disabled features leave it stored until removal. The guest keeps the encrypted credential file and reads credentials and forwarded bodies in memory. <a href="/keep/">What we keep</a></p>
  </section>;
}
