export default function SignedInBrowsersDocs() {
  return <section id="signed-in-browsers">
    <h2>Signed-in browsers</h2>
    <p>Open Settings to review active wallet sign-ins, see which key this browser uses, and sign out one browser or all the others with one confirmation. Each row is a wallet sign-in key, which may be shared by tabs. Keys connected by hand, team keys and agent sessions are managed separately. Browser labels are approximate; older sign-ins show “Browser details unavailable”. Last used means the last charged call, not browsing.</p>
    <p><code>GET /api/v1/account/browser-sessions</code> requires an active account management Bearer key; inference and agent session keys are refused. It returns only this account’s active, unexpired wallet-issued root management keys as <code>data</code> rows with <code>hash</code>, <code>browser_label</code>, <code>created_at</code>, <code>last_used</code> and <code>current</code>, plus <code>has_more</code>. Pagination uses <code>offset</code> (default 0) and <code>limit</code> (default 100, maximum 1000). Responses use <code>Cache-Control: no-store</code>.</p>
    <p>Signing out another browser uses the existing <code>DELETE /api/v1/keys/:hash</code>; signing out this browser uses <code>PATCH /api/v1/keys/:hash</code> with <code>{'{"disabled":true}'}</code>, then clears the saved browser key. Both retain existing owner/admin and account ownership checks. All others refreshes the list after confirmation and disables each other sign-in key; it keeps the caller’s key and reports partial failures for retry. New sign-ins after that refreshed list are not included. Already-running requests may finish. Disabling preserves account funds and history, and an owner can re-enable the key.</p>
    <p>Wallet sign-in stores only a short browser-family and operating-system label derived from User-Agent in the existing key-value store, never the full header, device model or IP through this feature. Labels remain after disabling until operator deletion. No migration, worker or new configuration flag is needed. <a href="/keep/">Read What we keep</a>.</p>
  </section>;
}
