import { Code } from "./UI";

export default function StructuredOutputDocs() {
  return <section id="structured-output">
    <h2>Check JSON before using it.</h2>
    <p>Switched on at anyroute.tech. Self-hosted routers can enable <code>STRUCTURED_OUTPUT_CHECK_ENABLED</code> (default <code>false</code>). Each chat request must also choose <code>anyroute.json_check</code>. Without both switches, the response and billing stay unchanged. Models must still support <code>response_format</code>; this option does not change routing requirements.</p>
    <Code>{JSON.stringify({ model: "qwen/qwen3-32b", messages: [{ role: "user", content: 'Return a JSON object with a "summary" field.' }], response_format: { type: "json_object" }, anyroute: { json_check: "validate" } }, null, 2)}</Code>
    <p>Choose <code>validate</code> to parse the final message without another provider call. With <code>json_object</code>, it must parse as an object. With <code>json_schema</code>, the router also checks <code>response_format.json_schema.schema</code>. The answer, usage and original signed receipt remain intact; the response adds <code>X-Anyroute-Json-Check: valid</code> or <code>invalid</code> and <code>receipt.structured_output</code> with <code>mode</code>, <code>valid</code> and <code>errors</code> (JSON Pointer <code>path</code> and plain <code>reason</code>; the empty path means the root).</p>
    <p>Choose <code>repair</code> to allow one correction call when the first answer is invalid. The same routed model and provider receive the original conversation, answer, schema and errors, with a request for corrected JSON only. Both calls are charged at their normal rates and pass the same account and agent rules. Repair requires a bearer API key; a blind token or per-call payment cannot authorize two charges. A single-use agent approval is not reused. Non-streaming repair bypasses the response cache. If authorization, credit or the provider prevents the correction, the first output is returned with <code>valid: false</code> and <code>retry_error</code>; its charge still applies. If the core settles a correction before refusing its attestation, that correction’s signed receipt and charge are included too; the refused answer is not returned.</p>
    <p><code>receipt.structured_output.calls</code> lists each served call with <code>attempt</code>, an exact USDG <code>cost</code> string and its complete signed <code>receipt</code>. <code>total_cost</code> is the sum of those charges; <code>retry_attempted</code> says whether a correction was requested, and <code>initial_errors</code> preserves the first failure after a served correction. Top-level usage and receipt identify the returned call only. A second charge is additional to the first, even if the correction is still invalid. There is never a second correction call.</p>
    <p>For streams, the header is <code>pending</code> because it is sent before the answer finishes. The final receipt event carries the completed validation result. A streaming request choosing repair gets <code>pending; repair-unsupported</code> and <code>repair_supported: false</code>: it validates once, without an extra call. Content chunks and their hash-chain comments remain unchanged. An interrupted stream is invalid; a disconnect may prevent delivery of the final receipt.</p>
    <p>The schema subset covers objects, arrays, strings, numbers, integers, booleans and null; properties, required fields, additional properties, items, enum, const, anyOf, nullable and type arrays; string length, number bounds, array length and property-count bounds; and local <code>#/</code> references through <code>$defs</code> or <code>definitions</code>. Unknown assertions, including pattern and format, are refused before a provider call. Schemas are bounded to 4,096 nodes and 64 levels; answer checks to 1 MiB, 100,000 validation steps and 64 levels. Oversized or non-text answers are invalid and cannot be repaired. Only a single chat answer is supported (<code>n: 1</code>); council and dual verification cannot be combined with this option.</p>
    <p>Presets can store <code>anyroute: {"{"} json_check: "validate" {"}"}</code> or <code>repair</code> with their response format. Explicit request settings win. The feature flag still applies.</p>
    <p>Validation checks syntax and this schema subset, not factual accuracy. It cannot guarantee a usable answer; callers must inspect <code>valid</code>. The supplemental validation report is unsigned and absent from receipt lookup. It is not written to generation receipts; existing batch-output retention can keep it with the answer. Each call’s payload, signature and v2 receipt remain independently verifiable. The router reads ordinary request and answer text in memory. This option does not hide prompts from AnyRoute.</p>
  </section>;
}
