// B: trading agents. Copy rule: compatibility only, never a relationship with any brokerage.
export default function TradingAgentDocs() {
  return <section id="trading-agents"><h2>Trading agents</h2>
    <p>Anyroute works with any OpenAI-compatible agent, including agents you run on Robinhood. Set the agent’s base URL to this site’s /api/v1 and give it an inference-only key. Anyroute has no partnership with Robinhood, is not endorsed by Robinhood and does not connect to its systems. It never places orders and never asks for brokerage credentials. The setup guide, the rulebook files and the helpers are in integrations/robinhood-agents in the repository.</p>
    <p>Three starter rulebooks for trading agents are on the Agents page and as JSON files to import with PUT /api/v1/agents/:key_hash/policy: a model allowlist, a daily model budget, and ask-first after a number of calls. approval.above_calls_per_hour asks the principal first once the rolling hour holds that many model calls the rulebook admitted, plus calls already approved; the agent retries with X-Agent-Approval as for any approval. The trading starters leave declared tools unrestricted, because the agent platform names its own tools.</p>
    <p>Decision receipts: send X-Anyroute-Decision-Tag with the SHA-256 of the order intent a call informs, and the router signs it into that call’s receipt; give Agent Guard the same hash as details_sha256 and its decision names that call. <a href="#decision-tags">Decision tags</a> has the hash, examples in curl, TypeScript and Python, and how to check a tag against an order. Decision tags are not switched on at anyroute.tech yet: DECISION_TAGS_ENABLED defaults to false, and the header is ignored while it is off.</p>
    <p>Data tools, charged per call (DATA_TOOLS_PRICE_USD, default $0.001): GET /api/v1/data lists them for free; /api/v1/data/stock/:symbol returns a Stock Token’s USD price from its Chainlink feed on Robinhood Chain; /api/v1/data/stock/:symbol/actions returns its uiMultiplier, any scheduled change and whether it reports paused; /api/v1/data/ipx/:class returns the inference price index. A key pays from its balance and a rulebook sees the call as the tool data_tool. A caller without a key gets an x402 exact offer once per-call payment is configured. A feed older than ESCROW_MAX_PRICE_AGE_S, a paused token, an unknown symbol or an index without fills returns an error before any payment and is not charged. The Stock Token feeds already include the multiplier, so it is never applied twice. DATA_TOOLS_ENABLED defaults to false; GET /api/v1/status shows data_tools and decision_tags.</p>
  </section>;
}
