export default function WeeklySummaryDocs() {
  return <section id="weekly-summary"><h2>Weekly agent summary in Telegram</h2>
    <p>Link Telegram on <a href="/agents/" className="inline-link">Agents</a> and choose “Weekly summary on Mondays” to receive last week’s agent spend, the five agents with the most spend, approvals, Stops and most-used model. Quiet weeks are skipped. Telegram can read the summary, including your agent names.</p>
    <p>This feature is not switched on yet. WEEKLY_SUMMARY_ENABLED defaults to false and requires TELEGRAM_LINKING_ENABLED, AGENT_POLICY_ENABLED and a bot token on the worker. With the switch off, its routes return 404 and no summary job is registered. An hourly job sends on Monday from 09:00 UTC for the previous ISO week, Monday inclusive to the next Monday exclusive. Turn the toggle off or unlink to stop summaries.</p>
    <p>GET /api/v1/telegram/weekly-summary reads opted_in and last_sent_week. PUT on the same path accepts only an opted_in boolean. Both require the same management or owner/admin key as Telegram linking, exclude session keys, return no-store, and require this key’s existing link (409 otherwise). Opt-in starts off for every link.</p>
    <p>One summary goes to the first eligible opted-in link per account. Team administrators see only their current team’s agents. Totals read existing call charges; approvals count requests created that week, with their status at send time (“used” counts as approved). Stops count recorded stop events. Top model means most calls, with ties ordered by model id. Pending or expired approvals remain in the total. No new activity tracking is added.</p>
    <p>The account keeps the last sent ISO week through unlinking and relinking. Ordinary retries and concurrent jobs do not repeat a successful week. A worker interruption or an uncertain network result after Telegram accepts the message can repeat delivery. Failed attempts retry later on Monday; there is no catch-up after Monday. Existing record retention and the link’s current access limit the summary.</p>
  </section>;
}
