// ZK9: bounded browser payment flow; availability follows the build-time switch.
export default function ZkapiDocs() {
  return <section aria-labelledby="zkapi"><h3 id="zkapi">Pay with zkAPI on Sepolia</h3>
    <p>The <a className="inline-link" href="/zkapi/">zkAPI payment page</a> is a Sepolia pilot. Funding remains unavailable until its hosted operator is configured and switched on. It uses the pinned MIT OR Apache-2.0 Rust browser wallet compiled to WASM and an AnyRoute JavaScript wrapper. Proofs run in a browser worker; proving keys come from the operator at runtime and their hashes are checked.</p>
    <p>The page separates a funding-wallet address from lease and inference requests. Calls under the same key remain linked to the operator account. AnyRoute reads ordinary prompts; the provider receives them too. IP addresses remain visible on ordinary HTTPS. Public chain amounts, timing and withdrawal addresses can reveal links. This page does not enable onion routing or encrypted chat.</p>
    <p>Your note secret, balance blinding, signed state, pending deposit transaction and recovery journal are saved unencrypted in browser storage under “Your note wallet.” Exports contain those secrets and a checksum, not encryption. The operator receives public proofs, nullifiers, quote metadata and request IDs, never the note secrets. Runtime inference keys, prompts and answers stay in page memory. Clearing storage or losing a current backup can lose funds; reloading loses the runtime key but keeps the lease journal for retirement.</p>
    <p>The page caps notes at $5-equivalent and leases at $1, with one chat attempt, up to 64 output tokens and a 300-second lifetime. These are browser limits, not vault deposit or aggregate operator admission limits. ETH value changes, gas is additional, and usage uses a quote fixed at lease authorization. Withdraw before the displayed expiry: the treasury can claim an expired active note in full. Mutual close is supported here; escape withdrawal requires separate tooling. The protocol is experimental, unaudited and uses a single-party setup.</p>
  </section>;
}
