import PageFrame from "../../components/PageFrame";
import { Button } from "../../components/UI";
import { checkerDigest } from "../../lib/network-check";
import Waitlist from "./Waitlist";
import Join from "./Join"; import { joinDigest } from "../../lib/network-join";
import s from "./network.module.css";

export const metadata = { title: "AnyRoute Network — Anyroute", description: "Private AI needs private hardware. Yours counts. We’re gauging interest in an open hardware network. Check your machine and join the waitlist." };
const FAQ = [
  ["Do I need to do KYC?", "The planned program has no KYC and no contracts. Your machine would prove itself through hardware attestation. When payouts exist, payout addresses would be screened against the public sanctions list."],
  ["What hardware do I need?", "For GPU models: an NVIDIA H100, H200 or B200-class GPU that supports confidential-computing mode, on an Intel TDX or AMD SEV-SNP host. For small models, a TDX or SEV-SNP CPU server may be enough. The checker gives hints; attestation would establish eligibility."],
  ["How would I get paid?", "Paid per token served, in USDG, claimable on-chain. This is a plan, not a live program. No amounts are promised. The form lets you record a payout preference."],
  ["Can I see the prompts my machine serves?", "The planned design processes prompts inside the enclave, with attestation of the measured code intended to protect that memory from the host operator. This depends on the hardware, measured software and its policy. AnyRoute’s router still reads requests in memory; the enclave runs the model."],
  ["When does it launch?", "There’s no date yet. We’re checking interest first, and your sign-up helps decide when host onboarding opens. Until then, outside hosts can’t join."],
  ["Can I join without leaving contact details?", "Yes. Contact is optional. Keep your entry id and delete code to remove your entry at any time. We delete the list when the program launches or is cancelled."],
];
export default function NetworkPage() {
  const sha = checkerDigest();
  return <PageFrame><main className="page-main" id="content">
    <div className="page-title" data-reveal><span className="eyebrow">ANYROUTE NETWORK · WE’RE GAUGING INTEREST</span><h1>Private AI needs<br />private hardware.<br /><em>Yours counts.</em></h1><p>The AnyRoute Network is coming: confidential hardware, owned by anyone, serving private AI and paid per token served. Hosting isn’t open yet. Join the waitlist and check your hardware now.</p><div className="button-row"><Button href="#waitlist">Join the waitlist</Button><Button href="#readiness" secondary>Check your hardware</Button></div></div>
    <div className="side-layout"><nav className="side-nav" aria-label="Sections"><span className="side-nav-label">On this page</span>{[["how", "How it will work"], ["today", "What’s true today"], ["who", "Who it’s for"], ["readiness", "Readiness checker"], ["waitlist", "Join the waitlist"], ["faq", "FAQ"]].map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav>
    <article className={`page-body prose ${s.body}`}>
      <section id="how"><span className="eyebrow">THE PLAN</span><h2>Your hardware proves what it runs.</h2><p>No KYC. No contracts. The machine would prove itself. This describes the proposed program; hosting and payouts are not available.</p><ol className="case-steps">{[["Join with one command", "When onboarding opens, an installer would connect your machine."], ["Prove the hardware", "Attestation would check the enclave and the measured software before traffic is accepted."], ["Serve private traffic", "The enclave would run the model. AnyRoute’s router still reads requests in memory."], ["Paid per token served", "The plan is USDG payouts for tokens served, claimable on-chain."]].map(([title, text], i) => <li className="case-step is-in" key={title}><span className="step-n">STEP {i + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
      <section id="today"><span className="eyebrow">CURRENT SERVING</span><h2>There’s already a foundation.</h2><p>AnyRoute’s attested lane already serves 23 open models inside hardware enclaves, with a signed receipt for each call. <a href="/seal/">See the serving protocol and current status</a>.</p><p>Public host measurements and Sigstore records let you inspect what is measured. Receipt roots and anchors make served work checkable where anchoring is switched on. <a href="/verify/">Verify a provider and its evidence</a>.</p><p>A one-command installer exists in the open-source repository. It does not admit outside hosts to a network today. Tor onion access with blind tokens separates token issuance from spending; those protections depend on the transport and lane you use. <a href="/seal/">Read the conditions and limits</a>.</p><p>AnyRoute’s router still reads requests in memory; the enclave runs the model. Receipts store hashes, token counts and cost, not prompt text. <a href="/keep/">See the full inventory of what we keep</a>.</p></section>
      <section id="who"><h2>Bring the hardware. Or the demand.</h2><ul><li><strong>Confidential GPU owners and fleet operators:</strong> NVIDIA H100, H200 or B200-class servers with GPU confidential-computing support on Intel TDX or AMD SEV-SNP hosts.</li><li><strong>Confidential cloud users:</strong> rented TDX or SEV-SNP machines with spare capacity. Renting solely to host may not cover your costs.</li><li><strong>Small-server owners:</strong> TDX or SEV-SNP CPU servers for small models.</li><li><strong>Relay operators and witnesses:</strong> record your interest in supporting the proposed network.</li><li><strong>Developers and agents:</strong> tell us you need more private inference capacity.</li></ul></section>
      <section id="readiness"><span className="eyebrow">READ-ONLY · NO NETWORK CALLS</span><h2>What can your machine do?</h2><p>Download the checker, compare its SHA-256 with the value below, inspect it, then run it. It checks guest devices, host support hints and NVIDIA confidential-computing queries. It changes nothing and sends nothing. Kernel log permissions can limit the answer; sudo may reveal more, but the checker never asks for root.</p><pre className={s.code}><code>curl -fsSLO https://anyroute.tech/network/check.sh &amp;&amp; sha256sum check.sh &amp;&amp; sh check.sh</code></pre><p className={s.small}>The command prints the digest before running. Compare the downloaded file before running it; you can perform the three steps separately.</p><dl className={s.digest}><dt>check.sh SHA-256</dt><dd><code data-network-check-sha256={sha}>{sha}</code></dd></dl><p><a href="/network/check.sh">Read or download check.sh</a></p><p><strong>This is a hint.</strong> Real eligibility is proven by attestation when hosting opens. A capability mention or an enabled GPU mode is not proof of an eligible machine. Paste the summary into the form only if you choose.</p></section>
      <section id="waitlist"><span className="eyebrow">WAITLIST</span><h2>Tell us what you’d bring.</h2><p>No names required. Contact details are optional. This form works on this site’s onion address using the same relative API path, with no third-party requests.</p><Waitlist /></section>
      <Join sha={joinDigest()} />
      <section id="faq"><h2>A few straight answers.</h2>{FAQ.map(([q, a]) => <details className={s.faq} key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    </article></div></main></PageFrame>;
}
