import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { profilePayload, directoryPath, profileLink, safeHomepage } from '../lib/agent-profiles.js';
test('explicit publication selection stays empty unless selected, and homepage schemes are safe', () => {
  const payload = profilePayload({ name: ' Agent ', description: ' Search ', homepage: '', tags: 'search, tools, search', show: [], claims: '' });
  assert.deepEqual(payload, { name: 'Agent', description: 'Search', capabilities: ['search', 'tools'], show: [], certificate_claims: [] });
  assert.equal(safeHomepage('javascript:alert(1)'), null);
  assert.equal(safeHomepage('https://name:secret@example.com'), null);
  assert.equal(safeHomepage('https://example.com/agent'), 'https://example.com/agent');
});
test('directory tag/cursor and profile query values are encoded', () => {
  assert.equal(directoryPath('a&b', 'abc'), '/api/v1/agents/profiles?tag=a%26b&cursor=abc');
  assert.equal(profileLink({ anyroute: { id: 'a?b' } }), '/agents/profile/?id=a%3Fb');
});
test('OpenAPI describes opt-in fields, owner authentication and public discovery', () => {
  const spec = JSON.parse(readFileSync(new URL('../public/openapi.json', import.meta.url), 'utf8'));
  const owned = spec.paths['/api/v1/agents/{key_hash}/profile'];
  for (const method of ['get', 'put', 'delete']) assert.deepEqual(owned[method].security, [{ BearerAuth: [] }]);
  const schema = owned.put.requestBody.content['application/json'].schema;
  assert.equal(schema.additionalProperties, false);
  assert.deepEqual(schema.properties.show.items.enum, ['spending_caps', 'ask_first', 'kill_switch']);
  assert.ok(!schema.properties.certificates);
  const card = spec.paths['/api/v1/agents/profiles/{slug}'].get;
  assert.deepEqual(card.security, []); assert.match(card.description, /defaults false/);
  assert.equal(card.responses['200'].content['application/json'].schema.properties.anyroute.properties.status.properties.attested.const, 'unavailable');
  assert.deepEqual(spec.paths['/api/v1/agents/profiles'].get.parameters.map(p => p.name), ['tag', 'cursor', 'limit']);
});
test('identity: endpoint in the payload, plain live and paid-reputation lines, and documented routes', async () => {
  const { livenessLine, reputationLine, bpsPercent } = await import('../lib/agent-profiles.js');
  const payload = profilePayload({ name: 'A', description: '', homepage: '', endpoint: ' https://agent.example/a2a ', tags: '', show: [], claims: '' });
  assert.equal(payload.endpoint, 'https://agent.example/a2a');
  assert.equal(livenessLine(undefined), null);
  assert.deepEqual(livenessLine({ endpoint_declared: false, live: null }), { state: 'none', text: 'Live check: no endpoint declared' });
  assert.equal(livenessLine({ endpoint_declared: true, live: null }).state, 'pending');
  assert.deepEqual(livenessLine({ endpoint_declared: true, live: true, probed_at: '2026-10-02T03:00:00.000Z' }), { state: 'live', text: 'Live: answered on 2026-10-02' });
  assert.equal(livenessLine({ endpoint_declared: true, live: false, probed_at: '2026-10-02T03:00:00.000Z' }).state, 'down');
  assert.equal(reputationLine(undefined), null);
  assert.match(reputationLine({ opted_in: false }).text, /not opted in/);
  assert.match(reputationLine({ opted_in: true, feedback_count: 0, score: null }).text, /no paid feedback yet/);
  assert.equal(reputationLine({ opted_in: true, feedback_count: 2, score: 66.7 }).text, 'Paid reputation: 66.7 of 100 from 2 paid reviews');
  assert.equal(bpsPercent(3333), '33.33%');
  assert.equal(bpsPercent(0), '0%');
  const spec = JSON.parse(readFileSync(new URL('../public/openapi.json', import.meta.url), 'utf8'));
  const feedback = spec.paths['/api/v1/agents/{slug}/feedback'].post;
  assert.deepEqual(feedback.security, [{ BearerAuth: [] }]);
  assert.deepEqual(feedback.requestBody.content['application/json'].schema.required, ['receipt_id', 'score']);
  assert.equal(feedback.requestBody.content['application/json'].schema.additionalProperties, false);
  assert.match(feedback.description, /No receipt, no feedback/);
  assert.deepEqual(spec.paths['/api/v1/agents/{slug}/reputation'].get.security, []);
  assert.match(spec.paths['/api/v1/agents/{key_hash}/identity/register'].post.description, /defaults false/);
  assert.ok(spec.paths['/api/v1/agents/track-records/{id}/proof'].get);
  assert.ok(spec.paths['/api/v1/agents/profiles/{slug}'].get.responses['200'].content['application/json'].schema.properties.anyroute.properties.liveness);
  const card = readFileSync(new URL('../app/agents/profile/ProfileCard.jsx', import.meta.url), 'utf8');
  assert.match(card, /livenessLine\(card\.anyroute\.liveness\)/);
  assert.match(card, /reputationLine\(card\.anyroute\.reputation\)/);
});
