export default function SanctionsSection() {
  return <>
    <h2 id="network-sanctions">Network sanctions screening</h2>
    <p>Optional screening checks provider payout addresses against digital currency addresses published in the <a href="https://ofac.treasury.gov/sanctions-list-service">OFAC SDN list</a>. A listed address is refused on provider application and skipped during weekly USDG payouts. This is address screening, not identity verification: it collects no KYC or identity data and cannot identify unlisted wallets controlled by a listed person.</p>
    <p><code>SANCTIONS_SCREENING_ENABLED</code> defaults to false. <code>SANCTIONS_LIST_URL</code> selects the official classic SDN XML download and must be explicitly set to an HTTPS URL when screening is enabled in production. <code>SANCTIONS_MAX_AGE_DAYS</code> defaults to 7. An operator schedules <code>sanctions-refresh</code> through the worker job allow-list; registration runs daily and once at worker startup. No production worker configuration is changed by this feature.</p>
    <p>The feed is validated before atomically replacing the stored addresses and metadata. Failed downloads preserve the last good list. Screening uses 0x-prefixed 20-byte digital currency addresses across EVM chains and token tickers; other address formats are counted and ignored. Names and other identity fields from the XML are not stored. The source hash is SHA-256 of the downloaded bytes, not an independent signature check.</p>
    <p>When the publication date is older than the configured maximum, or the list is missing, new admissions and payouts to addresses without a recorded successful payout pause. Previously paid addresses may continue receiving payouts, but any match in the retained list is always blocked. Skipped settlements remain due for a later run. The logs record skip reasons and the freshness exception. If the database is unavailable, screening pauses both admission and payouts.</p>
    <p>Public <code>GET /api/v1/network/sanctions</code> returns the publication date, entry count, source hash, ignored count, refresh time, age and stale status. Screening does not change prompt handling: AnyRoute&apos;s router reads request text in memory on every lane.</p>
  </>;
}
