'use client';
import { useEffect, useState } from 'react';
import { Button } from '../../components/UI';
export default function Agreements({ request }) {
  const [rows, setRows] = useState([]), [detail, setDetail] = useState(null), [error, setError] = useState(''), [off, setOff] = useState(false), [busy, setBusy] = useState(false), [content, setContent] = useState(''), [version, setVersion] = useState(0);
  useEffect(() => { const ac = new AbortController(); setDetail(null); setRows([]); setError(''); setOff(false); request('/api/v1/agreements', { signal: ac.signal }).then(r => { if (!ac.signal.aborted) setRows(r.data || []); }).catch(e => { if (!ac.signal.aborted) { setOff(e.status === 404); setError(e.status === 404 ? 'Agreements are not switched on yet for this router.' : e.message); } }); return () => ac.abort(); }, [request, version]);
  const read = async id => { setBusy(true); setError(''); setDetail(null); setContent(''); try { const r = await request(`/api/v1/agreements/${id}`); setDetail(r.data); } catch(e) { setError(e.message); } finally { setBusy(false); } };
  const upload = async e => { e.preventDefault(); setBusy(true); setError(''); try { let value = content; try { value = JSON.parse(content); } catch {} await request(`/api/v1/agreements/${detail.id}/evidence`, { method: 'POST', body: value }); const r = await request(`/api/v1/agreements/${detail.id}`); setDetail(r.data); setContent(''); } catch(e) { setError(e.message); } finally { setBusy(false); } };
  return <section className="control-panel"><h2>Agreements</h2><p className="help-text">Wallet-linked parties can read their USDG escrow agreements. Contracts are not deployed at anyroute.tech yet. The payer signs its own transaction; AnyRoute does not hold the escrow funds. <a href="/docs/#agreements">Read the trust model</a>.</p><Button secondary disabled={busy} onClick={() => setVersion(v => v + 1)}>Refresh agreements</Button>
    {error && <p role={off ? 'status' : 'alert'}>{error}</p>}{!off && !rows.length && <p>No agreements returned for this wallet.</p>}
    <ul>{rows.map(a => <li key={a.id}><button type="button" disabled={busy} onClick={() => read(a.id)}>Milestone {a.id} · {a.state} · {a.amount} USDG base units</button></li>)}</ul>
    {detail && <><h3>Milestone {detail.id}</h3><p>Dispute state: {detail.state}</p><p>Payer: <code>{detail.payer}</code><br/>Payee: <code>{detail.payee}</code></p><p>Terms hash: <code>{detail.termsHash}</code></p><p>Deliverable hashes: {(detail.deliverables || []).join(', ') || 'None recorded'}</p>
      <h3>Party evidence</h3><p className="help-text">Both parties and the router can read uploaded evidence. Stored encrypted at rest; jury calls send decrypted evidence to attested models. Upload during the evidence window. Resolution plus the configured retention interval permits deletion; copies in backups follow the operator’s policy.</p>
      <ul>{(detail.evidence || []).map((e, i) => <li key={`${e.sha256}-${i}`}><code>{e.party} · {e.sha256}</code><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{typeof e.content === 'string' ? e.content : JSON.stringify(e.content, null, 2)}</pre></li>)}</ul>
      {!['resolved','released'].includes(detail.state) && <form onSubmit={upload}><label htmlFor="agreement-evidence">Evidence text or JSON</label><textarea id="agreement-evidence" value={content} maxLength={65536} onChange={e => setContent(e.target.value)} required/><Button type="submit" disabled={busy || !content.trim()}>Upload evidence</Button></form>}
      <h3>Router-run jury</h3>{detail.jury ? <><p>Status: {detail.jury.status} · {detail.jury.statement.verdict ? `${detail.jury.statement.verdict.verdict}: ${detail.jury.statement.verdict.payee_bps} bps to payee` : 'Unresolved jury; no automatic ruling'}</p><p>Evidence root: <code>{detail.jury.evidence_root}</code></p><p className="help-text">Dry run stores a would-be ruling without posting. The router runs the jury and signs the statement. Attestation establishes hardware claims, not whether a verdict is correct.</p><ul>{detail.jury.statement.votes.map(v => <li key={v.model}>{v.model}: {v.verdict ? `${v.verdict.verdict} · ${v.verdict.payee_bps} bps · ${v.verdict.reason}` : v.failure || 'No verdict'} {v.receipt_id && (v.internal_receipt ? <span>Operational receipt <code>{v.receipt_id}</code> · attestation and signature in the statement below</span> : <a href={v.receipt_url || `/verify/?id=${encodeURIComponent(v.receipt_id)}`}>Receipt {v.receipt_id}</a>)}</li>)}</ul><p>Statement key: <code>{detail.jury.key_id}</code></p><details><summary>Signed jury statement</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(detail.jury, null, 2)}</pre></details></> : <p>No jury statement recorded. A dispute waits for the evidence window and a configured jury worker.</p>}</>}
  </section>;
}
