import type { TableDoc } from "../types.ts";
const json = (purpose: string) => ({ purpose, review: { covers: ["type:json"], verdict: "no-request-content" as const, why: "Only decoded public agreement event values and canonical block metadata are stored: wallets, USDG amounts, hashes, identifiers, bps and timestamps. No inference or evidence content is accepted into the chain journal or projection." } });
const common = { category: "chain" as const, request: "no" as const, retention: "Public chain journal and projections remain until the operator removes the agreement index. Orphaned events and projections are removed and replayed on reorganization." };
const scope = "Chain id, configured escrow and oracle addresses; isolates deployments.";
const agreement = "Composite decimal agreement.milestone identifier from the configured escrow contract.";
const dispute = "Canonical dispute transaction hash and log index, or before-dispute plus the creation transaction/log identity for earlier evidence; prevents reuse of a reorged id from exposing old content.";
const created = "Time this record was first saved by the router.";
const retention = "Evidence and signed jury statements are deleted after canonical resolution plus AGREEMENT_RETENTION_DAYS (30 by default), while agreement-retention runs with a fresh index. Parties may delete their own evidence after that interval. Backups follow the operator backup policy; deletion is not erasure from backups or chain.";
export const agreementTables: Record<string, TableDoc> = {
  agreement_cursor: { ...common, purpose: "Finality-aware resumable agreement event cursor and cross-worker serialization lock.", columns: { scope, block: "Last canonical scanned block number.", block_hash: "Hash at the canonical scan endpoint.", checkpoints: json("Up to 128 scan endpoint block/hash pairs used to find a canonical reorg rewind point."), checked_at: "Caught-up scan time, zero during backfill. Jury, posting and deletion require freshness within 120 seconds." } },
  agreement_events: { ...common, purpose: "Reversible public AgreementEscrow event journal, bounded by confirmation and finality checks.", columns: { scope, tx_hash: "Public transaction hash, unique with deployment scope and log position.", log_index: "Canonical log position in a block.", block: "Canonical event block number.", block_hash: "Event block hash checked against the RPC.", event: "AgreementEscrow milestone lifecycle events and DisputeOracle TallyRecorded, PanelRequired and RulingPosted ABI event names.", args: json("Public event arguments: agreement id, payer/payee wallets, USDG base-unit amount, terms/deliverable/evidence hashes, milestone index, deadline, oracle address, review deadline, payout amounts, ruling path and verdict encoding, evidence root, jury version, participation and consensus bitmaps and tally hash. indexedEscrow and indexedOracle identify configured contracts. indexedAt is the canonical block timestamp.") } },
  agreement_projection: { ...common, purpose: "Canonical agreement state rebuilt from the journal; both parties' wallet-linked accounts have API access.", columns: { scope, kind: "Fixed agreement projection kind; each row is an individual milestone.", id: agreement, data: json("Agreement id and creation transaction/log identity, public payer/payee wallets, amount, terms hash, ordered deliverable hashes, agreement deadline, milestone index, oracle address, review deadline and exact payout amounts, dispute identity/evidence hash/time, resolution time and public on-chain ruling. No uploaded evidence or model reasons.") } },
  agreement_evidence: { ...common, request: "yes", retention, purpose: "Party-uploaded text or JSON evidence, encrypted with APP_SECRET and hash-committed. Only the parties have REST access; the router and jury providers read the decrypted bundle.", columns: { scope, agreement_id: agreement, dispute, party: "Authenticated account wallet matched to the indexed payer or payee, never a caller IP.", sha256: "SHA-256 of canonical JSON content before encryption; public to both parties.", content: { purpose: "AES-GCM encrypted canonical JSON evidence; may contain arbitrary text including prompts, deliverables and personal information. The router decrypts it for party detail and jury calls. Default cap 16 KiB per item and 32 entries per party. Evidence is not end-to-end encrypted through the router.", review: { covers: ["name:content"], verdict: "holds-request-text", why: "The feature explicitly persists party-uploaded evidence content. Encryption at rest does not prevent the router or an operator with APP_SECRET from reading it. Only wallet-linked parties can retrieve it through these routes, and configured attested models receive it for adjudication." } }, created_at: created } },
  agreement_jury: { ...common, request: "aggregate", retention, purpose: "Router-signed model jury statement and durable ruling intent for the canonical dispute. Complete hung tallies may enter the panel path; failed or abstaining votes remain unresolved until a valid tally or expiry. Default consensus status is dry_run.", columns: { scope, agreement_id: agreement, dispute, root: "RFC 6962 SHA-256 Merkle root of canonical header and ordered party-evidence leaves.", status: "dry_run, panel, submitted, posting_failed or posted. A dry_run does not send a transaction. Posted denotes a successful transaction receipt, with escrow state reconciled separately by the index.", statement: { purpose: "Signed jury scope, dispute, root, leaf digests, fixed rubric digest, model list, majority threshold, per-model verdict/reason or fixed failure code, normal receipt id/link/policy hash, consensus bps, agreeing-model bitmap (separate from on-chain signer-order bitmaps), issuance time and trust notice. Model reasons may quote evidence text.", review: { covers: ["type:json"], verdict: "holds-request-text", why: "Structured model verdict reasons are answer text and can repeat uploaded evidence. This statement therefore stores answer content openly in the inventory, behind party-only API access and resolution-based retention. The public key log contains public signing material. Chain calldata contains evidence root and per-key basis-point votes with EIP-712 signatures; the oracle records signer-order bitmaps and tally hash. The worker holds one operator-configured private key per model; models do not hold these keys." } }, key_id: "Existing router Ed25519 receipt signing key id, published in the transparency key log before jury evaluation.", signature: "Base64 Ed25519 signature over canonical statement JSON.", posting_tx: "Hash of the persisted oracle transaction, public once broadcast.", posting_raw: "APP_SECRET-encrypted signed oracle transaction, saved before broadcast for identical nonce/byte retries. No private signer key is saved here.", created_at: created } },
};
