import type { TableDoc } from "../types.ts";
import { CREATED, JSON_FIELDS, KEPT, UPDATED, rv } from "./common.ts";

// Providers and attestation: who serves models, what they charge, what they have proved about their software and how they say
// they handle a prompt. These describe providers and models, not callers. The canary, lane-evaluation and probe rows are made
// from prompts the router itself wrote; none is made from a customer's request.

const PROVIDER_ROWS = "Kept while the provider is listed; a provider that leaves is delisted (status), not deleted.";
const CANARY_PROMPTS = "Made from fixed prompts the router wrote itself, not from any customer request.";

export const providerTables: Record<string, TableDoc> = {
  providers: {
    category: "providers",
    purpose: "The provider registry: each upstream that serves models, how to reach it, its status, whether its software is attested, and its bond and payout details.",
    request: "no",
    retention: PROVIDER_ROWS,
    columns: {
      id: "Provider slug, such as deepinfra.",
      name: "Display name.",
      base_url: {
        purpose: "The provider's API address that the router calls.",
        review: rv(["name:network"], "public-reference", "The address of a provider's server, set by the operator. It is not a caller's address."),
      },
      api_key_enc: "The router's own key at that provider, AES-256-GCM encrypted with APP_SECRET.",
      kind: "openai for a standard API, tee for an attested endpoint.",
      headers: {
        purpose: "Extra HTTP headers the router sends to that provider on every call, usually credentials. Stored only as one AES-GCM ciphertext under the router's APP_SECRET.",
        review: rv(["name:network", "type:json"], "config", "Fixed headers the provider's operator supplied in its application, stored encrypted (encrypted_v1). Nothing from a caller's request is ever written to it."),
      },
      data_policy: {
        purpose: "What the provider says about training on prompts, retaining them, retention days and zero-data-retention, as entered by the operator or the provider.",
        review: JSON_FIELDS("Fixed fields (training, retains_prompts, retention_days, zdr, moderated) validated on entry; about the provider's policy, not about any request."),
      },
      datacenter: "Regions the provider lists.",
      attested: "Whether the provider's last verified attestation passed.",
      attestation_url: {
        purpose: "Where the provider publishes its attestation report.",
        review: rv(["name:network"], "public-reference", "The address of a report on a provider's server, set by the operator."),
      },
      attestation_hash: "Hash of the last attestation report the router verified.",
      attested_at: "When it was verified.",
      tee_kind: "The hardware type: tdx, snp, nvidia-cc, tinfoil or dev.",
      classifier_enabled: "Whether the last verified attestation reported the in-enclave hard-block classifier as enabled.",
      bond_usdg: "The provider's bond in USDG base units.",
      anyr_stake: "The provider's $ANYR stake in base units.",
      operator: "The operator's name.",
      payout_mode: "invoice or usdg.",
      payout_address: {
        purpose: "The wallet address payouts go to, when the provider is paid in USDG.",
        review: rv(["name:network"], "wallet-address", "A blockchain wallet address for payouts, not a network address of a caller."),
      },
      status: "applied, shadow, live, suspended or delisted.",
      shadow_until: "When a shadow provider is due to be considered for live.",
      timeout_ms: "Request timeout for this provider.",
      static_models: {
        purpose: "A model list with prices for providers whose own listing lacks pricing.",
        review: JSON_FIELDS("A list of model ids, prices and limits entered by an operator and checked before it is applied."),
      },
      contact: {
        purpose: "A contact for the provider's operator, as given in the provider application.",
        review: rv(["name:network"], "config", "A contact detail for the provider's operator, given by the operator in a provider application. It is not about callers."),
      },
      created_at: CREATED,
      updated_at: UPDATED,
    },
  },

  models: {
    category: "providers",
    purpose: "The model catalogue: id, name, context length, modalities and creator.",
    request: "no",
    retention: KEPT,
    columns: {
      id: "Model id, author/slug.",
      author: "The author part of the id.",
      name: "Display name.",
      description: {
        purpose: "A short description of the model, from the provider listing or an operator.",
        review: rv(["name:content"], "config", "Descriptive text about a model from provider listings; it is catalogue data, not a request."),
      },
      ctx: "Context length in tokens.",
      max_out: "Maximum output tokens.",
      arch: { purpose: "Modality, input and output modalities, tokenizer and instruction type.", review: JSON_FIELDS("Fixed catalogue fields about the model: modality, input_modalities, output_modalities, tokenizer, instruct_type.") },
      hf_repo: "The Hugging Face repository the weights come from, when known.",
      creator: "The creator's payout address, when known.",
      royalty_bps: "The creator's royalty in basis points.",
      created_unix: "When the model was created, in Unix seconds.",
      hidden: "Whether the model is hidden from listings.",
    },
  },

  offers: {
    category: "providers",
    purpose: "What one provider charges to serve one model, and the model's features at that provider.",
    request: "no",
    retention: KEPT,
    columns: {
      model_id: "The model.",
      provider_id: "The provider.",
      provider_model_id: "The id the provider uses for the model.",
      price_prompt: "Pico-USD per prompt token.",
      price_completion: "Pico-USD per completion token.",
      price_request: "Pico-USD per request.",
      price_image: "Pico-USD per image.",
      price_web_search: "Pico-USD per web search.",
      price_reasoning: "Pico-USD per reasoning token.",
      price_cache_read: "Pico-USD per cached prompt token.",
      price_cache_write: "Pico-USD per token written to cache.",
      quant: "Quantisation, such as fp8, or unknown.",
      ctx: "Context length at this provider.",
      max_out: "Maximum output tokens at this provider.",
      supported_parameters: "Request parameters the provider supports.",
      features: { purpose: "Feature flags such as tools or json mode.", review: JSON_FIELDS("Feature flags and limits read from the provider's model listing; about the offer, not any request.") },
      is_moderated: "Whether the provider moderates content.",
      status: "live, shadow or disabled.",
      updated_at: UPDATED,
    },
  },

  canaries: {
    category: "providers",
    purpose: `Results of quantisation checks: known prompts sent to a provider to see whether it serves the precision it declares. ${CANARY_PROMPTS}`,
    request: "no",
    retention: KEPT,
    columns: {
      model_id: "The model checked.",
      provider_id: "The provider checked.",
      ts: "When the check ran.",
      quant_match: "Whether the result matched the declared precision.",
      quant_guess: "The precision the result looks like.",
      distance: "How far the result was from the reference.",
      quality: "A quality score for the result.",
      detail: { purpose: "The check's accuracy, how many prompts were answered, the declared precision and the fingerprint length.", review: JSON_FIELDS("Numbers and the declared precision written by runCanaries (accuracy, answered, declared, logprobs, fingerprint_tokens); the canary prompts are the router's own.") },
    },
  },

  canary_references: {
    category: "providers",
    purpose: "The reference fingerprint of a model at each precision, which canary results are compared to.",
    request: "no",
    retention: KEPT,
    columns: {
      model_id: "The model.",
      quant: "The precision the fingerprint is for: bf16, fp8, int4 and so on.",
      fingerprint: {
        purpose: "The model's output fingerprint at that precision for the router's own canary prompts.",
        review: rv(["name:network", "type:json"], "no-request-content", "A model-behaviour fingerprint (token probabilities on the router's own fixed prompts), not a device or network fingerprint and not a customer request."),
      },
      source: "Where the reference came from.",
      created_at: CREATED,
    },
  },

  attestations: {
    category: "providers",
    purpose: "The result of each attestation run against a provider: whether it passed, the report hash and the measurements it committed to.",
    request: "no",
    retention: KEPT,
    columns: {
      id: "Row number, counting up from 1.",
      provider_id: "The provider.",
      ts: "When the run happened.",
      ok: "Whether it passed.",
      tee_kind: "The hardware type.",
      report_hash: "Hash of the report.",
      nonce: "The fresh nonce the router sent to prove the report was made for this run.",
      measurements: { purpose: "The image, compose and model digests and hardware registers the report committed to.", review: JSON_FIELDS("Digests and register values taken from a verified report.") },
      detail: { purpose: "Why a run failed, or which verifiers accepted it, with the signing address and classifier flag, as short strings and flags written by the attestor.", review: JSON_FIELDS("Written by attestProvider about a report the router fetched with a fresh nonce. An attestation run starts from the router's schedule, so no caller's request can reach this column.") },
    },
  },

  attestation_events: {
    category: "providers",
    purpose: "The public proof-time record: one row per attestor run, canary run or change of the health probe's outcome.",
    request: "no",
    retention: "Rows older than ATTESTATION_HISTORY_DAYS (default 30) are pruned by the attestor job (pruneAttestationEvents); 0 turns recording off.",
    columns: {
      id: "Row number, counting up from 1.",
      provider_id: "The provider.",
      kind: "attestation, canary or probe.",
      ts: "When it happened.",
      ok: "Whether it passed.",
      reason: "A failure code from a fixed list, empty when it passed.",
      simulated: "Whether the evidence came from development mode; never counts as a fresh attestation.",
      tee_kind: "The hardware type.",
      attestation_hash: "The report hash of a passing run.",
      tls_spki_sha256: "SHA-256 of the certificate key the connection was pinned to, when pinned.",
      measurements: { purpose: "Digests and hardware registers of a passing run.", review: JSON_FIELDS("Only digests (image, compose, model) and register values; the table's comment states nothing raw from the provider is stored.") },
      measurement_changed: "Whether the measurement differs from the previous passing run.",
      verifiers: { purpose: "The names of the verifiers that accepted the quote.", review: JSON_FIELDS("A list of verifier names configured by the operator.") },
      detail: { purpose: "Further check results as codes and numbers.", review: JSON_FIELDS("Written by the attestation-events code from fixed fields; the table's comment states nothing raw from the provider is stored.") },
    },
  },

  measurements: {
    category: "providers",
    purpose: "The image, compose and model digests a provider's confidential endpoint has been seen running, each bound into a hardware quote a verifier accepted, with whether the digest was found in a public log.",
    request: "no",
    retention: "History is kept: a superseded measurement gets superseded_at and stays.",
    columns: {
      id: "Row number, counting up from 1.",
      provider_id: "The provider.",
      image_digest: "The container image digest.",
      compose_hash: "The hash of the deployment definition.",
      model_digest: "The digest of the model weights.",
      status: "observed, ready, registered or revoked.",
      verifier: "Which verifiers accepted the quote, comma separated.",
      tee_kind: "The hardware type.",
      quote: "The verified hardware quote, hex.",
      quote_proof_hash: "keccak256 of the quote bytes.",
      report_hash: "The attestation report hash that produced the row.",
      attested_at: "When it was attested.",
      last_seen_at: "When it was last seen.",
      rekor_uuid: "The public-log entry id, when found.",
      rekor_entry: "The entry hash inside that id.",
      rekor_log_index: "The entry's index in the public log.",
      rekor_kind: "The entry type.",
      rekor_integrated_at: "When the public log integrated it.",
      rekor_inclusion_verified: "Whether the inclusion proof verified.",
      rekor_checkpoint_verified: "Whether the log's checkpoint signature verified.",
      rekor_checked_at: "When the public log was last checked.",
      rekor_error: {
        purpose: "The last error from checking the public log, as a short code or message.",
        review: rv(["name:content"], "no-request-content", "An error string produced while looking up a public log entry; nothing in this lookup involves a caller's request."),
      },
      calldata: "Prepared registry call data, when built.",
      calldata_target: "The registry contract it is for.",
      calldata_built_at: "When it was built.",
      tx_hash: "The registering transaction.",
      registered_at: "When it was registered.",
      revoked_at: "When it was revoked.",
      superseded_at: "When a later verified quote committed to other digests.",
      superseded_by: "The row that replaced this one.",
      created_at: CREATED,
      updated_at: UPDATED,
    },
  },

  measurement_bundles: {
    category: "providers",
    purpose: "Signed measurement bundles: what a provider's measurement is made of, signed with the measurement key, recorded in a public log and verified by the router.",
    request: "no",
    retention: KEPT,
    columns: {
      id: "Row number, counting up from 1.",
      provider_id: "The provider.",
      compose_hash: "The deployment hash the bundle describes.",
      bundle_digest: "SHA-256 of the canonical bundle bytes.",
      bundle: { purpose: "The bundle itself: the components a measurement is made of.", review: JSON_FIELDS("A signed, canonical bundle of digests and component names that an operator hands over and the router verifies.") },
      signature: "The bundle's signature, base64.",
      signer_key_id: "SHA-256 of the signer's public key info.",
      status: "pending, verified or rejected.",
      rekor_uuid: "The public-log entry id.",
      rekor_entry: "The entry hash inside that id.",
      rekor_log_index: "The entry's index in the public log.",
      rekor_integrated_at: "When the public log integrated it.",
      rekor_entry_json: { purpose: "The public-log entry as the log returned it.", review: JSON_FIELDS("The response of a public transparency log for the bundle's entry (body, proof, signed timestamp).") },
      rekor_inclusion_verified: "Whether the inclusion proof verified.",
      rekor_checkpoint_verified: "Whether the log's checkpoint signature verified.",
      rekor_set_verified: "Whether the signed entry timestamp verified.",
      checked_at: "When the log was last checked.",
      verified_at: "When the bundle verified.",
      error: {
        purpose: "Why the bundle was rejected or could not be checked.",
        review: rv(["name:content"], "no-request-content", "An error string produced while verifying a bundle and its public-log entry; nothing in that check involves a caller's request."),
      },
      created_at: CREATED,
      updated_at: UPDATED,
    },
  },

  provider_disclosure: {
    category: "providers",
    purpose: "What a provider says, and can prove, about how it handles a prompt: retention, jurisdiction, legal hold and training use, each with a source and a date. Curated by an operator; nothing here comes from traffic.",
    request: "no",
    retention: "Kept and replaced in place when an operator updates a provider's profile.",
    columns: {
      provider_id: "The provider.",
      retention: "attested, policy or logs (the most conservative when there is no row).",
      jurisdiction: "The provider's jurisdiction, or unknown.",
      legal_hold: "Whether a legal hold is declared; empty means not declared.",
      legal_hold_note: {
        purpose: "A note on the legal hold, written by an operator.",
        review: rv(["name:content"], "config", "Free text written by an operator about a provider's declared legal hold; it is not derived from any request."),
      },
      training_use: "none, opt_in, yes or unknown.",
      claims: { purpose: "For each stated value, the document it comes from and its date.", review: JSON_FIELDS("A map of claim name to { source, as_of } written by an operator.") },
      updated_at: UPDATED,
    },
  },

  models_lane: {
    category: "providers",
    purpose: "Per-model metadata for open-weights variants: which lane a model can be served on, its base model, licence and weights source.",
    request: "no",
    retention: KEPT,
    columns: {
      model_id: "The model.",
      variant: "mainstream, native_low_refusal or abliterated.",
      status: "servable or candidate (not approved for serving).",
      base_model: "The model it derives from.",
      license: "The licence identifier from the weights' model card.",
      weights_source: "Where the weights come from.",
      weights_revision: "The commit the weights were taken from.",
      weights_digest: "SHA-256 of the weights manifest, when there is one.",
      creator_handle: "The uploader's Hugging Face handle.",
      updated_at: UPDATED,
    },
  },

  lane_candidates: {
    category: "providers",
    purpose: "New open-weights uploads found on Hugging Face that derive from an approved base model, with their evaluation status.",
    request: "no",
    retention: KEPT,
    columns: {
      id: "Row number, counting up from 1.",
      hf_repo: "The repository.",
      base_model: "The base model.",
      revision: "The revision seen at discovery.",
      license: "The licence.",
      variant: "The variant.",
      creator_handle: "The uploader's handle.",
      status: "discovered, rejected, evaluated, failed, approved or servable.",
      reason: "Why a candidate was rejected.",
      model_id: "The catalogue model id it is served under.",
      endpoint_provider: {
        purpose: "The provider whose offer for the model is evaluated.",
        review: rv(["name:network"], "public-reference", "A provider slug (a short name such as deepinfra), not a network address."),
      },
      source_created_at: "When the repository was created.",
      approved_by: "Who approved it.",
      approved_at: "When it was approved.",
      approval_note: {
        purpose: "A note written by the approving operator.",
        review: rv(["name:content"], "config", "Free text written by an operator when approving a candidate; not derived from any request."),
      },
      servable_at: "When it became servable.",
      created_at: CREATED,
      updated_at: UPDATED,
    },
  },

  lane_evals: {
    category: "providers",
    purpose: `One row per evaluation run of a candidate endpoint: refusal rate, capability score and canary accuracy. ${CANARY_PROMPTS}`,
    request: "no",
    retention: KEPT,
    columns: {
      id: "Row number, counting up from 1.",
      candidate_id: "The candidate evaluated.",
      ts: "When it ran.",
      provider_id: "The provider evaluated.",
      model_id: "The model evaluated.",
      refusal_rate: "Share of the benign probe prompts that were refused.",
      capability_score: "Share of the exact-check prompts answered correctly.",
      canary_accuracy: "The canary exact-match score.",
      canary_quant_match: "Whether the canary matched the declared precision.",
      passed: "Whether the candidate passed.",
      detail: { purpose: "Scores and counts for the run.", review: JSON_FIELDS("Numbers written by the evaluation code; the prompts used are the router's own fixed sets.") },
    },
  },

  lane_claims: {
    category: "providers",
    purpose: "Creator royalty claims: the router issues a challenge, the uploader publishes it in their Hugging Face repository, and the router checks it.",
    request: "no",
    retention: KEPT,
    columns: {
      id: "Claim id.",
      model_id: "The model.",
      hf_repo: "The repository.",
      handle: "The uploader's Hugging Face handle.",
      address: {
        purpose: "The wallet address royalties are to be sent to.",
        review: rv(["name:network"], "wallet-address", "A blockchain wallet address supplied by the creator, not a network address."),
      },
      challenge: "The challenge text the uploader must publish.",
      status: "pending or verified.",
      created_at: CREATED,
      expires_at: "When the challenge expires.",
      verified_at: "When it was verified.",
      onchain_tx: "The transaction that recorded the claim.",
    },
  },
};
