// Generates src/chain/abis.ts from the Solidity interfaces (and implementations when built).
// Usage: bun scripts/export-abis.ts   (runs `forge build` into a private out dir first)
import { $ } from "bun";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const out = resolve(root, ".data/abi-out");
const cache = resolve(root, ".data/abi-cache");
mkdirSync(out, { recursive: true });
const forge = process.env.FOUNDRY_BIN ? `${process.env.FOUNDRY_BIN}/forge` : Bun.which("forge") ?? `${process.env.HOME}/.foundry/bin/forge`;
await $`${forge} build --out ${out} --cache-path ${cache} --root ${resolve(root, "contracts")}`.quiet();

// Implementation ABIs (supersets of the interfaces): name -> [artifact file, contract]
const contracts: Record<string, [string, string]> = {
  Credits: ["Credits.sol", "Credits"],
  CallPay: ["CallPay.sol", "CallPay"],
  PayWithStock: ["PayWithStock.sol", "PayWithStock"],
  StockOracle: ["ChainlinkStockOracle.sol", "ChainlinkStockOracle"],
  ProviderBond: ["ProviderBond.sol", "ProviderBond"],
  ReceiptAnchor: ["ReceiptAnchor.sol", "ReceiptAnchor"],
  MeasurementRegistry: ["MeasurementRegistry.sol", "MeasurementRegistry"],
  Royalty: ["Royalty.sol", "Royalty"],
  AnyrPaymaster: ["AnyrPaymaster.sol", "AnyrPaymaster"],
  UniswapV3Adapter: ["UniswapV3Adapter.sol", "UniswapV3Adapter"],
  UniswapV4Adapter: ["UniswapV4Adapter.sol", "UniswapV4Adapter"],
  UiMultiplier: ["IStockOracle.sol", "IUiMultiplier"],
};
let ts = "// Generated by scripts/export-abis.ts from the compiled contracts. Do not edit.\n\n";
for (const [name, [file, contract]] of Object.entries(contracts)) {
  const p = resolve(out, file, `${contract}.json`);
  if (!existsSync(p)) throw new Error(`missing ABI ${p}`);
  const abi = JSON.parse(readFileSync(p, "utf8")).abi;
  ts += `export const ${name}Abi = ${JSON.stringify(abi)} as const;\n\n`;
}
ts += `export const erc20Abi = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "s", type: "address" }, { name: "v", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "o", type: "address" }, { name: "s", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "v", type: "uint256" }], outputs: [{ type: "bool" }] },
] as const;

export const aggregatorV3Abi = [
  { type: "function", name: "latestRoundData", stateMutability: "view", inputs: [], outputs: [{ name: "roundId", type: "uint80" }, { name: "answer", type: "int256" }, { name: "startedAt", type: "uint256" }, { name: "updatedAt", type: "uint256" }, { name: "answeredInRound", type: "uint80" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
] as const;
`;
writeFileSync(resolve(root, "src/chain/abis.ts"), ts);
console.log("wrote src/chain/abis.ts");
