// Local provider fleet for development and the demo:
//   bun scripts/mock-providers.ts      -> 3 OpenAI-compatible mock providers + config/providers.local.yaml
// Behaviours can be changed live: curl -XPOST localhost:9101/_control -d '{"behaviour":"empty200"}'
import { writeFileSync } from "node:fs";
import { serveMockProvider } from "../src/providers/mock.ts";

const models = {
  llama: { id: "llama-3.3-70b", slug: "meta-llama/llama-3.3-70b-instruct", prompt: "0.0000001", completion: "0.00000032" },
  llama2: { id: "llama-3.3-70b", slug: "meta-llama/llama-3.3-70b-instruct", prompt: "0.00000023", completion: "0.0000004" },
  qwen: { id: "qwen3-32b", slug: "qwen/qwen3-32b", prompt: "0.0000001", completion: "0.0000003" },
  embed: { id: "embed-small", slug: "acme/embed-small", prompt: "0.00000002", completion: "0", output: ["embeddings"] },
};
const fleet = [
  { id: "mock-cheap", name: "Mock Cheap", port: 9101, models: [models.llama, models.qwen, models.embed] },
  { id: "mock-fast", name: "Mock Fast", port: 9102, models: [models.llama2] },
  { id: "mock-tee", name: "Mock TEE", port: 9103, models: [models.llama2], tee: "dev" as const },
];
const running = fleet.map((f) => ({ f, s: serveMockProvider({ name: f.name, models: f.models, tee: f.tee ?? null }, f.port) }));
const yaml = [
  "# Generated by scripts/mock-providers.ts — local mock providers (not real inference).",
  "providers:",
  ...running.flatMap(({ f, s }) => [
    `  - id: ${f.id}`,
    `    name: ${f.name}`,
    `    base_url: ${s.url}`,
    `    status: live`,
    `    data_policy: { training: false, retains_prompts: false, zdr: true }`,
    ...(f.tee ? [`    tee: { kind: dev, attestation_url: ${s.url}/attestation }`] : []),
  ]),
].join("\n");
writeFileSync("config/providers.local.yaml", yaml + "\n");
for (const { f, s } of running) console.log(`${f.id.padEnd(10)} ${s.url}`);
console.log("wrote config/providers.local.yaml — seed with: bun scripts/seed.ts config/providers.local.yaml");
