import PageFrame from '../../components/PageFrame';
import {Button,Code} from '../../components/UI';
export const metadata={title:'Case study: a call paid with a Stock Token — Anyroute'};
export default function Case(){return <PageFrame><main className="page-main" id="content">
  <div className="page-title" data-reveal><span className="eyebrow">CASE STUDY / EXAMPLE PRODUCT WORKFLOW</span><h1>One call.<br/>A complete payment trail.</h1><p>How an agent pays for inference with a Stock Token, without changing the model request.</p></div>
  <article className="page-body prose case-body">
    <div className="note" data-reveal>A walkthrough of the Stock Token payment flow as Anyroute implements it. It is not a customer result, a record of a live transaction or an investment recommendation.</div>
    <section className="case-intro" data-reveal><h2>The starting point</h2><p>A developer wants a research agent to run within a clear spending boundary. The agent uses a familiar chat API, while its capped session wallet holds a supported Stock Token. The goal is to connect those two systems with an auditable payment trail.</p></section>
    <ol className="case-steps" data-progress>
      <li className="case-step" data-reveal><h2><span className="step-n">01 /</span> Set the boundary.</h2><p>The developer chooses a registered token and a daily limit. The wallet opens a session on the PayWithStock contract for this key, capped in token units per UTC day. The router can only spend within that cap, and the owner can close the session instantly. The agent never gets unrestricted spending authority.</p></li>
      <li className="case-step" data-reveal><h2><span className="step-n">02 /</span> Route the request.</h2><p>The API request keeps its usual model and messages. A payment header expresses the preferred token. The call is priced in USDG and routed to an eligible provider.</p><Code label="Payment preference">{JSON.stringify({endpoint:'POST /api/v1/chat/completions',headers:{Authorization:'Bearer <ANYROUTE_API_KEY>','X-Pay-With':'NVDA'},body:{model:'author/model',messages:[{role:'user',content:'Your prompt'}]}},null,2)}</Code></li>
      <li className="case-step" data-reveal><h2><span className="step-n">03 /</span> Settle with limits.</h2><p>Small call costs accrue in USDG. At $1, or after 24 hours, the router asks the contract to swap exactly the USDG owed: the contract reads the Chainlink fair value (which already includes the token’s multiplier), enforces the slippage bound and the daily cap, and credits the key. If the oracle is stale or paused, the call falls back to prepaid USDG when available, or returns a payment-required state.</p></li>
      <li className="case-step" data-reveal><h2><span className="step-n">04 /</span> Keep the evidence.</h2><p>The generation receipt identifies the model, provider, token usage and USDG cost. After allocation, its payment details identify the Stock Token units, fair-price input and swap transaction. A later anchor adds proof of inclusion.</p></li>
    </ol>
    <div className="case-outcomes" data-stagger><article className="route-card" data-reveal><span className="eyebrow">USER CONTROL</span><h3>Cap. Pause. Close.</h3><p>A clear spending boundary and an immediate way to end a session.</p><div className="card-ramp" aria-hidden="true"/></article><article className="route-card" data-reveal><span className="eyebrow">VERIFIABLE RESULT</span><h3>Follow the receipt.</h3><p>Generation, cost, token allocation and settlement evidence in one trace.</p><div className="card-ramp" aria-hidden="true"/></article></div>
    <section className="case-cta dark" data-reveal><span className="empty-grid" aria-hidden="true"/><h2>Try it</h2><p>Open a session in the dashboard’s Payments tab, choose NVDA in the playground and inspect the receipt’s paid-with line. The monthly statement lists every swap with its per-call token allocation. A sample workspace with fictional values is also available if you only want to explore.</p><Button href="/dashboard/#payments">Try the payment workflow</Button></section>
  </article>
</main></PageFrame>}
