export default function SecurityAlertsDocs() {
  return <section id="security-alerts"><h2>Security alerts</h2>
    <p>Keep a record of security changes in your account inbox: API keys created, switched off or changed; wallet sign-ins; saved rulebooks and spending limits; Stop and Resume; Telegram links; and added team members or changed roles. Alerts name the key and the change, including changes you make yourself. Wallet sign-ins show only a shortened version of your own address.</p>
    <p>This feature is not switched on yet. SECURITY_ALERTS_ENABLED defaults to false. When enabled, Security alerts starts on in account Settings. A worker checks recorded changes every 30 seconds. Turn the setting off to mute new alerts; earlier inbox items stay. Changes made while the service flag is off are not reconstructed later.</p>
    <p>GET /api/v1/account/security-alerts reads data.enabled. PATCH accepts only an enabled boolean and returns the saved value. Both require an active account management Bearer key, exclude session keys and return no-store. With the feature flag off, both return 404. GET /api/v1/inbox uses its existing authentication and since parameter; security items have kind security, id, at, title, status null, href /dashboard/#settings and unread. Management keys see account changes; team owners and administrators see only their team. Ordinary and session keys see no security items.</p>
    <p>Each recorded event produces one inbox item. Key changes made in one save share an item. Team actions authenticated directly with a wallet or passkey name that member type. Linked Telegram accounts receive only alerts their current rights allow. Telegram can read alert text and key names. An unlink prevents later messages to that link; other eligible links can receive its unlink alert.</p>
    <p>Recorded alerts stay for up to 90 days after the worker claims them, with cleanup while the flag is on. The worker claims before attempting Telegram once per link. Interrupted or failed sends can leave an inbox item without a Telegram message. Pending events wait for a worker. These records contain no key secret, rulebook contents, Stop reason or prompt text. Anyroute reads ordinary model request text in memory.</p>
  </section>;
}
