import { parseAbi } from "viem";
// HostBond.sol's complete event surface, including inherited ownership events.
export const hostBondAbi = parseAbi([
  "event Bonded(bytes32 indexed hostId, address indexed operator, uint256 amount, uint256 total)",
  "event UnbondRequested(bytes32 indexed hostId, uint256 amount, uint64 availableAt)",
  "event UnbondCancelled(bytes32 indexed hostId)",
  "event Unbonded(bytes32 indexed hostId, address indexed to, uint256 amount)",
  "event SlashProposed(uint256 indexed slashId, bytes32 indexed hostId, uint8 reason, uint256 amount, bytes32 evidenceRoot, uint64 executableAt)",
  "event SlashDisputed(uint256 indexed slashId, bytes32 disputeHash)",
  "event SlashApproved(uint256 indexed slashId, bytes32 disputeHash)",
  "event SlashApprovalsRevoked()",
  "event SlashCancelled(uint256 indexed slashId)",
  "event SlashExecuted(uint256 indexed slashId, bytes32 indexed hostId, uint256 amount, bool delisted)",
  "event Delisted(bytes32 indexed hostId)",
  "event MinBondSet(uint256 minBond)",
  "event SlasherSet(address indexed slasher)",
  "event RefundPoolSet(address indexed pool)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)",
  "function slasher() view returns (address)",
  "function minBond() view returns (uint256)",
  "function approvalGeneration() view returns (uint256)",
  "function slashApproval(uint256) view returns (uint256)",
  "function operatorOf(bytes32) view returns (address)",
  "function bondOf(bytes32) view returns (uint256)",
  "function slashes(uint256) view returns (bytes32 hostId, uint256 amount, bytes32 evidenceRoot, bytes32 disputeHash, uint64 executableAt, uint8 reason, bool delist, uint8 status)",
  "function proposeSlash(bytes32 hostId, uint8 reason, uint256 amount, bytes32 evidenceRoot, bool delist) returns (uint256 slashId)",
  "function executeSlash(uint256 slashId)",
]);
